import type { PokemonPaletteGuessConfig, PokemonPaletteHintKind } from '@pokemon-universe/shared';
import { Lightbulb } from 'lucide-react';
import { GenerationSelector } from '../../components/GenerationSelector';
import { ConfigRange } from '../../room/ConfigRange';

export function PokemonPaletteGuessConfigPanel({ config, disabled, onChange }: { config: unknown; disabled: boolean; onChange(config: unknown): Promise<void> }) {
  const value = config as PokemonPaletteGuessConfig;
  const hintOptions: Array<{ id: PokemonPaletteHintKind; label: string }> = [
    { id: 'GENERATION', label: 'Generación' }, { id: 'TYPE', label: 'Tipos' }, { id: 'TYPE_COUNT', label: 'Nº de tipos' },
    { id: 'EVOLUTION', label: 'Etapa evolutiva' }, { id: 'CATEGORY', label: 'Legendario / Mítico' },
  ];
  const toggleHint = (id: PokemonPaletteHintKind) => void onChange({ ...value, hintKinds: value.hintKinds.includes(id) ? value.hintKinds.filter((kind) => kind !== id) : [...value.hintKinds, id] });
  return <fieldset disabled={disabled} className="space-y-6"><GenerationSelector selected={value.generations} label="Generaciones" description="Solo entrarán Pokémon cuya paleta haya sido persistida por DataSync." onChange={(generations) => void onChange({ ...value, generations })} /><section><span className="label">Máximo de colores visibles</span><div className="grid max-w-xl grid-cols-4 gap-2">{[5, 6, 7, 8].map((size) => <button key={size} type="button" aria-pressed={value.paletteSize === size} onClick={() => void onChange({ ...value, paletteSize: size })} className={`min-h-12 rounded-xl border font-extrabold transition-colors ${value.paletteSize === size ? 'border-aqua bg-aqua text-night' : 'border-ink/10 bg-surface-raised hover:border-aqua/60'}`}>{size}</button>)}</div><p className="mt-2 text-sm font-bold text-ink/60">Se mostrarán todos los colores dominantes disponibles hasta este máximo; nunca se descartará un Pokémon por tener menos.</p></section><section className="rounded-2xl border border-ink/10 bg-ink/[.025] p-4"><button type="button" aria-pressed={value.hintsEnabled} onClick={() => void onChange({ ...value, hintsEnabled: !value.hintsEnabled })} className="flex w-full items-center gap-3 text-left"><span className={`grid h-11 w-11 place-items-center rounded-xl ${value.hintsEnabled ? 'bg-electric text-night' : 'bg-ink/10'}`}><Lightbulb /></span><span className="flex-1"><strong className="block font-display text-xl">Pistas adicionales</strong><small className="font-bold text-ink/65">{value.hintsEnabled ? 'Visibles públicamente desde el inicio.' : 'Solo se mostrará la paleta.'}</small></span><span className={`rounded-full px-3 py-1 text-xs font-black ${value.hintsEnabled ? 'bg-leaf text-night' : 'bg-ink/10 text-ink/60'}`}>{value.hintsEnabled ? 'ON' : 'OFF'}</span></button>{value.hintsEnabled && <div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{hintOptions.map((hint) => <label key={hint.id} className="flex min-h-11 cursor-pointer items-center gap-2 rounded-xl bg-surface-raised px-3 font-bold"><input type="checkbox" checked={value.hintKinds.includes(hint.id)} onChange={() => toggleHint(hint.id)} /> {hint.label}</label>)}</div>}</section><div className="grid gap-4 md:grid-cols-2"><ConfigRange label="Tiempo por ronda" value={value.roundSeconds} min={10} max={60} step={5} disabled={disabled} formatValue={(seconds) => `${seconds} segundos`} onCommit={(roundSeconds) => onChange({ ...value, roundSeconds })} /><ConfigRange label="Número de rondas" value={value.rounds} min={1} max={20} disabled={disabled} accent="aqua" formatValue={(rounds) => `${rounds} rondas`} onCommit={(rounds) => onChange({ ...value, rounds })} /></div></fieldset>;
}
