import type { SubjectiveCategory } from '../contracts.js';

const texts = [
  'Pokémon que parecen mascotas',
  'Pokémon que parecen peligrosos',
  'Pokémon que darían miedo encontrarse de noche',
  'Pokémon que llevarías de vacaciones',
  'Pokémon que llevarías a una isla desierta',
  'Pokémon que elegirías como guardaespaldas',
  'Pokémon que serían buenos compañeros de piso',
  'Pokémon que no dejarías entrar en tu casa',
  'Pokémon que llevarías a una fiesta',
  'Pokémon que parecen villanos',
  'Pokémon que parecen héroes',
  'Pokémon que parecen muy inteligentes',
  'Pokémon que parecen bastante tontos',
  'Pokémon que parecen más fuertes de lo que realmente son',
  'Pokémon que parecen adorables',
  'Pokémon que parecen juguetes',
  'Pokémon que parecen comida',
  'Pokémon que usarías como almohada',
  'Pokémon que usarías como montura',
  'Pokémon que podrían protagonizar una película',
  'Pokémon que podrían ser una mascota famosa',
  'Pokémon que parecen de otro planeta',
  'Pokémon que podrían vivir perfectamente en una ciudad',
  'Pokémon que parecen caros',
  'Pokémon que parecen pobres',
  'Pokémon que parecen perros',
  'Pokémon que parecen gatos',
  'Pokémon que parecen dragones',
  'Pokémon que parecen robots',
  'Pokémon que parecen dinosaurios',
  'Pokémon que parecen animales marinos',
  'Pokémon que llevarías a una cita',
  'Pokémon que elegirías para una pelea',
  'Pokémon con los que te irías de aventura',
  'Pokémon en los que confiarías',
  'Pokémon de los que desconfiarías',
  'Pokémon que podrían trabajar en un hospital',
  'Pokémon que podrían trabajar de policía',
  'Pokémon que podrían cocinar bien',
  'Pokémon que serían malos profesores',
  'Pokémon que parecen tener mucho dinero',
  'Pokémon que probablemente romperían cosas en tu casa',
  'Pokémon que adoptarías',
  'Pokémon que jamás adoptarías',
  'Pokémon que parecen tener mal carácter',
  'Pokémon que parecen muy tranquilos',
  'Pokémon con los que te gustaría viajar',
  'Pokémon que podrían ser buenos influencers',
  'Pokémon que parecen jefes finales',
] as const;

/** Data-only official catalog. Categories are subjective prompts, never validation rules. */
export const officialSubjectiveCategories: readonly SubjectiveCategory[] = texts.map((text, index) => ({
  id: `official-${String(index + 1).padStart(2, '0')}`,
  text,
}));
