import type { WhoIsWhoPokemonConfig } from '@pokemon-universe/shared';
import { Grid3X3, Shuffle, Target, Timer, Users } from 'lucide-react';
import { GenerationSelector } from '../../components/GenerationSelector';

const boardSizes = [5, 10, 16, 24, 36, 50];
const turnTimes = [20, 30, 40, 60, 90];
const roundCounts = [5, 10, 15, 20, 25];
export function WhoIsWhoPokemonConfigPanel({ config, disabled, onChange }: { config: unknown; disabled: boolean; onChange(config: unknown): Promise<void> }) {
  const value = config as WhoIsWhoPokemonConfig;
  return <fieldset disabled={disabled} className="space-y-6"><GenerationSelector selected={value.generations} label="Generaciones del tablero" description="El pool se mezcla en el servidor antes de repartir los secretos." onChange={(generations) => void onChange({ ...value, generations })} />
    <section><span className="label">Pokémon secreto</span><div className="grid gap-2 sm:grid-cols-2"><button type="button" aria-pressed={value.secretSelection === 'RANDOM'} onClick={() => void onChange({ ...value, secretSelection: 'RANDOM' })} className={`flex min-h-16 items-center gap-3 rounded-xl border p-3 text-left ${value.secretSelection === 'RANDOM' ? 'border-aqua bg-aqua/10' : 'border-ink/10 bg-surface-raised'}`}><Shuffle size={20} /><span><strong className="block">Aleatorio</strong><small className="font-bold text-ink/60">El servidor asigna uno a cada equipo.</small></span></button><button type="button" aria-pressed={value.secretSelection === 'PLAYER_CHOICE'} onClick={() => void onChange({ ...value, secretSelection: 'PLAYER_CHOICE' })} className={`flex min-h-16 items-center gap-3 rounded-xl border p-3 text-left ${value.secretSelection === 'PLAYER_CHOICE' ? 'border-aqua bg-aqua/10' : 'border-ink/10 bg-surface-raised'}`}><Target size={20} /><span><strong className="block">Elegido por el equipo</strong><small className="font-bold text-ink/60">Cada equipo elige en secreto una carta del tablero.</small></span></button></div></section>
    <section><span className="label flex items-center gap-2"><Grid3X3 size={17} /> Pokémon en el tablero</span><div className="grid grid-cols-3 gap-2 sm:grid-cols-6">{boardSizes.map((boardSize) => <button type="button" key={boardSize} aria-pressed={value.boardSize === boardSize} onClick={() => void onChange({ ...value, boardSize })} className={`min-h-11 rounded-xl border font-extrabold ${value.boardSize === boardSize ? 'border-aqua bg-aqua text-night' : 'border-ink/10 bg-surface-raised text-ink/65 hover:border-aqua'}`}>{boardSize}</button>)}</div><p className="mt-2 text-sm font-bold text-ink/60">Rango permitido: 5–50 Pokémon.</p></section>
    <div className="grid gap-5 lg:grid-cols-2"><section><span className="label flex items-center gap-2"><Timer size={17} /> Tiempo por turno</span><div className="grid grid-cols-3 gap-2 sm:grid-cols-5">{turnTimes.map((turnSeconds) => <button type="button" key={turnSeconds} aria-pressed={value.turnSeconds === turnSeconds} onClick={() => void onChange({ ...value, turnSeconds })} className={`min-h-11 rounded-xl border font-extrabold ${value.turnSeconds === turnSeconds ? 'border-electric bg-electric text-night' : 'border-ink/10 bg-surface-raised text-ink/65 hover:border-aqua'}`}>{turnSeconds}s</button>)}</div></section><section><span className="label flex items-center gap-2"><Users size={17} /> Rondas máximas</span><div className="grid grid-cols-3 gap-2 sm:grid-cols-5">{roundCounts.map((rounds) => <button type="button" key={rounds} aria-pressed={value.rounds === rounds} onClick={() => void onChange({ ...value, rounds })} className={`min-h-11 rounded-xl border font-extrabold ${value.rounds === rounds ? 'border-electric bg-electric text-night' : 'border-ink/10 bg-surface-raised text-ink/65 hover:border-aqua'}`}>{rounds}</button>)}</div></section></div>
    <button type="button" aria-pressed={value.includeForms} onClick={() => void onChange({ ...value, includeForms: !value.includeForms })} className={`flex min-h-16 w-full items-center gap-3 rounded-xl border p-3 text-left ${value.includeForms ? 'border-aqua bg-aqua/10' : 'border-ink/10 bg-surface-raised'}`}><span className="min-w-0 flex-1"><strong className="block">Incluir formas regionales y variantes</strong><small className="font-bold text-ink/60">Usa todas las formas que el PokémonRepository marque como compatibles.</small></span><span className="font-black text-leaf">{value.includeForms ? '✓' : ''}</span></button>
  </fieldset>;
}
