import type { GuessFromStatsHint, GuessFromStatsPlayerState, GuessFromStatsPokemonReveal, GuessFromStatsPublicState, GuessFromStatsVisibleStat, Pokemon, PokemonLegendaryStatus, RoomView } from '@pokemon-universe/shared';
import { BarChart3, CheckCircle2, Clock3, Eye, History, Lightbulb, Search, XCircle } from 'lucide-react';
import { memo, useEffect, useMemo, useState } from 'react';
import { Avatar } from '../components/Avatar';
import { PokemonTypeBadge } from '../components/PokemonTypeBadge';
import { api } from '../lib/api';
import { PokemonSelector } from './PokemonSelector';

const EMPTY_LOCKED = new Set<string>();
const statLabels: Record<GuessFromStatsVisibleStat['key'], string> = { hp: 'PS', attack: 'Ataque', defense: 'Defensa', specialAttack: 'At. Esp.', specialDefense: 'Def. Esp.', speed: 'Velocidad', bst: 'Total (BST)' };
const categoryLabels: Record<PokemonLegendaryStatus, string> = { NORMAL: 'Normal', LEGENDARY: 'Legendario', MYTHICAL: 'Mítico' };
const evolutionLabels = { BASE: 'Pokémon base', MIDDLE: 'Evolución intermedia', FINAL: 'Evolución final', NO_EVOLUTION: 'No evoluciona' } as const;
const ordinal = (value: number) => `${value}.º`;

const ServerTimer = memo(function ServerTimer({ deadline, serverOffset, label = 'Tiempo' }: { deadline: number | null; serverOffset: number; label?: string }) {
  const [now, setNow] = useState(Date.now()); useEffect(() => { setNow(Date.now()); if (!deadline) return undefined; const timer = window.setInterval(() => setNow(Date.now()), 250); return () => window.clearInterval(timer); }, [deadline]);
  const remaining = deadline ? Math.max(0, Math.ceil((deadline - now - serverOffset) / 1_000)) : 0;
  return <div className="text-center" role="timer" aria-label={`${remaining} segundos restantes`}><span className="block text-[10px] font-black uppercase tracking-[.15em] text-ink/40">{label}</span><strong className={`inline-flex min-w-[4.5ch] items-center justify-center gap-1.5 font-display text-3xl tabular-nums ${remaining <= 5 ? 'pokeddle-timer-urgent text-berry' : remaining <= 10 ? 'text-electric' : 'text-aqua'}`}><Clock3 size={21} />{remaining}s</strong></div>;
});

function StatsGrid({ stats, compact = false }: { stats: GuessFromStatsVisibleStat[]; compact?: boolean }) {
  return <section aria-label="Estadísticas base" className={`grid gap-2 ${compact ? 'grid-cols-2 sm:grid-cols-3' : 'grid-cols-2 sm:grid-cols-3'}`}>{stats.map((stat) => <article key={stat.key} className={`rounded-2xl bg-ink/[0.045] text-center ${compact ? 'p-2' : 'p-3 sm:p-4'}`}><span className="block text-[10px] font-black uppercase tracking-wider text-ink/40">{statLabels[stat.key]}</span><strong className={`block font-display tabular-nums ${compact ? 'text-2xl' : 'text-4xl sm:text-5xl'}`}>{stat.value}</strong><span className="mt-2 block h-1.5 overflow-hidden rounded-full bg-ink/10" aria-hidden="true"><span className="block h-full rounded-full bg-gradient-to-r from-aqua to-electric" style={{ width: `${Math.min(100, stat.value / 255 * 100)}%` }} /></span></article>)}</section>;
}

function HintPanel({ hints }: { hints: GuessFromStatsHint[] }) {
  if (!hints.length) return null;
  return <section aria-label="Pistas adicionales" className="flex flex-wrap items-center gap-2 rounded-2xl border border-electric/20 bg-electric/[0.06] p-3"><span className="flex items-center gap-1.5 text-xs font-black uppercase tracking-wider text-electric"><Lightbulb size={17} /> Pistas</span>{hints.map((hint, index) => {
    if (hint.kind === 'TYPES') return <span key={`${hint.kind}-${index}`} className="flex flex-wrap gap-1">{hint.value.map((type) => <PokemonTypeBadge key={type} type={type} compact />)}</span>;
    const text = hint.kind === 'GENERATION' ? `Generación ${hint.value}` : hint.kind === 'TYPE_COUNT' ? hint.value === 1 ? 'Monotipo' : 'Doble tipo' : hint.kind === 'EVOLUTION' ? evolutionLabels[hint.value] : hint.kind === 'HEIGHT' ? `Altura ${(hint.decimeters / 10).toFixed(1)} m` : hint.kind === 'WEIGHT' ? `Peso ${(hint.hectograms / 10).toFixed(1)} kg` : categoryLabels[hint.value];
    return <span key={`${hint.kind}-${index}`} className="rounded-full border border-electric/20 bg-night/20 px-3 py-1.5 text-sm font-extrabold text-electric">{text}</span>;
  })}</section>;
}

function GuessPanel({ pokemon, player, game, serverOffset, participating, loadError, actionError, onGuess }: { pokemon: Pokemon[]; player: GuessFromStatsPlayerState; game: GuessFromStatsPublicState; serverOffset: number; participating: boolean; loadError: string; actionError: string; onGuess(id: string): Promise<void> }) {
  const [now, setNow] = useState(Date.now()); useEffect(() => { if (!player.cooldownUntil) return undefined; const timer = window.setInterval(() => setNow(Date.now()), 100); return () => window.clearInterval(timer); }, [player.cooldownUntil]); const cooldownMs = Math.max(0, (player.cooldownUntil ?? 0) - now - serverOffset);
  if (!participating) return <div className="grid min-h-28 place-items-center rounded-2xl bg-ink/[0.04] text-center"><div><Eye className="mx-auto text-aqua" /><strong className="block font-display text-xl">Estás observando</strong><span className="text-sm font-bold text-ink/45">Los espectadores no pueden responder.</span></div></div>;
  if (player.solved) return <div className="reveal-pop grid min-h-28 place-items-center rounded-2xl border border-leaf/30 bg-leaf/[0.08] text-center"><div><CheckCircle2 className="mx-auto text-leaf" size={38} /><strong className="block font-display text-2xl text-leaf">¡Has acertado!</strong><span className="font-bold text-ink/50">{ordinal(player.solveOrder!)} en resolverlo · +{player.roundPoints} pts</span><small className="block font-bold text-ink/35">Esperando al resto…</small></div></div>;
  return <section aria-label="Tu respuesta"><div className="mb-2 flex items-end justify-between gap-2"><div><span className="label !mb-0 text-aqua">Tu respuesta</span><h2 className="flex items-center gap-2 font-display text-xl"><Search size={19} /> Buscar Pokémon</h2></div><small className="font-bold text-ink/35">{player.attemptCount} intento{player.attemptCount === 1 ? '' : 's'}</small></div>{player.lastAttempt?.result === 'INCORRECT' && <p className="mb-2 flex flex-wrap items-center justify-between gap-2 rounded-xl bg-berry/[0.08] px-3 py-2 text-sm font-extrabold text-berry" role="status"><span className="flex items-center gap-1.5"><XCircle size={17} /> No es una respuesta válida</span><span>{cooldownMs > 0 ? `Nuevo intento en ${(cooldownMs / 1_000).toFixed(1)}s` : 'Ya puedes volver a intentarlo'}</span></p>}{(loadError || actionError) && <p className="mb-2 rounded-xl bg-berry/10 p-3 text-sm font-extrabold text-berry" role="alert">{actionError || loadError}</p>}{!loadError && <PokemonSelector key={game.roundNumber} pokemon={pokemon} locked={EMPTY_LOCKED} disabled={!player.canGuess} confirmationDisabled={cooldownMs > 0} variant="embedded" autoFocus={false} inputLabel={`Buscar respuesta para la ronda ${game.roundNumber}`} onSelect={onGuess} />}</section>;
}

function PlayersPanel({ room, game }: { room: RoomView; game: GuessFromStatsPublicState }) {
  const solved = new Map(game.solvedPlayers.map((entry) => [entry.playerId, entry.solveOrder])); return <section className="rounded-3xl border border-ink/10 bg-surface/80 p-4"><h2 className="mb-3 font-display text-xl">Jugadores</h2><div className="space-y-2">{room.members.map((member) => { const order = solved.get(member.id); return <div key={member.id} className={`flex items-center gap-2.5 rounded-xl px-2.5 py-2 ${order ? 'bg-leaf/[0.08]' : 'bg-ink/[0.035]'}`}><Avatar name={member.displayName} avatar={member.avatar} presence={member.presence} size="sm" /><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{member.displayName}</strong><small className="font-bold text-ink/35">{game.scores[member.id] ?? 0} pts</small></div>{member.role === 'SPECTATOR' ? <span className="flex items-center gap-1 text-xs font-bold text-ink/35"><Eye size={15} /> Espectador</span> : order ? <span className="text-xs font-black text-leaf">✓ {ordinal(order)} en acertar</span> : <span className="text-xs font-bold text-ink/40">buscando…</span>}</div>; })}</div></section>;
}

function AttemptsPanel({ room, game }: { room: RoomView; game: GuessFromStatsPublicState }) {
  return <section className="rounded-3xl border border-ink/10 bg-surface/80 p-4"><h2 className="mb-3 flex items-center gap-2 font-display text-xl"><History className="text-berry" size={20} /> Intentos recientes</h2>{game.attempts.length ? <div className="max-h-72 space-y-1.5 overflow-y-auto overscroll-contain pr-1" aria-live="polite">{game.attempts.slice().reverse().map((attempt, index) => { const member = room.members.find((candidate) => candidate.id === attempt.playerId); return <div key={`${attempt.playerId}-${attempt.attemptedAt}-${index}`} className="flex items-center gap-2 rounded-xl bg-berry/[0.07] p-2"><Avatar name={member?.displayName ?? attempt.playerId} avatar={member?.avatar} size="xs" /><span className="min-w-0 flex-1 text-sm"><strong>{member?.displayName ?? attempt.playerId}</strong><span className="text-ink/40"> probó </span><strong>{attempt.guessedPokemon.name}</strong></span><img src={attempt.guessedPokemon.sprite} alt="" className="h-8 w-8 object-contain [image-rendering:pixelated]" /><XCircle className="shrink-0 text-berry" size={16} /></div>; })}</div> : <p className="rounded-xl border border-dashed border-ink/10 p-5 text-center text-sm font-bold text-ink/40">Todavía no hay intentos incorrectos.</p>}</section>;
}

function FullPokemonStats({ pokemon }: { pokemon: GuessFromStatsPokemonReveal }) { return <StatsGrid compact stats={[{ key: 'hp', value: pokemon.hp }, { key: 'attack', value: pokemon.attack }, { key: 'defense', value: pokemon.defense }, { key: 'specialAttack', value: pokemon.specialAttack }, { key: 'specialDefense', value: pokemon.specialDefense }, { key: 'speed', value: pokemon.speed }, { key: 'bst', value: pokemon.bst }]} />; }

function RoundReveal({ room, game, serverOffset }: { room: RoomView; game: GuessFromStatsPublicState; serverOffset: number }) {
  const result = game.lastRound!; const multiple = result.answers.length > 1; const ordered = room.members.filter((member) => member.role !== 'SPECTATOR').sort((a, b) => (result.solves[a.id]?.solveOrder ?? 999) - (result.solves[b.id]?.solveOrder ?? 999));
  return <section className="mx-auto max-w-7xl px-3 py-5 sm:px-5"><div className="overflow-hidden rounded-[2rem] border border-leaf/25 bg-surface/95 shadow-card reveal-pop"><header className="flex items-start justify-between gap-3 border-b border-ink/10 px-4 py-4 sm:px-6"><div><span className="label !mb-0">Reveal · Ronda {game.roundNumber}</span><h1 className="font-display text-3xl text-leaf sm:text-4xl">{multiple ? `¡Había ${result.answers.length} respuestas válidas!` : `¡Era ${result.answers[0]?.name}!`}</h1>{multiple && <p className="text-sm font-bold text-ink/45">Todas coinciden exactamente con las pistas mostradas.</p>}</div><ServerTimer deadline={game.nextTransitionAt} serverOffset={serverOffset} label="Siguiente ronda" /></header><div className="space-y-5 p-4 sm:p-6"><HintPanel hints={result.hints} /><div className="grid max-h-[38rem] gap-3 overflow-y-auto sm:grid-cols-2 lg:grid-cols-3">{result.answers.map((answer) => <article key={answer.id} className="rounded-3xl border border-leaf/20 bg-leaf/[0.055] p-3"><div className="mb-2 flex items-center gap-3"><img src={answer.sprite} alt={answer.name} className="h-24 w-24 object-contain [image-rendering:pixelated]" /><div><strong className="block font-display text-xl">{answer.name}</strong><div className="flex flex-wrap gap-1">{answer.types.map((type) => <PokemonTypeBadge key={type} type={type} compact />)}</div></div></div><FullPokemonStats pokemon={answer} /></article>)}</div><div className="grid gap-2 sm:grid-cols-2">{ordered.map((member) => { const solve = result.solves[member.id]; const attempts = result.attemptCounts[member.id] ?? 0; return <article key={member.id} className={`flex items-center gap-3 rounded-2xl border p-3 ${solve ? 'border-leaf/30 bg-leaf/[0.07]' : 'border-berry/20 bg-berry/[0.05]'}`}><strong className="w-8 text-center font-display text-xl">{solve ? solve.solveOrder <= 3 ? ['🥇', '🥈', '🥉'][solve.solveOrder - 1] : solve.solveOrder : '—'}</strong><Avatar name={member.displayName} avatar={member.avatar} size="sm" /><div className="min-w-0 flex-1"><strong className="block truncate">{member.displayName}</strong>{solve ? <><small className="block truncate font-bold text-leaf">Eligió {solve.submittedPokemon.name}</small><small className="font-bold text-ink/40">{attempts} intentos · {(solve.elapsedMs / 1_000).toFixed(1)}s</small></> : <small className="font-bold text-berry">No acertó · {attempts} intentos</small>}</div><strong className={solve ? 'text-leaf' : 'text-ink/30'}>+{solve?.points ?? 0}</strong></article>; })}</div></div></div></section>;
}

export function GuessFromStatsGame({ room, selfId, onAction }: { room: RoomView; selfId: string; onAction(action: unknown): Promise<void> }) {
  const game = room.game as GuessFromStatsPublicState; const player = room.gamePlayerState as GuessFromStatsPlayerState; const config = room.selectedGameConfig as { generations: number[] }; const generationKey = config.generations.join(',');
  const [pokemon, setPokemon] = useState<Pokemon[]>([]); const [loadError, setLoadError] = useState(''); const [actionError, setActionError] = useState(''); const serverOffset = useMemo(() => room.serverNow - Date.now(), [room.serverNow]); const participating = room.members.find((member) => member.id === selfId)?.role === 'PLAYER';
  useEffect(() => { let active = true; setLoadError(''); void api<{ pokemon: Pokemon[] }>(`/pokemon?generations=${generationKey}&includeForms=true`).then((body) => { if (active) setPokemon(body.pokemon); }).catch((error) => { if (active) setLoadError(error instanceof Error ? error.message : 'No se pudo cargar el buscador.'); }); return () => { active = false; }; }, [generationKey]);
  async function guess(pokemonId: string) { setActionError(''); try { await onAction({ type: 'GUESS_POKEMON', pokemonId }); } catch (error) { setActionError(error instanceof Error ? error.message : 'No se pudo enviar el intento.'); } }
  if (game.phase === 'ROUND_RESULTS' && game.lastRound) return <RoundReveal room={room} game={game} serverOffset={serverOffset} />;
  return <section className="mx-auto max-w-[90rem] overflow-x-clip px-3 py-4 sm:px-5"><header className="mb-4 flex items-center justify-between gap-3 rounded-3xl border border-ink/10 bg-surface/85 px-4 py-3 shadow-card"><div><span className="block text-[10px] font-black uppercase tracking-[.16em] text-ink/40">Ronda {game.roundNumber} / {game.totalRounds}</span><h1 className="font-display text-xl sm:text-3xl">Guess from Stats</h1></div><ServerTimer deadline={game.roundEndsAt} serverOffset={serverOffset} /></header><div className="grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_22rem]"><main className="space-y-4"><section className="rounded-[2rem] border border-aqua/20 bg-[linear-gradient(145deg,rgba(29,201,224,.08),rgba(255,255,255,.02))] p-4 shadow-card sm:p-6"><div className="mb-4 text-center"><BarChart3 className="mx-auto text-aqua" size={34} /><span className="label !mb-0 text-aqua">Base Stats</span><h2 className="font-display text-2xl sm:text-3xl">¿Qué Pokémon es?</h2></div><StatsGrid stats={game.visibleStats} /></section><HintPanel hints={game.hints} /><div className="rounded-[2rem] border border-ink/10 bg-surface/90 p-4 shadow-card sm:p-5"><GuessPanel pokemon={pokemon} player={player} game={game} serverOffset={serverOffset} participating={Boolean(participating)} loadError={loadError} actionError={actionError} onGuess={guess} /></div></main><aside className="grid gap-4 md:grid-cols-2 xl:sticky xl:top-4 xl:grid-cols-1"><PlayersPanel room={room} game={game} /><AttemptsPanel room={room} game={game} /></aside></div></section>;
}
