import type { HigherLowerCategory, HigherLowerChoice, HigherLowerPlayerState, HigherLowerPublicState, RoomView } from '@pokemon-universe/shared';
import { ArrowDown, ArrowUp, Check, Clock3, Equal, Flame, Trophy } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
const categoryLabels: Record<HigherLowerCategory, string> = { DEX_NUMBER: 'N.º Pokédex', HP: 'HP', ATTACK: 'Ataque', DEFENSE: 'Defensa', SPECIAL_ATTACK: 'Ataque Especial', SPECIAL_DEFENSE: 'Defensa Especial', SPEED: 'Velocidad', BASE_STAT_TOTAL: 'Total de stats' };
const choices: Array<{ id: HigherLowerChoice; label: string; icon: typeof ArrowUp; tone: string }> = [{ id: 'HIGHER', label: 'HIGHER', icon: ArrowUp, tone: 'border-leaf hover:bg-leaf/15' }, { id: 'SAME', label: 'SAME', icon: Equal, tone: 'border-electric hover:bg-electric/15' }, { id: 'LOWER', label: 'LOWER', icon: ArrowDown, tone: 'border-berry hover:bg-berry/15' }];
function useRemaining(deadline: number | null, offset: number) { const [now, setNow] = useState(Date.now()); useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 100); return () => clearInterval(timer); }, []); return deadline ? Math.max(0, deadline - now - offset) : 0; }
export function HigherLowerGame({ room, onAction }: { room: RoomView; selfId: string; onAction(action: unknown): Promise<void> }) {
  const game = room.game as HigherLowerPublicState; const player = room.gamePlayerState as HigherLowerPlayerState; const [pending, setPending] = useState(false); const [error, setError] = useState(''); const offset = useMemo(() => room.serverNow - Date.now(), [room.serverNow]); const remaining = Math.ceil(useRemaining(game.roundEndsAt ?? game.nextTransitionAt, offset) / 1000); const reveal = game.phase === 'ROUND_RESULTS';
  const members = useMemo(() => new Map(room.members.map((member) => [member.id, member])), [room.members]);
  async function answer(choice: HigherLowerChoice) { setPending(true); setError(''); try { await onAction({ type: 'ANSWER', choice }); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Respuesta rechazada'); } finally { setPending(false); } }
  return <section className="mx-auto max-w-7xl px-4 py-6"><header className="mb-5 flex items-end justify-between"><div><span className="label">Ronda {game.roundNumber} de {game.totalRounds}</span><h1 className="font-display text-3xl">{categoryLabels[game.category]}</h1></div><span className="chip text-lg"><Clock3 size={18} /> {remaining}s</span></header>
    {reveal && <div className="reveal-pop mb-5 rounded-2xl border-2 border-electric bg-electric/15 p-4 text-center"><strong className="font-display text-2xl">Respuesta: {game.lastRound?.correctAnswer}</strong><p className="font-bold text-ink/55">Siguiente ronda en {Math.max(1, remaining)}s…</p></div>}
    <div className="grid gap-5 lg:grid-cols-[1fr_280px]"><div><div className="grid gap-4 sm:grid-cols-2"><article className="card text-center"><span className="label">Pokémon anterior</span><img className="mx-auto h-44 w-44 object-contain" src={game.previousPokemon.sprite} alt="" /><h2 className="font-display text-2xl">{game.previousPokemon.name}</h2><strong className="text-xl text-aqua">{categoryLabels[game.category]}: {game.previousPokemon.value ?? '???'}</strong></article><article className="card text-center"><span className="label">¿Su valor es…?</span><img className="mx-auto h-44 w-44 object-contain" src={game.currentPokemon.sprite} alt="" /><h2 className="font-display text-2xl">{game.currentPokemon.name}</h2><strong className="text-xl text-berry">{categoryLabels[game.category]}: {game.currentPokemon.value ?? '???'}</strong></article></div>
      {game.phase === 'ROUND_ACTIVE' && player.canAnswer && <div className="mt-4 grid gap-3 sm:grid-cols-3">{choices.map(({ id, label, icon: Icon, tone }) => <button key={id} disabled={pending} onClick={() => void answer(id)} className={`flex items-center justify-center gap-2 rounded-2xl border-2 bg-surface p-4 font-display text-xl transition ${tone}`}><Icon />{label}</button>)}</div>}
      {game.phase === 'ROUND_ACTIVE' && player.answer && <p className="mt-4 rounded-2xl bg-leaf/10 p-3 text-center font-extrabold text-leaf"><Check className="mr-2 inline" />Respuesta {player.answer.choice} bloqueada.</p>}
      {error && <p className="mt-3 text-center font-bold text-berry">{error}</p>}
      {reveal && <div className="card mt-4 !p-4"><div className="grid gap-2 sm:grid-cols-2">{game.playerIds.map((id) => { const outcome = game.lastRound?.outcomes[id]; return <div key={id} className={`rounded-xl p-3 ${outcome?.correct ? 'bg-leaf/10' : 'bg-berry/10'}`}><strong>{members.get(id)?.displayName ?? id}</strong><span className="float-right font-extrabold">{outcome?.correct ? `✓ +${outcome.awardedPoints}` : '✗'}</span>{outcome?.correct && <p className="text-sm font-extrabold text-electric"><Flame className="inline" size={15} /> Racha {outcome.streak}{outcome.streakBonus ? ` · BONUS +${outcome.streakBonus}` : ''}</p>}</div>; })}</div></div>}
    </div><aside className="space-y-4"><div className="card !p-4"><h2 className="mb-3 flex gap-2 font-display text-xl"><Trophy className="text-electric" /> Clasificación</h2>{[...game.playerIds].sort((a, b) => game.scores[b]! - game.scores[a]!).map((id) => <div key={id} className="mb-2 rounded-xl bg-ink/[.04] p-2"><div className="flex"><span className="flex-1 font-bold">{members.get(id)?.displayName}</span><strong>{game.scores[id]} pts</strong></div><span className="text-xs font-extrabold text-electric">🔥 Racha {game.streaks[id]}</span></div>)}</div><div className="card !p-4"><h2 className="mb-3 font-display text-xl">Respuestas</h2>{choices.map(({ id }) => <div key={id} className="mb-2 rounded-xl bg-ink/[.04] p-2"><strong>{id}</strong><div className="mt-1 flex flex-wrap gap-1">{Object.entries(game.answers).filter(([, answer]) => answer.choice === id).map(([playerId]) => <span key={playerId} className="chip text-xs">{members.get(playerId)?.displayName}</span>)}</div></div>)}{Object.keys(game.answers).length === 0 && game.answeredIds.length > 0 && <div className="flex flex-wrap gap-1">{game.answeredIds.map((id) => <span key={id} className="chip text-xs">{members.get(id)?.displayName} ✓</span>)}</div>}</div></aside></div>
  </section>;
}
