import type { LearnsetGuessPlayerState, LearnsetGuessPublicState, LearnsetMoveHint, MoveCategory, Pokemon, PokemonType, RoomView } from '@pokemon-universe/shared';
import { BookOpen, CheckCircle2, Clock3, Eye, History, Lightbulb, Sparkles, XCircle } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Avatar } from '../components/Avatar';
import { api } from '../lib/api';
import { PokemonSelector } from './PokemonSelector';

const typeLabels: Record<PokemonType, [string, string]> = {
  normal: ['⚪', 'Normal'], fire: ['🔥', 'Fuego'], water: ['💧', 'Agua'], electric: ['⚡', 'Eléctrico'], grass: ['🌿', 'Planta'], ice: ['❄️', 'Hielo'], fighting: ['🥊', 'Lucha'], poison: ['☠️', 'Veneno'], ground: ['⛰️', 'Tierra'], flying: ['🪽', 'Volador'], psychic: ['🔮', 'Psíquico'], bug: ['🐛', 'Bicho'], rock: ['🪨', 'Roca'], ghost: ['👻', 'Fantasma'], dragon: ['🐉', 'Dragón'], dark: ['🌑', 'Siniestro'], steel: ['⚙️', 'Acero'], fairy: ['🧚', 'Hada'],
};
const categoryLabels: Record<MoveCategory, [string, string]> = { physical: ['⚔️', 'Físico'], special: ['✨', 'Especial'], status: ['◯', 'Estado'] };

function useNow(): number { const [now, setNow] = useState(Date.now()); useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 100); return () => clearInterval(timer); }, []); return now; }

export function LearnsetGuessGame({ room, selfId, onAction }: { room: RoomView; selfId: string; onAction(action: unknown): Promise<void> }) {
  const game = room.game as LearnsetGuessPublicState; const player = room.gamePlayerState as LearnsetGuessPlayerState;
  const generations = (room.selectedGameConfig as { generations: number[] }).generations; const [pokemon, setPokemon] = useState<Pokemon[]>([]);
  const now = useNow(); const offset = useMemo(() => room.serverNow - Date.now(), [room.serverNow]); const serverNow = now + offset;
  const roundRemaining = Math.max(0, Math.ceil(((game.roundEndsAt ?? 0) - serverNow) / 1_000));
  const transitionRemaining = Math.max(0, Math.ceil(((game.nextTransitionAt ?? 0) - serverNow) / 1_000));
  const cooldownRemaining = Math.max(0, (player.cooldownUntil ?? 0) - serverNow); const active = game.phase === 'ROUND_ACTIVE';
  const self = room.members.find((member) => member.id === selfId); const participating = self?.role === 'PLAYER';
  useEffect(() => { void api<{ pokemon: Pokemon[] }>(`/pokemon?generations=${generations.join(',')}`).then((body) => setPokemon(body.pokemon)); }, [generations.join(',')]);

  if (game.phase === 'ROUND_RESULTS' && game.lastRound) return <RoundReveal room={room} game={game} remaining={transitionRemaining} />;
  return <section className="mx-auto max-w-7xl px-4 py-5 md:px-7">
    <header className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><span className="label">Ronda {game.roundNumber} de {game.totalRounds}</span><h1 className="font-display text-3xl font-bold sm:text-4xl"><BookOpen className="mr-2 inline text-aqua" />¿Qué Pokémon es?</h1><p className="mt-1 font-bold text-ink/45">Learnset de Gen {game.referenceGeneration} · {game.referenceSource}</p></div><span className={`chip text-lg ${roundRemaining <= 5 ? 'timer-pulse text-berry' : ''}`}><Clock3 /> {roundRemaining}s</span></header>
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_20rem]">
      <main className="space-y-5">
        {game.evolutionHint && <div className="flex items-center gap-3 rounded-2xl border-2 border-electric/25 bg-electric/10 p-3"><Sparkles className="text-electric" /><div><span className="label !mb-0">Pista evolutiva</span><strong className="font-display text-lg">{game.evolutionHint}</strong></div></div>}
        <section className="card !p-4 md:!p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><div><span className="label !mb-0">Movimientos conocidos</span><h2 className="font-display text-2xl">Pistas reveladas</h2></div>{active && game.nextTransitionAt && <span className="chip bg-aqua/10 text-aqua"><Lightbulb size={16} /> Nueva pista en {transitionRemaining}s</span>}</div>
          {game.visibleGroups.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{game.visibleGroups.map((group, index) => <div key={`${group.level ?? 'hidden'}-${group.stage}-${index}`} className={`rounded-2xl border-2 p-3 ${group.stage > 0 && group.stage === Math.max(...game.visibleGroups.map((entry) => entry.stage)) ? 'reveal-pop border-aqua bg-aqua/10' : 'border-ink/10 bg-surface-raised'}`}><div className="mb-2 flex items-center justify-between"><span className="label !mb-0">{group.level === null ? 'Movimiento' : `Nv. ${group.level}`}</span>{group.stage > 0 && <span className="rounded-full bg-aqua px-2 py-1 text-[10px] font-black uppercase text-night">Nueva pista</span>}</div><div className="space-y-2">{group.moves.map((move) => <MoveHint key={`${move.moveId}-${move.level}`} move={move} />)}</div></div>)}</div> : <div className="rounded-2xl border-2 border-dashed border-ink/10 p-8 text-center"><Lightbulb className="mx-auto text-electric" /><strong className="mt-2 block font-display text-xl">No aprende movimientos hasta nivel 15</strong><p className="font-bold text-ink/40">La primera pista superior aparecerá pronto.</p></div>}
        </section>
        {active && participating && player.canGuess && <div><PokemonSelector pokemon={pokemon} locked={new Set()} disabled={false} confirmationDisabled={cooldownRemaining > 0} onSelect={(pokemonId) => onAction({ type: 'GUESS_POKEMON', pokemonId })} />{cooldownRemaining > 0 && <p className="mt-2 text-center text-sm font-extrabold text-berry">Espera {(cooldownRemaining / 1_000).toFixed(1)}s para confirmar otro intento.</p>}</div>}
        {active && player.solved && <div className="card reveal-pop grid min-h-52 place-items-center border-leaf bg-leaf/10 text-center"><div><CheckCircle2 className="mx-auto text-leaf" size={56} /><h2 className="mt-3 font-display text-3xl text-leaf">¡Has acertado!</h2><p className="font-bold text-ink/50">+{player.roundPoints} puntos · la respuesta sigue oculta para los demás.</p></div></div>}
        {active && (!participating || (!player.canGuess && !player.solved)) && <div className="card grid min-h-44 place-items-center text-center"><div><Eye className="mx-auto text-aqua" size={44} /><h2 className="mt-2 font-display text-2xl">Estás observando</h2></div></div>}
      </main>
      <aside className="space-y-4 xl:sticky xl:top-4"><div className="card !p-4"><h2 className="mb-3 font-display text-xl">Entrenadores</h2><div className="space-y-2">{room.members.map((member) => { const solved = game.solvedPlayerIds.includes(member.id); return <div key={member.id} className={`flex items-center gap-2 rounded-xl p-2 ${solved ? 'bg-leaf/10' : 'bg-ink/[.035]'}`}><Avatar name={member.displayName} avatar={member.avatar} presence={member.presence} size="sm" /><strong className="min-w-0 flex-1 truncate">{member.displayName}</strong>{member.role === 'SPECTATOR' ? <Eye size={16} className="text-ink/35" /> : solved ? <span className="flex items-center gap-1 text-xs font-black text-leaf"><CheckCircle2 size={16} /> Acertó</span> : <span className="text-xs font-bold text-ink/40">buscando…</span>}</div>; })}</div></div>
        <div className="card !p-4"><h2 className="mb-3 flex items-center gap-2 font-display text-xl"><History className="text-berry" /> Intentos públicos</h2>{game.attempts.length ? <div className="max-h-72 space-y-2 overflow-y-auto">{game.attempts.slice().reverse().map((attempt, index) => { const member = room.members.find((entry) => entry.id === attempt.playerId); return <div key={`${attempt.playerId}-${attempt.attemptedAt}-${index}`} className="flex items-center gap-2 rounded-xl bg-berry/10 p-2"><img src={attempt.sprite} alt="" className="h-9 w-9 object-contain [image-rendering:pixelated]" /><div className="min-w-0 flex-1"><small className="block truncate font-bold text-ink/45">{member?.displayName ?? attempt.playerId} probó</small><strong className="block truncate">{attempt.pokemonName}</strong></div><XCircle className="text-berry" size={18} /></div>; })}</div> : <p className="text-sm font-bold text-ink/40">Todavía no hay intentos incorrectos.</p>}</div></aside>
    </div>
  </section>;
}

function MoveHint({ move }: { move: LearnsetMoveHint }) { const type = typeLabels[move.type]; const category = categoryLabels[move.category]; return <div className="rounded-xl bg-night/35 p-3"><strong className="block font-display text-lg">{move.name}</strong><div className="mt-1 flex flex-wrap gap-2 text-xs font-extrabold"><span>{type[0]} {type[1]}</span><span className="text-ink/35">·</span><span>{category[0]} {category[1]}</span></div></div>; }

function RoundReveal({ room, game, remaining }: { room: RoomView; game: LearnsetGuessPublicState; remaining: number }) {
  const result = game.lastRound!; const revealed = new Set(result.revealedMoves.map((move) => `${move.moveId}:${move.level}`)); return <section className="mx-auto max-w-6xl px-4 py-6"><div className="card reveal-pop"><div className="mb-5 flex items-start justify-between gap-3"><div><span className="label">Resultado de la ronda</span><h1 className="font-display text-4xl text-leaf">¡Era {result.pokemon.name}!</h1><p className="font-bold text-ink/45">#{String(result.pokemon.nationalDexNumber).padStart(3, '0')} · Generación {result.pokemon.generation} · Learnset Gen {result.referenceGeneration}</p><p className="text-sm font-bold text-aqua">{result.referenceSource}</p></div><span className="chip"><Clock3 size={16} /> {Math.max(1, remaining)}s</span></div><div className="grid gap-5 lg:grid-cols-[15rem_1fr]"><div className="grid place-items-center rounded-3xl bg-leaf/10 p-4"><img src={result.pokemon.sprite} alt={result.pokemon.name} className="h-44 w-44 object-contain [image-rendering:pixelated]" /></div><div className="grid gap-2 sm:grid-cols-2">{room.members.map((member) => { const solve = result.solves[member.id]; return <div key={member.id} className={`flex items-center gap-3 rounded-2xl border-2 p-3 ${solve ? 'border-leaf bg-leaf/10' : 'border-berry/30 bg-berry/10'}`}><Avatar name={member.displayName} avatar={member.avatar} size="md" /><div className="min-w-0 flex-1"><strong className="block truncate">{member.displayName}</strong>{solve ? <small className="font-bold text-leaf">✓ {solve.revealStage === 0 ? 'Pistas iniciales' : `Después de ${solve.revealStage} reveal${solve.revealStage === 1 ? '' : 's'}`}</small> : <small className="font-bold text-berry">✗ No acertó</small>}</div><strong className={solve ? 'text-leaf' : 'text-ink/30'}>+{solve?.points ?? 0}</strong></div>; })}</div></div><div className="mt-5"><span className="label">Learnset utilizado · {result.revealedMoves.length} pistas llegaron a verse</span><div className="flex max-h-52 flex-wrap gap-2 overflow-y-auto">{result.learnset.map((move) => <span key={`${move.moveId}-${move.level}`} className={`chip ${revealed.has(`${move.moveId}:${move.level}`) ? 'bg-aqua/15 text-aqua' : 'opacity-45'}`}>{move.level !== null && `Nv. ${move.level} · `}{move.name}</span>)}</div></div></div></section>;
}
