import type { OneOfUsIsFakeConfig, OneOfUsIsFakePlayerState, OneOfUsIsFakePublicState, RoomMemberView, RoomView } from '@pokemon-universe/shared';
import { Check, CheckCircle2, Eye, MessageCircle, ShieldAlert, Sparkles, UserRoundSearch, Vote } from 'lucide-react';
import { Avatar } from '../components/Avatar';
import { ServerTimer } from '../components/ServerTimer';
import { usePokemonPool } from '../hooks/usePokemonPool';
import { useServerOffset } from '../hooks/useServerTime';
import { PokemonSelector } from './PokemonSelector';

const EMPTY_LOCKED = new Set<string>();
const stages = ['Categoría', 'Elegir Pokémon', 'Reveal', 'Discusión', 'Votación', 'Resultado'];

function member(room: RoomView, id: string): RoomMemberView | undefined { return room.members.find((candidate) => candidate.id === id); }

function StageRail({ phase }: { phase: string }) {
  const active = phase === 'ROUND_ACTIVE' ? 1 : phase === 'CHOICE_REVEAL' ? 2 : phase === 'DISCUSSION' ? 3 : phase === 'REVOTE' ? 4 : phase === 'ROUND_RESULTS' ? 5 : 0;
  return <ol className="grid grid-cols-3 gap-1.5 sm:grid-cols-6" aria-label="Fases de la ronda">{stages.map((stage, index) => <li key={stage} className={`rounded-lg px-2 py-2 text-center text-[10px] font-black uppercase tracking-wide sm:text-xs ${index === active ? 'bg-aqua text-night' : index < active ? 'bg-leaf/10 text-leaf' : 'bg-ink/[.05] text-ink/45'}`} aria-current={index === active ? 'step' : undefined}><span className="mr-1 hidden sm:inline">{index < active ? '✓' : index + 1}</span>{stage}</li>)}</ol>;
}

function CategoryCard({ player }: { player: Extract<OneOfUsIsFakePlayerState, { role: 'PLAYER' }> }) {
  return <section className={`overflow-hidden rounded-2xl border shadow-card ${player.isFake ? 'border-berry/35 bg-berry/[.06]' : 'border-aqua/25 bg-surface'}`} aria-labelledby="my-category">
    <div className="border-b border-ink/10 px-4 py-3 sm:px-6"><span className="label !mb-0">Solo tú puedes ver esto</span><div className="flex items-center gap-2"><h2 id="my-category" className="font-display text-xl">Tu categoría</h2>{player.isFake && <span className="rounded-full bg-berry px-2.5 py-1 text-xs font-black text-white">FAKE</span>}</div></div>
    <div className="px-4 py-6 text-center sm:px-8"><blockquote className="mx-auto max-w-3xl font-display text-2xl leading-tight sm:text-4xl">“{player.myCategory}”</blockquote>{player.isFake && <p className="mx-auto mt-4 max-w-xl rounded-xl bg-berry/10 px-3 py-2 font-extrabold text-berry"><ShieldAlert className="mr-2 inline" size={18} />Tienes una categoría diferente al resto. No conoces la categoría principal.</p>}</div>
  </section>;
}

function ChoiceGrid({ room, game, selectionMode = false }: { room: RoomView; game: OneOfUsIsFakePublicState; selectionMode?: boolean }) {
  const byPlayer = new Map(game.revealedChoices.map((choice) => [choice.playerId, choice.pokemon]));
  return <div className={selectionMode ? 'grid gap-2' : 'grid gap-2 sm:grid-cols-2 xl:grid-cols-4'}>{game.playerIds.map((id) => { const person = member(room, id); const pokemon = byPlayer.get(id); const completed = game.selectionCompletedIds.includes(id); return <article key={id} className={`min-w-0 rounded-xl border p-3 ${pokemon ? 'border-aqua/25 bg-aqua/[.05] reveal-pop' : 'border-ink/10 bg-surface-raised/70'}`}><div className="flex items-center gap-2"><Avatar name={person?.displayName ?? id} avatar={person?.avatar} presence={person?.presence} size="sm" /><strong className="min-w-0 flex-1 truncate">{person?.displayName ?? id}</strong>{selectionMode && (completed ? <CheckCircle2 className="shrink-0 text-leaf" size={19} /> : <span className="text-xs font-bold text-ink/50">Eligiendo…</span>)}</div>{pokemon && <div className="mt-3 flex items-center gap-3"><img src={pokemon.sprite} alt="" className="h-20 w-20 shrink-0 object-contain" /><strong className="min-w-0 break-words font-display text-xl">{pokemon.name}</strong></div>}{!selectionMode && !pokemon && game.phase !== 'CHOICE_REVEAL' && <p className="mt-3 text-sm font-bold text-ink/50">Sin elección</p>}</article>; })}</div>;
}

function VotePanel({ room, selfId, game, player, onAction }: { room: RoomView; selfId: string; game: OneOfUsIsFakePublicState; player: OneOfUsIsFakePlayerState; onAction(action: unknown): Promise<void> }) {
  const canVote = player.role === 'PLAYER' && player.canVote;
  return <section className="rounded-2xl border border-berry/20 bg-surface p-4 shadow-card sm:p-5" aria-labelledby="vote-heading"><div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><span className="label !mb-0">Papeleta secreta</span><h2 id="vote-heading" className="flex items-center gap-2 font-display text-2xl"><Vote className="text-berry" />{game.phase === 'REVOTE' ? `Revotación ${game.voteRoundNumber}` : '¿Quién es el fake?'}</h2><p className="mt-1 text-sm font-bold text-ink/60">Los votos se revelarán al terminar la ronda. No puedes votarte.</p></div>{player.role === 'PLAYER' && player.ownVotePlayerId && <span className="chip !bg-leaf/10 !text-leaf"><Check size={15} /> Voto enviado</span>}</div><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{game.voteCandidates.map((id) => { const person = member(room, id); const self = id === selfId; return <button type="button" key={id} disabled={!canVote || self} onClick={() => void onAction({ type: 'VOTE_PLAYER', playerId: id })} className={`flex min-h-16 items-center gap-3 rounded-xl border p-3 text-left ${self ? 'border-transparent bg-ink/[.04] opacity-45' : canVote ? 'border-ink/10 bg-surface-raised hover:border-berry/50 hover:bg-berry/[.06]' : 'border-ink/10 bg-surface-raised opacity-65'}`}><Avatar name={person?.displayName ?? id} avatar={person?.avatar} presence={person?.presence} size="sm" /><span className="min-w-0 flex-1"><strong className="block truncate">{person?.displayName ?? id}</strong><small className="font-bold text-ink/55">{self ? 'Eres tú' : game.votedPlayerIds.includes(id) ? 'Ya ha votado' : 'Votar'}</small></span></button>; })}</div></section>;
}

function RoundResult({ room, game, serverOffset }: { room: RoomView; game: OneOfUsIsFakePublicState; serverOffset: number }) {
  const result = game.lastRound!; const fake = member(room, result.fakePlayerId);
  return <section className="mx-auto max-w-6xl overflow-x-clip px-3 py-5 sm:px-5"><div className={`overflow-hidden rounded-2xl border bg-surface shadow-card ${result.winner === 'NORMALS' ? 'border-leaf/35' : 'border-berry/35'}`}><header className="flex flex-wrap items-start justify-between gap-3 border-b border-ink/10 p-4 sm:p-6"><div><span className="label !mb-0">Ronda {game.roundNumber} · Resultado</span><h1 className={`font-display text-3xl sm:text-5xl ${result.winner === 'NORMALS' ? 'text-leaf' : 'text-berry'}`}>{result.winner === 'NORMALS' ? 'Ganan los normales' : 'Gana el fake'}</h1></div><ServerTimer deadline={game.nextTransitionAt} serverOffset={serverOffset} label="Siguiente ronda" /></header><div className="grid gap-5 p-4 sm:p-6 lg:grid-cols-[18rem_minmax(0,1fr)]"><aside className="rounded-2xl bg-berry/[.07] p-5 text-center"><span className="label">El fake era</span>{fake && <Avatar name={fake.displayName} avatar={fake.avatar} size="xl" />}<h2 className="mt-3 break-words font-display text-3xl">{fake?.displayName ?? result.fakePlayerId}</h2><p className="mt-3 text-sm font-extrabold text-berry">{result.selectedPlayerId === result.fakePlayerId ? 'Descubierto por el grupo' : 'Engañó al grupo'}</p></aside><main className="min-w-0"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-aqua/[.07] p-4"><span className="label !mb-1">Categoría principal</span><strong className="block font-display text-xl leading-tight">{result.mainCategory}</strong></div><div className="rounded-xl bg-berry/[.07] p-4"><span className="label !mb-1">Categoría del fake</span><strong className="block font-display text-xl leading-tight">{result.fakeCategory}</strong></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{result.players.map((entry) => { const person = member(room, entry.playerId); return <article key={entry.playerId} className={`rounded-xl border p-3 ${entry.isFake ? 'border-berry/35 bg-berry/[.05]' : 'border-ink/10 bg-surface-raised'}`}><div className="flex items-center gap-2"><Avatar name={person?.displayName ?? entry.playerId} avatar={person?.avatar} size="sm" /><strong className="min-w-0 flex-1 truncate">{person?.displayName ?? entry.playerId}</strong>{entry.isFake && <span className="text-xs font-black text-berry">FAKE</span>}<span className="font-extrabold text-leaf">+{result.pointsAwarded[entry.playerId] ?? 0}</span></div><p className="mt-2 text-xs font-bold leading-snug text-ink/60">{entry.category}</p>{entry.pokemon ? <div className="mt-2 flex items-center gap-2"><img src={entry.pokemon.sprite} alt="" className="h-14 w-14 object-contain" /><strong>{entry.pokemon.name}</strong></div> : <p className="mt-2 text-sm font-bold text-ink/45">Sin elección</p>}</article>; })}</div></main></div></div></section>;
}

export function OneOfUsIsFakeGame({ room, selfId, onAction }: { room: RoomView; selfId: string; onAction(action: unknown): Promise<void> }) {
  const game = room.game as OneOfUsIsFakePublicState;
  const player = room.gamePlayerState as OneOfUsIsFakePlayerState;
  const config = room.selectedGameConfig as OneOfUsIsFakeConfig;
  const { pokemon, error: poolError } = usePokemonPool({ generations: config.generations, includeForms: config.includeRegionalForms, enabled: player.role === 'PLAYER' && player.canSelect });
  const serverOffset = useServerOffset(room.serverNow);
  if (game.phase === 'ROUND_RESULTS' && game.lastRound) return <RoundResult room={room} game={game} serverOffset={serverOffset} />;
  const choosing = game.phase === 'ROUND_ACTIVE'; const revealing = game.phase === 'CHOICE_REVEAL'; const discussing = game.phase === 'DISCUSSION' || game.phase === 'REVOTE';
  return <section className="mx-auto max-w-[90rem] overflow-x-clip px-3 py-4 sm:px-5"><header className="rounded-2xl border border-ink/10 bg-surface p-4 shadow-card"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="label !mb-0">Ronda {game.roundNumber} de {game.totalRounds}</span><h1 className="font-display text-2xl sm:text-4xl">One of Us Is Fake</h1></div><ServerTimer deadline={game.roundEndsAt ?? game.nextTransitionAt} serverOffset={serverOffset} label={choosing ? 'Para elegir' : revealing ? 'Siguiente reveal' : discussing ? game.phase === 'REVOTE' ? 'Revotación' : 'Discusión' : 'Tiempo'} /></div><div className="mt-4"><StageRail phase={game.phase} /></div></header>
    <main className="mt-4 space-y-4">{player.role === 'PLAYER' ? <CategoryCard player={player} /> : <section className="rounded-2xl border border-ink/10 bg-surface p-6 text-center shadow-card"><Eye className="mx-auto text-aqua" size={38} /><h2 className="mt-2 font-display text-2xl">Estás observando</h2><p className="font-bold text-ink/60">Puedes seguir elecciones, discusión y resultado, pero no participar.</p></section>}
      {choosing && <div className="grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_22rem]"><section className="min-w-0 rounded-2xl border border-ink/10 bg-surface p-4 shadow-card sm:p-5"><div className="mb-3"><span className="label !mb-0">Tu decisión</span><h2 className="font-display text-2xl">Elige cualquier Pokémon</h2><p className="mt-1 font-bold text-ink/60">No hay respuesta correcta. Escoge uno que puedas justificar después.</p></div>{player.role === 'PLAYER' && player.ownChoice && <div className="mb-3 flex items-center gap-3 rounded-xl bg-leaf/[.07] p-3"><img src={player.ownChoice.sprite} alt="" className="h-16 w-16 object-contain" /><span className="min-w-0 flex-1"><small className="block font-black text-leaf">ELECCIÓN GUARDADA</small><strong className="block truncate font-display text-xl">{player.ownChoice.name}</strong></span><CheckCircle2 className="text-leaf" /></div>}{player.role === 'PLAYER' ? poolError ? <p className="status-error">{poolError}</p> : <PokemonSelector key={game.roundNumber} pokemon={pokemon} locked={EMPTY_LOCKED} disabled={!player.canSelect} variant="embedded" autoFocus={false} inputLabel="Buscar Pokémon para tu categoría" onSelect={(pokemonId) => onAction({ type: 'SELECT_POKEMON', pokemonId })} /> : null}</section><aside className="rounded-2xl border border-ink/10 bg-surface p-4 shadow-card"><h2 className="mb-3 font-display text-xl">Estado del grupo</h2><ChoiceGrid room={room} game={game} selectionMode /></aside></div>}
      {revealing && <section className="rounded-2xl border border-ink/10 bg-surface p-4 shadow-card sm:p-6"><div className="mb-5 text-center"><Sparkles className="mx-auto text-electric" size={36} /><span className="label mt-2 !mb-0">Reveal aleatorio</span><h2 className="font-display text-3xl">Estas son las elecciones</h2><p className="font-bold text-ink/60">Se muestran una a una. Las categorías siguen siendo secretas.</p></div><ChoiceGrid room={room} game={game} /></section>}
      {discussing && <><section className="rounded-2xl border border-aqua/20 bg-surface p-4 shadow-card sm:p-6"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><span className="label !mb-0">Voz externa · conversación libre</span><h2 className="flex items-center gap-2 font-display text-2xl sm:text-3xl"><MessageCircle className="text-aqua" /> Defended vuestra elección</h2><p className="mt-1 font-bold text-ink/60">Explicad, mentid, acusad y escuchad. No hay turnos de palabra.</p></div><span className="chip"><UserRoundSearch size={16} /> {game.votedPlayerIds.length}/{game.playerIds.length} votos</span></div><ChoiceGrid room={room} game={game} /></section><VotePanel room={room} selfId={selfId} game={game} player={player} onAction={onAction} /></>}
    </main></section>;
}
