import type { PokemonTriviaOption, PokemonTriviaPlayerState, PokemonTriviaPublicState, RoomView } from '@pokemon-universe/shared';
import { Brain, CheckCircle2, Eye, XCircle } from 'lucide-react';
import { useState } from 'react';
import { Avatar } from '../components/Avatar';
import { ServerTimer } from '../components/ServerTimer';
import { useServerOffset } from '../hooks/useServerTime';

function OptionButton({ option, selected, correct, reveal, disabled, onClick }: { option: PokemonTriviaOption; selected: boolean; correct: boolean; reveal: boolean; disabled: boolean; onClick(): void }) {
  const tone = reveal ? correct ? 'border-leaf bg-leaf/[.12]' : selected ? 'border-berry bg-berry/[.08] opacity-70' : 'border-ink/10 bg-surface-raised opacity-60' : selected ? 'border-aqua bg-aqua/[.1]' : 'border-ink/10 bg-surface-raised hover:border-aqua/70 hover:bg-aqua/[.05]';
  return <button type="button" disabled={disabled} aria-pressed={selected} onClick={onClick} className={`group relative flex min-h-44 items-center gap-3 rounded-xl border p-3 text-left transition-[border-color,background-color,opacity,transform] ${tone} ${disabled ? 'cursor-default' : 'hover:-translate-y-0.5'}`}><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-lg font-display text-xl ${correct && reveal ? 'bg-leaf text-night' : selected ? 'bg-aqua text-night' : 'bg-ink/[.07]'}`}>{option.id}</span><img src={option.pokemon.sprite} alt="" className="h-28 w-28 shrink-0 object-contain [image-rendering:pixelated] sm:h-32 sm:w-32" /><strong className="min-w-0 break-words font-display text-lg sm:text-xl">{option.pokemon.name}</strong>{reveal && correct && <CheckCircle2 className="absolute right-3 top-3 text-leaf" aria-label="Respuesta correcta" />}{reveal && selected && !correct && <XCircle className="absolute right-3 top-3 text-berry" aria-label="Respuesta incorrecta" />}</button>;
}

function Players({ room, game }: { room: RoomView; game: PokemonTriviaPublicState }) {
  return <aside className="rounded-xl border border-ink/10 bg-surface p-3"><h2 className="mb-2 font-display text-lg">Marcador</h2><div className="space-y-1.5">{room.members.filter((member) => member.role === 'PLAYER').map((member) => <div key={member.id} className="flex items-center gap-2 rounded-lg bg-ink/[.035] p-2"><Avatar name={member.displayName} avatar={member.avatar} presence={member.presence} size="xs" /><strong className="min-w-0 flex-1 truncate text-sm">{member.displayName}</strong>{game.answeredPlayerIds.includes(member.id) && <CheckCircle2 className="text-leaf" size={16} aria-label="Ha respondido" />}<span className="text-xs font-extrabold text-berry">{game.scores[member.id] ?? 0}</span></div>)}</div></aside>;
}

function Reveal({ room, game, offset }: { room: RoomView; game: PokemonTriviaPublicState; offset: number }) {
  const result = game.lastRound!;
  return <section className="mx-auto max-w-6xl px-3 py-4 sm:px-5"><header className="mb-4 flex items-start justify-between gap-3"><div><p className="font-extrabold text-leaf">Ronda resuelta</p><h1 className="max-w-3xl text-pretty font-display text-2xl sm:text-4xl">{game.prompt}</h1></div><ServerTimer deadline={game.nextTransitionAt} serverOffset={offset} label="Siguiente pregunta" /></header><div className="grid items-start gap-4 lg:grid-cols-[minmax(0,1fr)_20rem]"><main><div className="grid gap-3 sm:grid-cols-2">{game.options.map((option) => <OptionButton key={option.id} option={option} selected={false} correct={option.id === result.correctOptionId} reveal disabled onClick={() => undefined} />)}</div><p className="mt-4 rounded-xl bg-leaf/[.1] p-4 text-center font-extrabold text-leaf">{result.fact}</p></main><aside className="rounded-xl border border-ink/10 bg-surface p-3"><h2 className="mb-3 font-display text-lg">Respuestas</h2><div className="space-y-2">{room.members.filter((member) => member.role === 'PLAYER').map((member) => { const answer = result.answers[member.id]; const correct = answer?.optionId === result.correctOptionId; return <div key={member.id} className="flex items-center gap-2 rounded-lg bg-ink/[.035] p-2"><Avatar name={member.displayName} avatar={member.avatar} size="xs" /><strong className="min-w-0 flex-1 truncate text-sm">{member.displayName}</strong><span className="font-extrabold">{answer?.optionId ?? '—'}</span><strong className={correct ? 'text-leaf' : 'text-berry'}>{correct ? `+${result.points[member.id] ?? 0}` : '✕'}</strong></div>; })}</div></aside></div></section>;
}

export function PokemonTriviaGame({ room, onAction }: { room: RoomView; selfId: string; onAction(action: unknown): Promise<void> }) {
  const game = room.game as PokemonTriviaPublicState; const player = room.gamePlayerState as PokemonTriviaPlayerState; const offset = useServerOffset(room.serverNow); const [sending, setSending] = useState(false); const [error, setError] = useState('');
  if (game.phase === 'ROUND_RESULTS' && game.lastRound) return <Reveal room={room} game={game} offset={offset} />;
  const submit = async (optionId: PokemonTriviaOption['id']) => { if (!player.canAnswer || sending) return; setSending(true); setError(''); try { await onAction({ type: 'ANSWER', optionId }); } catch (caught) { setError(caught instanceof Error ? caught.message : 'No se pudo enviar la respuesta.'); } finally { setSending(false); } };
  return <section className="mx-auto max-w-7xl overflow-x-clip px-3 py-4 sm:px-5"><header className="mb-4 flex items-center justify-between gap-3"><div><p className="text-xs font-extrabold text-ink/60">Pregunta {game.roundNumber} / {game.totalRounds}</p><h1 className="font-display text-2xl sm:text-3xl">Pokémon Trivia</h1></div><ServerTimer deadline={game.roundEndsAt} serverOffset={offset} /></header><div className="grid items-start gap-4 lg:grid-cols-[minmax(0,1fr)_18rem]"><main><div className="mb-4 flex min-h-28 items-center gap-4 rounded-xl bg-night px-4 py-5 text-white sm:px-6"><Brain className="shrink-0 text-electric" size={38} /><h2 className="text-pretty font-display text-2xl leading-tight sm:text-3xl">{game.prompt}</h2></div><div className="grid gap-3 sm:grid-cols-2">{game.options.map((option) => <OptionButton key={option.id} option={option} selected={player.answer?.optionId === option.id} correct={false} reveal={false} disabled={!player.canAnswer || sending} onClick={() => void submit(option.id)} />)}</div>{player.answer && <p className="mt-3 rounded-xl bg-aqua/[.1] p-3 text-center font-extrabold text-aqua"><CheckCircle2 className="mr-2 inline" size={19} />Respuesta {player.answer.optionId} bloqueada por el servidor.</p>}{player.role === 'SPECTATOR' && <p className="mt-3 rounded-xl bg-ink/[.05] p-3 text-center font-bold"><Eye className="mr-2 inline" size={19} />Estás observando la ronda.</p>}{error && <p role="alert" className="mt-3 rounded-xl bg-berry/[.1] p-3 text-center font-bold text-berry">{error}</p>}</main><Players room={room} game={game} /></div></section>;
}
