import { describeBingoCondition, type BingoPublicBoard, type PokemonBingoPlayerState, type PokemonBingoPublicState, type RoomView } from '@pokemon-universe/shared';
import { Clock3, Eye, Search, Trash2, Trophy } from 'lucide-react';
import { useEffect, useState } from 'react';
import { usePokemonPool } from '../hooks/usePokemonPool';
import { useRemainingMs, useServerOffset } from '../hooks/useServerTime';
import { PokemonSelector } from './PokemonSelector';

export function PokemonBingoBoard({ board, width, selectedCellId, interactive = false, onSelect }: { board: BingoPublicBoard; width: number; selectedCellId?: string | null; interactive?: boolean; onSelect?(cellId: string): void }) {
  return <div className="max-w-full overflow-x-auto overscroll-x-contain rounded-2xl border border-ink/10 bg-night/25 p-2"><div className="grid w-max min-w-full gap-2" style={{ gridTemplateColumns: `repeat(${width}, minmax(9rem, 1fr))` }}>{board.cells.map((cell) => { const selected = cell.id === selectedCellId; return <button type="button" key={cell.id} disabled={!interactive} onClick={() => onSelect?.(cell.id)} className={`relative flex min-h-40 flex-col rounded-2xl border p-3 text-left transition ${selected ? 'border-electric bg-electric/10 shadow-[0_0_0_3px_rgba(240,191,84,.16)]' : cell.assignment ? 'border-leaf/45 bg-leaf/10' : 'border-ink/10 bg-surface-raised'} ${interactive ? 'hover:border-aqua' : 'cursor-default'}`}><span className="mb-2 block text-xs font-black uppercase leading-snug tracking-wide">{cell.conditions.map(describeBingoCondition).map((label, index) => <span key={label} className="block">{index > 0 && <small className="text-electric">＋ </small>}{label}</span>)}</span>{cell.assignment ? <span className="mt-auto flex items-center gap-2"><img src={cell.assignment.sprite} alt="" className="h-16 w-16 object-contain [image-rendering:pixelated]" /><span className="min-w-0"><strong className="block truncate">{cell.assignment.name}</strong><small className="font-extrabold text-leaf">✓ Completa</small></span></span> : <span className="mt-auto grid min-h-16 place-items-center rounded-xl border border-dashed border-ink/10 font-bold text-ink/55">Vacía</span>}{cell.possibleSolutions.length > 0 && <span className="mt-2 block border-t border-ink/10 pt-2"><small className="font-extrabold text-ink/65">Podías usar:</small>{cell.possibleSolutions.map((pokemon) => <span key={pokemon.id} className="mt-1 flex items-center gap-1.5 text-xs font-bold"><img src={pokemon.sprite} alt="" className="h-7 w-7 object-contain" />{pokemon.name}</span>)}</span>}</button>; })}</div></div>;
}

export function PokemonBingoGame({ room, selfId, onAction }: { room: RoomView; selfId: string; onAction(action: unknown): Promise<void> }) {
  const game = room.game as PokemonBingoPublicState; const playerState = room.gamePlayerState as PokemonBingoPlayerState; const config = room.selectedGameConfig as { generations: number[]; durationSeconds: number };
  const { pokemon } = usePokemonPool({ generations: config.generations }); const [selectedCellId, setSelectedCellId] = useState<string | null>(null); const [selectedRival, setSelectedRival] = useState<string | null>(null); const [actionError, setActionError] = useState('');
  const serverOffset = useServerOffset(room.serverNow); const deadline = game.roundEndsAt ?? game.nextTransitionAt; const remainingMs = useRemainingMs(deadline, serverOffset); const remaining = Math.ceil(remainingMs / 1000);
  const own = game.boards[selfId]; useEffect(() => { if (!selectedCellId && own?.cells[0]) setSelectedCellId(own.cells[0].id); }, [own, selectedCellId]);
  const selectedCell = own?.cells.find((cell) => cell.id === selectedCellId); const rivals = Object.keys(game.boards).filter((id) => id !== selfId); const rivalId = selectedRival && game.boards[selectedRival] ? selectedRival : rivals[0] ?? null; const rival = rivalId ? game.boards[rivalId] : null;
  const name = (id: string) => room.members.find((member) => member.id === id)?.displayName ?? id; const cooldownMs = useRemainingMs(playerState.cooldownUntil, serverOffset);
  async function assign(pokemonId: string) {
    if (!selectedCell || !own) return; setActionError(''); const source = own.cells.find((cell) => cell.assignment?.id === pokemonId && cell.id !== selectedCell.id);
    const moveExisting = Boolean(source); if (source && !window.confirm(`${source.assignment?.name} ya está usado en “${source.conditions.map(describeBingoCondition).join(' + ')}”.\n\n¿Moverlo a “${selectedCell.conditions.map(describeBingoCondition).join(' + ')}”?`)) return;
    try { await onAction({ type: 'ASSIGN_POKEMON', cellId: selectedCell.id, pokemonId, moveExisting }); } catch (error) { setActionError(error instanceof Error ? error.message : 'No se pudo asignar.'); }
  }
  async function remove() { if (!selectedCell?.assignment) return; setActionError(''); try { await onAction({ type: 'REMOVE_POKEMON', cellId: selectedCell.id }); } catch (error) { setActionError(error instanceof Error ? error.message : 'No se pudo quitar.'); } }
  return <section className="mx-auto max-w-[96rem] px-3 py-4 sm:px-5 md:py-6">
    <header className="mb-4 grid gap-3 rounded-2xl border border-ink/10 bg-surface/90 p-4 sm:grid-cols-[1fr_auto_1fr] sm:items-center"><div><span className="label !mb-0">Tu progreso</span><strong className="font-display text-3xl">{own?.completed ?? 0}/{own?.total ?? 0}</strong></div><div className="text-center"><span className="label !mb-0">Pokémon Bingo</span><strong className={`font-display text-3xl ${remaining <= 10 && game.phase === 'ROUND_ACTIVE' ? 'timer-pulse text-berry' : ''}`}><Clock3 className="mr-2 inline" />{Math.floor(remaining / 60)}:{String(remaining % 60).padStart(2, '0')}</strong></div><div className="flex justify-end"><span className="chip"><Trophy className="mr-1" size={16} /> {room.members.find((member) => member.id === selfId)?.sessionPoints ?? 0} pts</span></div></header>
    {game.phase === 'ROUND_RESULTS' && game.winnerId && <div className="reveal-pop mb-5 rounded-2xl border border-electric bg-electric/15 p-6 text-center"><div className="text-6xl">🎉</div><h1 className="font-display text-5xl text-electric">¡BINGO!</h1><p className="mt-2 text-xl font-extrabold">{name(game.winnerId)} ha completado el tablero</p><p className="mt-2 font-bold text-ink/65">Resultados en {remaining}s…</p></div>}
    {own && <section className="card mb-5 !p-3 sm:!p-5"><div className="mb-3 flex items-center justify-between gap-3"><div><span className="label !mb-0">Tu tablero</span><h1 className="font-display text-2xl">{name(selfId)}</h1></div><span className="chip bg-leaf/10 text-leaf">{own.completed}/{own.total}</span></div><PokemonBingoBoard board={own} width={game.width} selectedCellId={selectedCellId} interactive={game.phase === 'ROUND_ACTIVE' && playerState.canAct} onSelect={setSelectedCellId} /></section>}
    {game.phase === 'ROUND_ACTIVE' && selectedCell && <section className="card mb-5 !p-4"><div className="mb-3 flex flex-wrap items-start justify-between gap-3"><div><span className="label !mb-0">Casilla seleccionada</span><h2 className="font-display text-2xl">{selectedCell.conditions.map(describeBingoCondition).join(' + ')}</h2>{selectedCell.assignment && <p className="font-bold text-leaf">Actualmente: {selectedCell.assignment.name}</p>}</div>{selectedCell.assignment && <button className="btn-ghost" onClick={() => void remove()}><Trash2 size={17} /> Quitar Pokémon</button>}</div>{playerState.lastAttempt && <p className={`mb-3 rounded-xl p-3 font-extrabold ${playerState.lastAttempt.correct ? 'bg-leaf/10 text-leaf' : 'bg-berry/10 text-berry'}`} role="status">{playerState.lastAttempt.message}</p>}{actionError && <p className="mb-3 rounded-xl bg-berry/10 p-3 font-extrabold text-berry" role="alert">{actionError}</p>}{cooldownMs > 0 && <p className="mb-3 font-bold text-electric">Cooldown: {(cooldownMs / 1000).toFixed(1)}s. Puedes seguir buscando o cambiar de casilla.</p>}<div className="mb-2 flex items-center gap-2"><Search size={18} className="text-aqua" /><strong>Buscar Pokémon</strong></div><PokemonSelector pokemon={pokemon} locked={new Set()} disabled={false} confirmationDisabled={cooldownMs > 0} onSelect={assign} /></section>}
    {rivals.length > 0 && <section><div className="mb-3"><span className="label !mb-0">Rivales</span><h2 className="font-display text-2xl">Progreso en directo</h2></div><div className="mb-3 flex gap-2 overflow-x-auto pb-2" role="tablist">{rivals.map((id) => { const board = game.boards[id]!; return <button key={id} role="tab" aria-selected={rivalId === id} onClick={() => setSelectedRival(id)} className={`min-w-max rounded-2xl border px-4 py-3 text-left ${rivalId === id ? 'border-electric bg-electric/10' : 'border-ink/10 bg-surface-raised'}`}><strong className="block">{name(id)}</strong><small className="font-extrabold text-ink/65">{board.completed}/{board.total}</small></button>; })}</div>{rival && <div><div className="mb-2 flex items-center gap-2"><Eye size={18} className="text-aqua" /><strong className="font-display text-xl">Tablero de {name(rival.playerId)}</strong></div><PokemonBingoBoard board={rival} width={game.width} /></div>}</section>}
  </section>;
}
