import type { PokemonTriviaPublicState, RoomView } from '@pokemon-universe/shared';
import { Brain, RotateCcw, StopCircle } from 'lucide-react';
import { Avatar } from '../components/Avatar';

const categories = [
  ['type', 'Tipos'], ['generation', 'Generación'], ['hp', 'PS'], ['attack', 'Ataque'], ['defense', 'Defensa'], ['special_attack', 'At. Esp.'], ['special_defense', 'Def. Esp.'], ['speed', 'Velocidad'], ['bst', 'BST'], ['height', 'Altura'], ['weight', 'Peso'], ['dex_number', 'Pokédex'],
] as const;

export function PokemonTriviaResults({ room, selfId, onLobby, onEnd }: { room: RoomView; selfId: string; onLobby(): void; onEnd(): void }) {
  const game = room.game as PokemonTriviaPublicState; const host = room.hostId === selfId;
  return <section className="mx-auto max-w-4xl px-3 py-8 sm:px-5"><div className="rounded-2xl border border-ink/10 bg-surface p-4 sm:p-7"><Brain className="mx-auto text-aqua" size={48} /><h1 className="mb-6 text-center font-display text-3xl">Resultados · Pokémon Trivia</h1><div className="space-y-2">{game.results?.standings.map((entry) => { const member = room.members.find((candidate) => candidate.id === entry.playerId); const answers = entry.stats.answers ?? 0; const correct = entry.stats.correct ?? 0; const accuracy = answers ? Math.round(correct / answers * 100) : 0; return <article key={entry.playerId} className={`flex items-center gap-3 rounded-xl border p-3 ${entry.position === 1 ? 'border-electric/50 bg-electric/[.08]' : 'border-ink/10 bg-surface-raised'}`}><strong className="w-9 text-center font-display text-2xl">{entry.position <= 3 ? ['🥇', '🥈', '🥉'][entry.position - 1] : entry.position}</strong><Avatar name={member?.displayName ?? entry.playerId} avatar={member?.avatar} size="md" /><div className="min-w-0 flex-1"><strong className="block truncate text-lg">{member?.displayName ?? entry.playerId}</strong><p className="text-sm font-bold text-ink/60">{correct} aciertos · {accuracy}% de precisión</p><p className="mt-1 flex flex-wrap gap-x-2 text-xs font-bold text-ink/50">{categories.flatMap(([key, label]) => { const categoryAnswers = entry.stats[`${key}Answers`] ?? 0; return categoryAnswers ? [<span key={key}>{label}: {entry.stats[`${key}Correct`] ?? 0}/{categoryAnswers}</span>] : []; })}</p></div><strong className="text-xl text-berry">{entry.points} pts</strong></article>; })}</div>{host ? <div className="mt-6 flex flex-wrap justify-center gap-3"><button className="btn-primary" onClick={onLobby}><RotateCcw /> Continuar sesión</button><button className="btn-ghost" onClick={onEnd}><StopCircle /> Terminar sesión</button></div> : <p className="mt-6 text-center font-bold text-ink/60">Esperando al host…</p>}</div></section>;
}
