import type { PokemonBluffAuctionConfig, PokemonBluffAuctionPlayerState, PokemonBluffAuctionPublicState, RoomMemberView, RoomView } from '@pokemon-universe/shared';
import { ArrowUp, CheckCircle2, Clock3, Gavel, Mic2, Search, ShieldQuestion, XCircle } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import { Avatar } from '../components/Avatar';
import { ServerTimer } from '../components/ServerTimer';
import { usePokemonPool } from '../hooks/usePokemonPool';
import { useServerOffset } from '../hooks/useServerTime';
import { PokemonSelector } from './PokemonSelector';

const EMPTY_LOCKED = new Set<string>();

export function confirmBluffAuctionPass(confirm: (message: string) => boolean): boolean {
  return confirm('¿Seguro que quieres pasar? Quedarás fuera de esta ronda.');
}

function member(room: RoomView, id: string | null): RoomMemberView | undefined { return id ? room.members.find((candidate) => candidate.id === id) : undefined; }

function Condition({ game }: { game: PokemonBluffAuctionPublicState }) {
  return <section className="rounded-2xl border border-electric/25 bg-surface px-4 py-6 text-center sm:px-7" aria-label="Condición de la ronda"><ShieldQuestion className="mx-auto text-electric" size={30} /><p className="mt-2 font-display text-3xl leading-tight text-wrap-balance sm:text-5xl">{game.condition?.description}</p></section>;
}

function PlayerAuctionList({ room, game }: { room: RoomView; game: PokemonBluffAuctionPublicState }) {
  const latestBid = new Map<string, number>(); for (const event of game.bidHistory) if (event.type === 'BID') latestBid.set(event.playerId, event.amount);
  return <section className="rounded-2xl bg-surface p-4" aria-labelledby="auction-table"><h2 id="auction-table" className="mb-3 font-display text-xl">Mesa de pujas</h2><div className="space-y-2">{game.bidOrder.map((id, index) => { const person = member(room, id); const passed = game.passedPlayerIds.includes(id); const turn = id === game.currentTurnPlayerId; return <div key={id} className={`flex min-h-14 items-center gap-3 rounded-xl border px-3 py-2 ${turn ? 'border-aqua/45 bg-aqua/[.07]' : passed ? 'border-transparent bg-ink/[.035] opacity-60' : 'border-ink/10 bg-surface-raised'}`}><span className="w-5 text-center text-xs font-black text-ink/45">{index + 1}</span><Avatar name={person?.displayName ?? id} avatar={person?.avatar} presence={person?.presence} size="sm" /><span className="min-w-0 flex-1"><strong className="block truncate">{person?.displayName ?? id}</strong><small className={`font-extrabold ${turn ? 'text-aqua' : 'text-ink/50'}`}>{turn ? 'Está pujando' : passed ? 'Fuera de la ronda' : 'En la subasta'}</small></span><strong className={passed ? 'text-berry' : 'text-electric'}>{passed ? 'PASÓ' : latestBid.has(id) ? latestBid.get(id) : '—'}</strong></div>; })}</div></section>;
}

function BidControls({ game, player, onAction }: { game: PokemonBluffAuctionPublicState; player: PokemonBluffAuctionPlayerState; onAction(action: unknown): Promise<void> }) {
  const [amount, setAmount] = useState(game.minimumBid); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => setAmount(game.minimumBid), [game.minimumBid]);
  async function send(action: unknown) { if (busy) return; setBusy(true); setError(''); try { await onAction(action); } catch (caught) { setError(caught instanceof Error ? caught.message : 'La acción fue rechazada.'); } finally { setBusy(false); } }
  function submit(event: FormEvent) { event.preventDefault(); void send({ type: 'RAISE_BID', amount }); }
  if (!player.canRaise) return <div className="rounded-2xl border border-ink/10 bg-surface p-5 text-center"><Gavel className="mx-auto text-ink/35" size={34} /><strong className="mt-2 block font-display text-xl">Esperando tu turno</strong><p className="mt-1 text-sm font-bold text-ink/60">Puedes hablar por voz externa y decidir hasta dónde quieres bluffear.</p></div>;
  return <form onSubmit={submit} className="rounded-2xl border border-aqua/30 bg-aqua/[.05] p-4" aria-labelledby="bid-controls"><h2 id="bid-controls" className="font-display text-2xl">Tu turno</h2><p className="mt-1 text-sm font-bold text-ink/60">Sube la puja o abandona esta subasta.</p><div className="mt-4 flex items-stretch gap-2"><label className="min-w-0 flex-1"><span className="sr-only">Nueva puja</span><input className="field min-h-12 text-center text-xl font-black tabular-nums" type="number" min={game.minimumBid} max={game.maxBid} value={amount} onChange={(event) => setAmount(Number(event.target.value))} /></label><button type="submit" className="btn-primary shrink-0" disabled={busy || amount < game.minimumBid || amount > game.maxBid}><ArrowUp size={18} /> Pujar</button></div><div className="mt-2 flex flex-wrap gap-2">{[game.minimumBid, Math.min(game.maxBid, game.minimumBid + 2), Math.min(game.maxBid, game.minimumBid + 4)].filter((value, index, values) => values.indexOf(value) === index).map((value) => <button key={value} type="button" className="btn-ghost min-h-9 !px-3 text-sm" onClick={() => setAmount(value)}>Pujar {value}</button>)}</div><button type="button" className="mt-4 min-h-11 w-full rounded-xl border border-berry/25 bg-berry/[.06] font-extrabold text-berry hover:bg-berry/10" disabled={busy || !player.canPass} onClick={() => { if (confirmBluffAuctionPass(window.confirm)) void send({ type: 'PASS_BID' }); }}>Pasar esta ronda</button>{error && <p className="status-error mt-3" role="alert">{error}</p>}</form>;
}

function Attempts({ game }: { game: PokemonBluffAuctionPublicState }) {
  return <section className="rounded-2xl bg-surface p-4" aria-labelledby="attempt-list"><div className="mb-3 flex items-center justify-between gap-3"><h2 id="attempt-list" className="font-display text-xl">Respuestas enviadas</h2><span className="chip">{game.attempts.length} intentos</span></div>{game.attempts.length ? <ol className="max-h-[30rem] space-y-2 overflow-y-auto pr-1" aria-live="polite">{game.attempts.map((attempt, index) => <li key={`${attempt.pokemon.id}-${attempt.submittedAt}-${index}`} className={`flex items-center gap-3 rounded-xl px-3 py-2 ${attempt.result === 'CORRECT' ? 'bg-leaf/[.08]' : 'bg-berry/[.07]'}`}><strong className="w-6 text-right text-sm tabular-nums text-ink/45">{index + 1}.</strong><img src={attempt.pokemon.sprite} alt="" className="h-12 w-12 shrink-0 object-contain" /><span className="min-w-0 flex-1"><strong className="block truncate">{attempt.pokemon.name}</strong>{attempt.result === 'DUPLICATE' && <small className="font-bold text-berry">Ya utilizado · no cambia el tiempo</small>}</span>{attempt.result === 'CORRECT' ? <CheckCircle2 className="shrink-0 text-leaf" /> : <XCircle className="shrink-0 text-berry" />}</li>)}</ol> : <div className="empty-state !p-5">Los intentos aparecerán aquí para todo el grupo.</div>}</section>;
}

function Demonstration({ room, selfId, game, player, onAction }: { room: RoomView; selfId: string; game: PokemonBluffAuctionPublicState; player: PokemonBluffAuctionPlayerState; onAction(action: unknown): Promise<void> }) {
  const bidder = member(room, game.bidderId); const config = room.selectedGameConfig as PokemonBluffAuctionConfig;
  const { pokemon, error } = usePokemonPool({ generations: config.generations, includeForms: false, enabled: player.canSubmitPokemon });
  const serverOffset = useServerOffset(room.serverNow);
  return <section className="mx-auto max-w-[90rem] overflow-x-clip px-3 py-4 sm:px-5"><header className="flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-surface p-4 shadow-card"><div><span className="label !mb-0">Ronda {game.roundNumber}/{game.totalRounds} · Demostrar la apuesta</span><h1 className="font-display text-2xl sm:text-4xl">Pokémon Bluff Auction</h1></div><ServerTimer deadline={game.roundEndsAt} serverOffset={serverOffset} label="Tiempo restante" /></header><main className="mt-4 grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_22rem]"><div className="min-w-0 space-y-4"><Condition game={game} /><section className="rounded-2xl border border-ink/10 bg-surface p-4 sm:p-5"><div className="flex flex-wrap items-center gap-3"><Avatar name={bidder?.displayName ?? game.bidderId ?? 'Apostador'} avatar={bidder?.avatar} presence={bidder?.presence} size="lg" /><div className="min-w-0 flex-1"><span className="font-extrabold text-aqua">DEMOSTRANDO</span><h2 className="truncate font-display text-2xl">{bidder?.displayName} apostó {game.targetBid}</h2></div><div className="grid grid-cols-3 gap-2 text-center"><Metric label="Correctos" value={`${game.correctCount}/${game.targetBid}`} tone="leaf" /><Metric label="Incorrectos" value={String(game.incorrectCount)} tone="berry" /><Metric label="Faltan" value={String(game.remainingCount)} tone="electric" /></div></div></section>{player.canSubmitPokemon ? <section className="rounded-2xl border border-aqua/20 bg-surface p-4 sm:p-5" aria-labelledby="demonstration-search"><div className="mb-3"><span className="label !mb-0">Tu demostración</span><h2 id="demonstration-search" className="flex items-center gap-2 font-display text-2xl"><Search className="text-aqua" /> Nombra Pokémon</h2><p className="mt-1 text-sm font-bold text-ink/60">Acierto: +5 segundos · Fallo: −3 segundos.</p></div>{error ? <p className="status-error">{error}</p> : <PokemonSelector key={game.roundNumber} pokemon={pokemon} locked={EMPTY_LOCKED} disabled={false} variant="embedded" autoFocus={false} inputLabel="Buscar Pokémon para demostrar la apuesta" maxResults={5} onSelect={(pokemonId) => onAction({ type: 'SUBMIT_POKEMON', pokemonId })} />}</section> : <div className="rounded-2xl bg-ink/[.04] p-6 text-center"><Clock3 className="mx-auto text-electric" size={34} /><strong className="mt-2 block font-display text-xl">{selfId === game.bidderId ? 'Reconectando con la demostración…' : `${bidder?.displayName} está buscando`}</strong><p className="mt-1 font-bold text-ink/60">Todos veis los intentos en tiempo real.</p></div>}</div><aside className="xl:sticky xl:top-20"><Attempts game={game} /></aside></main></section>;
}

function Metric({ label, value, tone }: { label: string; value: string; tone: 'leaf' | 'berry' | 'electric' }) {
  const colors = { leaf: 'text-leaf', berry: 'text-berry', electric: 'text-electric' };
  return <span className="min-w-16 rounded-xl bg-ink/[.04] px-2 py-2"><small className="block text-[10px] font-black uppercase text-ink/50">{label}</small><strong className={`font-display text-xl tabular-nums ${colors[tone]}`}>{value}</strong></span>;
}

function RoundResult({ room, game }: { room: RoomView; game: PokemonBluffAuctionPublicState }) {
  const result = game.lastRound!; const bidder = member(room, result.bidderId); const serverOffset = useServerOffset(room.serverNow);
  const title = result.success ? `${bidder?.displayName} lo consiguió` : result.reason === 'IMPOSSIBLE' ? 'Apuesta imposible' : `${bidder?.displayName} no lo consiguió`;
  return <section className="mx-auto max-w-6xl overflow-x-clip px-3 py-5 sm:px-5"><div className={`overflow-hidden rounded-2xl border bg-surface ${result.success ? 'border-leaf/35' : 'border-berry/35'}`}><header className="flex flex-wrap items-start justify-between gap-3 border-b border-ink/10 p-4 sm:p-6"><div><span className="label !mb-0">Ronda {game.roundNumber} · Resultado</span><h1 className={`font-display text-3xl text-wrap-balance sm:text-5xl ${result.success ? 'text-leaf' : 'text-berry'}`}>{title}</h1><p className="mt-2 font-bold text-ink/65">{result.correctCount}/{result.bid} Pokémon correctos · {result.incorrectCount} incorrectos</p></div><ServerTimer deadline={game.nextTransitionAt} serverOffset={serverOffset} label="Siguiente ronda" /></header><div className="grid gap-4 p-4 sm:p-6 lg:grid-cols-[minmax(0,1fr)_20rem]"><main><div className="rounded-xl bg-ink/[.04] p-4 text-center"><strong className="font-display text-2xl">{result.condition.description}</strong>{result.reason === 'IMPOSSIBLE' && <p className="mt-3 font-extrabold text-berry">{bidder?.displayName} apostó {result.bid}, pero solo existían {result.validPokemonCount} respuestas válidas.</p>}{result.reason === 'TIMEOUT' && <p className="mt-3 font-extrabold text-berry">Se agotó el tiempo.</p>}{result.reason === 'BIDDER_LEFT' && <p className="mt-3 font-extrabold text-berry">El apostador abandonó la demostración.</p>}</div><div className="mt-4"><Attempts game={{ ...game, attempts: result.attempts }} /></div></main><aside className={`rounded-2xl p-5 text-center ${result.success ? 'bg-leaf/[.08]' : 'bg-electric/[.08]'}`}><Avatar name={bidder?.displayName ?? result.bidderId} avatar={bidder?.avatar} size="xl" /><h2 className="mt-3 font-display text-2xl">{bidder?.displayName}</h2>{result.success ? <><CheckCircle2 className="mx-auto mt-3 text-leaf" size={36} /><strong className="mt-2 block text-xl text-leaf">+{result.pointsAwarded[result.bidderId]} puntos</strong></> : <><XCircle className="mx-auto mt-3 text-berry" size={36} /><strong className="mt-2 block text-berry">Apostador · +0</strong><p className="mt-2 text-sm font-bold text-ink/65">Ganan los demás · +{Object.entries(result.pointsAwarded).find(([id]) => id !== result.bidderId)?.[1] ?? 0} cada uno</p></>}</aside></div></div></section>;
}

export function PokemonBluffAuctionGame({ room, selfId, onAction }: { room: RoomView; selfId: string; onAction(action: unknown): Promise<void> }) {
  const game = room.game as PokemonBluffAuctionPublicState; const player = room.gamePlayerState as PokemonBluffAuctionPlayerState;
  if (game.phase === 'POKEMON_SEARCH') return <Demonstration room={room} selfId={selfId} game={game} player={player} onAction={onAction} />;
  if (game.phase === 'ROUND_RESULTS' && game.lastRound) return <RoundResult room={room} game={game} />;
  const turn = member(room, game.currentTurnPlayerId); const leader = member(room, game.currentBidderId);
  return <section className="mx-auto max-w-[90rem] overflow-x-clip px-3 py-4 sm:px-5"><header className="flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-surface p-4 shadow-card"><div><span className="label !mb-0">Ronda {game.roundNumber}/{game.totalRounds} · Subasta</span><h1 className="font-display text-2xl sm:text-4xl">Pokémon Bluff Auction</h1></div><div className="flex items-center gap-3 rounded-xl bg-aqua/[.07] px-3 py-2"><Mic2 className="text-aqua" /><span><strong className="block text-sm">Bluff por voz externa</strong><small className="font-bold text-ink/55">Sin desafíos: la última persona demuestra</small></span></div></header><main className="mt-4 grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_22rem]"><div className="min-w-0 space-y-4"><Condition game={game} /><section className="rounded-2xl bg-surface p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><span className="font-bold text-ink/60">Puja actual</span><strong className="block font-display text-4xl text-electric">{game.currentBid ?? 'Empieza en 1'}{game.currentBid !== null && <small className="ml-2 text-lg text-ink/55">Pokémon</small>}</strong>{leader && <span className="text-sm font-bold text-ink/60">de {leader.displayName}</span>}</div><div className="flex items-center gap-3"><Avatar name={turn?.displayName ?? 'Turno'} avatar={turn?.avatar} presence={turn?.presence} size="md" /><span><small className="block font-black text-aqua">ESTÁ PUJANDO</small><strong className="block font-display text-xl">{turn?.displayName}</strong></span></div></div></section><BidControls game={game} player={player} onAction={onAction} /></div><aside className="xl:sticky xl:top-20"><PlayerAuctionList room={room} game={game} /></aside></main></section>;
}
