import type { Pokemon, PokeddleClueKey, PokeddleFeedbackEntry, PokeddlePublicBoard, PokeddleRacePlayerState, PokeddleRacePublicState, RoomView } from '@pokemon-universe/shared';
import { CheckCircle2, Clock3, Eye, Flag, Search, Trophy } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { api } from '../lib/api';
import { PokemonSelector } from './PokemonSelector';

const labels: Record<PokeddleClueKey, string> = { generation: 'Gen', dexNumber: 'Dex', types: 'Tipos', typeCount: 'N.º tipos', hp: 'HP', attack: 'Atq', defense: 'Def', specialAttack: 'At. Esp.', specialDefense: 'Def. Esp.', speed: 'Vel', baseStatTotal: 'Total', height: 'Altura', weight: 'Peso', evolutionStage: 'Evolución', legendaryStatus: 'Categoría', color: 'Color', abilities: 'Habilidades' };
const legendaryLabels: Record<string, string> = { NORMAL: 'Normal', LEGENDARY: 'Legendario', MYTHICAL: 'Mítico' };

function useCountdown(deadline: number | null, offset: number) { const [now, setNow] = useState(Date.now()); useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 100); return () => clearInterval(timer); }, []); return deadline ? Math.max(0, deadline - now - offset) : 0; }
function words(value: string) { return value.split('-').map((word) => word[0]?.toUpperCase() + word.slice(1)).join(' '); }
function direction(result: string) { return result === 'HIGHER' ? '↑ Mayor' : result === 'LOWER' ? '↓ Menor' : '= Igual'; }
function feedbackTone(result: string) { return result === 'MATCH' || result === 'EXACT' ? 'border-leaf/40 bg-leaf/15 text-leaf' : result === 'PARTIAL' ? 'border-electric/40 bg-electric/15 text-electric' : result === 'NONE' ? 'border-berry/40 bg-berry/10 text-berry' : 'border-aqua/30 bg-aqua/10 text-aqua'; }
function numericValue(key: PokeddleClueKey, value: number) { if (key === 'height') return `${(value / 10).toFixed(1)} m`; if (key === 'weight') return `${(value / 10).toFixed(1)} kg`; if (key === 'dexNumber') return `#${String(value).padStart(3, '0')}`; return value; }

export function formatPokeddleFeedback(key: PokeddleClueKey, entry: PokeddleFeedbackEntry): { value: string | number; result: string; tone: string } {
  if (entry.kind === 'NUMERIC') return { value: numericValue(key, entry.value), result: direction(entry.result), tone: feedbackTone(entry.result) };
  if (entry.kind === 'TYPES') return { value: entry.value.map(words).join(' / '), result: entry.result === 'EXACT' ? '✓ Exacto' : entry.result === 'PARTIAL' ? '~ Parcial' : '× Ninguno', tone: feedbackTone(entry.result) };
  if (entry.kind === 'EVOLUTION') return { value: entry.value.stages === 1 ? 'No evoluciona' : `Etapa ${entry.value.stage}/${entry.value.stages}`, result: direction(entry.result), tone: feedbackTone(entry.result) };
  if (entry.kind === 'ABILITIES') return { value: entry.value.map(words).join(', '), result: entry.matches ? `~ ${entry.matches} coincide${entry.matches === 1 ? '' : 'n'}` : '× Ninguna', tone: feedbackTone(entry.result) };
  const value = key === 'legendaryStatus' ? legendaryLabels[entry.value] ?? entry.value : words(entry.value);
  return { value, result: entry.result === 'MATCH' ? '✓ Coincide' : '× No coincide', tone: feedbackTone(entry.result) };
}

export function PokeddleBoard({ board, clues, prominent = false }: { board: PokeddlePublicBoard; clues: PokeddleClueKey[]; prominent?: boolean }) {
  return <div className={`overflow-hidden rounded-[1.5rem] border-2 ${prominent ? 'border-aqua/45 bg-surface' : 'border-ink/10 bg-surface-raised'}`}>
    {board.revealedPokemon && <div className="flex items-center gap-3 border-b-2 border-leaf/25 bg-leaf/10 px-4 py-3"><img src={board.revealedPokemon.sprite} alt="" className="h-14 w-14 object-contain [image-rendering:pixelated]" /><div><strong className="block font-display text-xl text-leaf">{board.solved ? '✅ Pokémon encontrado' : 'Objetivo revelado'}</strong><span className="font-extrabold">{board.revealedPokemon.name}</span>{board.solved && <small className="ml-2 font-bold text-ink/45">Ronda {board.solvedRound}</small>}</div></div>}
    <div className="max-w-full overflow-x-auto overscroll-x-contain"><table className="w-max min-w-full border-collapse text-sm"><thead><tr className="bg-night/35 text-left"><th className="sticky left-0 z-10 min-w-40 bg-night px-3 py-3 font-black">Intento</th>{clues.map((key) => <th key={key} className="min-w-28 px-3 py-3 font-black">{labels[key]}</th>)}</tr></thead><tbody>{board.rows.length ? board.rows.map((row) => <tr key={row.round} className="border-t border-ink/10"><td className="sticky left-0 z-10 bg-surface px-3 py-2">{row.status === 'NO_GUESS' ? <span className="font-extrabold text-berry">R{row.round} · Sin respuesta</span> : <span className="flex items-center gap-2"><img src={row.guessedPokemon?.sprite} alt="" className="h-10 w-10 object-contain" /><span><strong className="block">{row.guessedPokemon?.name}</strong><small className="font-bold text-ink/40">Ronda {row.round}</small></span>{row.correct && <CheckCircle2 className="text-leaf" size={18} />}</span>}</td>{clues.map((key) => { const feedback = row.feedback?.[key]; if (!feedback) return <td key={key} className="px-3 py-2 text-ink/25">—</td>; const shown = formatPokeddleFeedback(key, feedback); return <td key={key} className="px-2 py-2"><span className={`block min-h-14 rounded-xl border px-2 py-1.5 ${shown.tone}`}><strong className="block leading-tight">{shown.value}</strong><small className="font-extrabold">{shown.result}</small></span></td>; })}</tr>) : <tr><td colSpan={clues.length + 1} className="px-4 py-10 text-center font-bold text-ink/40">Todavía no hay intentos resueltos.</td></tr>}</tbody></table></div>
  </div>;
}

export function PokeddleRaceGame({ room, selfId, onAction }: { room: RoomView; selfId: string; onAction(action: unknown): Promise<void> }) {
  const game = room.game as PokeddleRacePublicState; const player = room.gamePlayerState as PokeddleRacePlayerState;
  const config = room.selectedGameConfig as { generations: number[]; roundSeconds: number };
  const [pokemon, setPokemon] = useState<Pokemon[]>([]); const [selectedRival, setSelectedRival] = useState<string | null>(null);
  const offset = useMemo(() => room.serverNow - Date.now(), [room.serverNow]);
  const remainingMs = useCountdown(game.roundEndsAt ?? game.nextTransitionAt, offset); const remaining = Math.ceil(remainingMs / 1_000);
  useEffect(() => { void api<{ pokemon: Pokemon[] }>(`/pokemon?generations=${config.generations.join(',')}`).then((body) => setPokemon(body.pokemon)); }, [config.generations.join(',')]);
  const own = game.boards[selfId]; const rivals = game.activePlayerIds.filter((id) => id !== selfId).concat(Object.keys(game.boards).filter((id) => id !== selfId && !game.activePlayerIds.includes(id)));
  const rivalId = selectedRival && game.boards[selectedRival] ? selectedRival : rivals[0] ?? null; const rival = rivalId ? game.boards[rivalId] : null;
  const memberName = (id: string) => room.members.find((member) => member.id === id)?.displayName ?? id;
  return <section className="mx-auto max-w-[96rem] px-3 py-4 sm:px-5 md:py-6">
    <header className="mb-4 grid gap-3 rounded-[1.5rem] border-2 border-ink/10 bg-surface/90 p-4 sm:grid-cols-[1fr_auto_1fr] sm:items-center"><div className="flex flex-wrap gap-2"><span className="chip">Ronda {game.roundNumber}/{game.maxRounds}</span><span className="chip">{game.activePlayerIds.length} en carrera</span></div><div className="text-center"><span className="label !mb-0">Pokédle Race</span><strong className={`font-display text-3xl ${remaining <= 5 && game.phase === 'ROUND_ACTIVE' ? 'timer-pulse text-berry' : ''}`}><Clock3 className="mr-2 inline" />{remaining}s</strong></div><div className="flex justify-end"><span className="chip"><Trophy className="mr-1" size={16} /> {room.members.find((member) => member.id === selfId)?.sessionPoints ?? 0} pts sesión</span></div></header>
    {own && <section className="card mb-5 !p-3 sm:!p-5"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><span className="label !mb-0">Tu tablero</span><h1 className="font-display text-2xl font-bold">{memberName(selfId)}</h1></div>{own.solved ? <span className="chip bg-leaf/15 text-leaf"><Flag size={16} className="mr-1" /> Finalizado</span> : game.answeredPlayerIds.includes(selfId) ? <span className="chip bg-aqua/15 text-aqua">Has respondido ✓</span> : <span className="chip">{game.phase === 'ROUND_RESULTS' ? 'Calculando siguiente ronda' : 'Esperando intento'}</span>}</div><PokeddleBoard board={own} clues={game.enabledClues} prominent /></section>}
    {!own?.solved && game.phase === 'ROUND_ACTIVE' && <div className="mb-5">{player.canGuess ? <><div className="mb-2 flex items-center gap-2 px-1"><Search size={18} className="text-aqua" /><strong>Envía un único Pokémon; quedará bloqueado por esta ronda.</strong></div><PokemonSelector pokemon={pokemon} locked={new Set()} disabled={false} onSelect={(pokemonId) => onAction({ type: 'GUESS_POKEMON', pokemonId })} /></> : <div className="card grid min-h-36 place-items-center text-center"><div><CheckCircle2 className="mx-auto text-leaf" size={42} /><h2 className="mt-2 font-display text-2xl">Respuesta bloqueada</h2><p className="font-bold text-ink/45">Esperando al resto de entrenadores.</p></div></div>}</div>}
    {own?.solved && <div className="card mb-5 grid min-h-32 place-items-center text-center"><div><Eye className="mx-auto text-aqua" /><h2 className="font-display text-2xl">Ahora observas la carrera</h2><p className="font-bold text-ink/45">Tu Pokémon ya es público y no volverás a bloquear una ronda.</p></div></div>}
    {rivals.length > 0 && <section><div className="mb-3 flex items-end justify-between gap-2"><div><span className="label !mb-0">Rivales</span><h2 className="font-display text-2xl">Todos los tableros</h2></div><span className="text-sm font-bold text-ink/45">Toca un entrenador para abrirlo</span></div><div className="mb-3 flex gap-2 overflow-x-auto pb-2" role="tablist">{rivals.map((id) => { const board = game.boards[id]!; return <button key={id} role="tab" aria-selected={rivalId === id} onClick={() => setSelectedRival(id)} className={`min-w-max rounded-2xl border-2 px-4 py-3 text-left ${rivalId === id ? 'border-electric bg-electric/10' : 'border-ink/10 bg-surface-raised'}`}><strong className="block">{memberName(id)}</strong><small className={`font-extrabold ${board.solved ? 'text-leaf' : 'text-ink/45'}`}>{board.solved ? `✓ Ronda ${board.solvedRound}` : `${board.rows.length} rondas · ${board.validGuesses} intentos`}</small></button>; })}</div>{rival && <div><div className="mb-2 flex items-center justify-between px-1"><strong className="font-display text-xl">{memberName(rival.playerId)}</strong>{game.answeredPlayerIds.includes(rival.playerId) && !rival.solved && <span className="chip bg-aqua/10 text-aqua">Ha respondido ✓</span>}</div><PokeddleBoard board={rival} clues={game.enabledClues} /></div>}</section>}
  </section>;
}

