import type { PokemonBingoPublicState, RoomView } from '@pokemon-universe/shared';
import { RotateCcw, StopCircle, Trophy } from 'lucide-react';
import { useState } from 'react';
import { Avatar } from '../components/Avatar';
import { PokemonBingoBoard } from './PokemonBingoGame';

export function PokemonBingoResults({ room, selfId, onLobby, onEnd }: { room: RoomView; selfId: string; onLobby(): void; onEnd(): void }) {
  const game = room.game as PokemonBingoPublicState; const host = room.hostId === selfId; const [selectedId, setSelectedId] = useState(game.results?.standings[0]?.playerId ?? selfId); const board = game.boards[selectedId];
  const name = (id: string) => room.members.find((member) => member.id === id)?.displayName ?? id;
  return <section className="mx-auto max-w-[90rem] px-4 py-9"><div className="card"><Trophy className="mx-auto text-electric" size={54} /><span className="label mt-3 text-center">Pokémon Bingo — Resultados</span><h1 className="mb-7 text-center font-display text-4xl">{game.winnerId ? `🎉 Bingo de ${name(game.winnerId)}` : 'Tiempo agotado'}</h1><div className="grid gap-3 lg:grid-cols-2">{game.results?.standings.map((entry) => { const member = room.members.find((item) => item.id === entry.playerId); const resultBoard = game.boards[entry.playerId]!; return <button key={entry.playerId} onClick={() => setSelectedId(entry.playerId)} className={`flex items-center gap-3 rounded-2xl border-2 p-3 text-left ${selectedId === entry.playerId ? 'border-electric bg-electric/10' : 'border-ink/10 bg-surface-raised'}`}><strong className="w-9 text-center font-display text-2xl">{entry.position <= 3 ? ['🥇', '🥈', '🥉'][entry.position - 1] : entry.position}</strong><Avatar name={member?.displayName ?? entry.playerId} avatar={member?.avatar} size="md" /><span className="min-w-0 flex-1"><strong className="block truncate">{member?.displayName}</strong><small className="font-extrabold text-ink/45">{resultBoard.completed}/{resultBoard.total}{entry.playerId === game.winnerId ? ' · BINGO' : ''} · {entry.stats.correctAssignments} correctos · {entry.stats.incorrectAttempts} fallos</small></span><strong className="text-berry">+{entry.points}</strong></button>; })}</div>{board && <section className="mt-7"><div className="mb-3"><span className="label !mb-0">Tablero final</span><h2 className="font-display text-2xl">{name(selectedId)} — {board.completed}/{board.total}</h2></div><PokemonBingoBoard board={board} width={game.width} /></section>}{host ? <div className="mt-7 flex flex-wrap justify-center gap-3"><button className="btn-primary" onClick={onLobby}><RotateCcw /> Volver al mismo lobby</button><button className="btn-ghost" onClick={onEnd}><StopCircle /> Terminar sesión</button></div> : <p className="mt-6 text-center font-bold text-ink/45">Esperando al host…</p>}</div></section>;
}
