import type { Pokemon, PokemonCryQuizPlayerState, PokemonCryQuizPublicState, RoomView } from '@pokemon-universe/shared';
import { CheckCircle2, Eye, Headphones, Play, RotateCcw, Volume2, XCircle } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { Avatar } from '../components/Avatar';
import { ServerTimer } from '../components/ServerTimer';
import { usePokemonPool } from '../hooks/usePokemonPool';
import { useRemainingMs, useServerOffset } from '../hooks/useServerTime';
import { PokemonSelector } from './PokemonSelector';

const EMPTY_LOCKED = new Set<string>();

function CryPlayer({ source, replay = false }: { source: string; replay?: boolean }) {
  const audioRef = useRef<HTMLAudioElement>(null); const [playing, setPlaying] = useState(false); const [error, setError] = useState('');
  useEffect(() => { setPlaying(false); setError(''); audioRef.current?.load(); }, [source]);
  const play = async () => { try { setError(''); if (!audioRef.current) return; audioRef.current.currentTime = 0; await audioRef.current.play(); setPlaying(true); } catch { setError('No se pudo reproducir el audio. Comprueba el volumen o vuelve a intentarlo.'); } };
  return <div className="text-center"><audio ref={audioRef} src={source} preload="auto" onEnded={() => setPlaying(false)} onError={() => setError('El grito no está disponible temporalmente.')} /><button type="button" onClick={() => void play()} className={`mx-auto grid aspect-square w-40 place-items-center rounded-full border transition-[transform,background-color,border-color] duration-200 hover:scale-[1.03] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-aqua sm:w-48 ${playing ? 'border-electric bg-electric/15 text-electric' : 'border-aqua/50 bg-aqua/10 text-aqua'}`} aria-label={replay ? 'Volver a escuchar el grito' : 'Reproducir grito'}>{playing ? <Volume2 size={64} className="animate-pulse motion-reduce:animate-none" /> : replay ? <RotateCcw size={58} /> : <Play size={64} className="translate-x-1" />}</button><strong className="mt-3 block font-display text-xl">{playing ? 'Escuchando…' : replay ? 'Volver a escuchar' : 'Pulsa para escuchar'}</strong>{error && <p className="mt-2 text-sm font-bold text-berry" role="alert">{error}</p>}</div>;
}

function GuessArea({ pokemon, game, player, participating, serverOffset, onAction }: { pokemon: Pokemon[]; game: PokemonCryQuizPublicState; player: PokemonCryQuizPlayerState; participating: boolean; serverOffset: number; onAction(action: unknown): Promise<void> }) {
  const cooldownMs = useRemainingMs(player.cooldownUntil, serverOffset);
  if (!participating) return <div className="grid min-h-36 place-items-center text-center"><div><Eye className="mx-auto text-aqua" /><strong className="mt-2 block font-display text-xl">Estás observando</strong><p className="text-sm font-bold text-ink/60">Puedes escuchar el grito y seguir los resultados.</p></div></div>;
  if (player.solved) return <div className="grid min-h-36 place-items-center rounded-xl bg-leaf/[.08] text-center"><div><CheckCircle2 className="mx-auto text-leaf" size={42} /><strong className="block font-display text-2xl text-leaf">¡Grito acertado!</strong><p className="font-bold text-ink/65">{player.solveOrder}.º · +{player.roundPoints} puntos</p></div></div>;
  return <div><div className="mb-2 flex items-center justify-between gap-2"><h2 className="font-display text-xl">¿Quién es?</h2><span className="text-xs font-bold text-ink/60">{player.attemptCount} intento{player.attemptCount === 1 ? '' : 's'}</span></div>{player.lastAttempt?.result === 'INCORRECT' && <p className="mb-2 flex items-center justify-between rounded-xl bg-berry/[.08] px-3 py-2 text-sm font-extrabold text-berry" role="status"><span className="flex items-center gap-1"><XCircle size={17} /> Incorrecto</span><span>{cooldownMs > 0 ? `${(cooldownMs / 1_000).toFixed(1)}s` : 'Prueba otra vez'}</span></p>}<PokemonSelector key={game.roundNumber} pokemon={pokemon} locked={EMPTY_LOCKED} disabled={!player.canGuess} confirmationDisabled={cooldownMs > 0} variant="embedded" autoFocus={false} inputLabel={`Buscar respuesta para el grito ${game.roundNumber}`} onSelect={(pokemonId) => onAction({ type: 'GUESS_POKEMON', pokemonId })} /></div>;
}

function PlayerStatus({ room, game }: { room: RoomView; game: PokemonCryQuizPublicState }) {
  const solved = new Map(game.solvedPlayers.map((entry) => [entry.playerId, entry.solveOrder]));
  return <aside className="rounded-xl border border-ink/10 bg-surface p-3"><h2 className="mb-2 font-display text-lg">Jugadores</h2><div className="space-y-1.5">{room.members.map((member) => <div key={member.id} className="flex items-center gap-2 rounded-lg bg-ink/[.035] p-2"><Avatar name={member.displayName} avatar={member.avatar} presence={member.presence} size="xs" /><strong className="min-w-0 flex-1 truncate text-sm">{member.displayName}</strong><span className="text-xs font-bold text-ink/60">{game.scores[member.id] ?? 0} pts</span>{solved.has(member.id) && <CheckCircle2 className="text-leaf" size={16} />}</div>)}</div></aside>;
}

function RoundReveal({ room, game, serverOffset }: { room: RoomView; game: PokemonCryQuizPublicState; serverOffset: number }) {
  const result = game.lastRound!;
  return <section className="mx-auto max-w-5xl px-3 py-5 sm:px-5"><header className="mb-4 flex items-start justify-between gap-3"><div><p className="font-bold text-leaf">Ronda {game.roundNumber} resuelta</p><h1 className="font-display text-3xl sm:text-4xl">¡Era {result.pokemon.name}!</h1></div><ServerTimer deadline={game.nextTransitionAt} serverOffset={serverOffset} label="Siguiente ronda" /></header><div className="grid gap-5 rounded-2xl border border-leaf/25 bg-surface p-4 sm:p-6 md:grid-cols-[18rem_1fr]"><div className="text-center"><img src={result.pokemon.sprite} alt={result.pokemon.name} className="mx-auto h-52 w-52 object-contain [image-rendering:pixelated]" /><strong className="font-display text-2xl">{result.pokemon.name}</strong><p className="text-sm font-bold text-ink/60">Generación {result.pokemon.generation} · grito {result.cryVersion === 'LATEST' ? 'actual' : 'clásico'}</p><div className="mt-3"><CryPlayer source={result.cryUrl} replay /></div></div><div className="space-y-2">{room.members.filter((member) => member.role === 'PLAYER').sort((a, b) => (result.solves[a.id]?.solveOrder ?? Infinity) - (result.solves[b.id]?.solveOrder ?? Infinity)).map((member) => { const solve = result.solves[member.id]; return <article key={member.id} className={`flex items-center gap-3 rounded-xl border p-3 ${solve ? 'border-leaf/30 bg-leaf/[.07]' : 'border-ink/10'}`}><Avatar name={member.displayName} avatar={member.avatar} size="sm" /><div className="min-w-0 flex-1"><strong className="block truncate">{member.displayName}</strong><small className="font-bold text-ink/60">{solve ? `${solve.solveOrder}.º · ${(solve.elapsedMs / 1_000).toFixed(1)}s · ${solve.attempts} intentos` : 'No acertó'}</small></div><strong className={solve ? 'text-leaf' : 'text-ink/40'}>+{solve?.points ?? 0}</strong></article>; })}</div></div></section>;
}

export function PokemonCryQuizGame({ room, selfId, onAction }: { room: RoomView; selfId: string; onAction(action: unknown): Promise<void> }) {
  const game = room.game as PokemonCryQuizPublicState; const player = room.gamePlayerState as PokemonCryQuizPlayerState; const config = room.selectedGameConfig as { generations: number[]; includeRegionalForms: boolean }; const offset = useServerOffset(room.serverNow); const { pokemon, error } = usePokemonPool({ generations: config.generations, includeForms: config.includeRegionalForms }); const self = room.members.find((member) => member.id === selfId); const participating = self?.role === 'PLAYER';
  if (game.phase === 'ROUND_RESULTS' && game.lastRound) return <RoundReveal room={room} game={game} serverOffset={offset} />;
  return <section className="mx-auto max-w-6xl overflow-x-clip px-3 py-4 sm:px-5"><header className="mb-4 flex items-center justify-between gap-3"><div><p className="text-xs font-extrabold text-ink/60">Ronda {game.roundNumber} / {game.totalRounds}</p><h1 className="font-display text-2xl sm:text-3xl">Adivina el Grito</h1></div><ServerTimer deadline={game.roundEndsAt} serverOffset={offset} /></header><div className="grid items-start gap-4 lg:grid-cols-[minmax(0,1fr)_18rem]"><main className="rounded-2xl border border-ink/10 bg-surface"><div className="grid min-h-80 place-items-center border-b border-ink/10 p-5"><div><Headphones className="mx-auto mb-3 text-ink/25" size={42} />{game.cryUrl && <CryPlayer source={game.cryUrl} />}</div></div><div className="p-4 sm:p-5">{error ? <p className="status-error" role="alert">{error}</p> : <GuessArea pokemon={pokemon} game={game} player={player} participating={Boolean(participating)} serverOffset={offset} onAction={onAction} />}</div></main><PlayerStatus room={room} game={game} /></div></section>;
}
