import type { Pokemon, PokemonPaletteGuessPlayerState, PokemonPaletteGuessPublicState, RoomView } from '@pokemon-universe/shared';
import { CheckCircle2, Eye, Palette, XCircle } from 'lucide-react';
import { Avatar } from '../components/Avatar';
import { ServerTimer } from '../components/ServerTimer';
import { usePokemonPool } from '../hooks/usePokemonPool';
import { useRemainingMs, useServerOffset } from '../hooks/useServerTime';
import { PokemonSelector } from './PokemonSelector';

const EMPTY_LOCKED = new Set<string>();
function PaletteClue({ colors, compact = false }: { colors: readonly string[]; compact?: boolean }) {
  return <div className={`flex w-full overflow-hidden rounded-xl ${compact ? 'h-20' : 'h-56 sm:h-72'}`} role="img" aria-label={`Paleta de ${colors.length} colores`}>{colors.map((color, index) => <span key={`${color}-${index}`} className="h-full min-w-0 flex-1" style={{ backgroundColor: color }} aria-label={`Color ${index + 1}: ${color}`} title={color} />)}</div>;
}
function PlayerStatus({ room, game }: { room: RoomView; game: PokemonPaletteGuessPublicState }) { const solved = new Set(game.solvedPlayers.map(({ playerId }) => playerId)); return <aside className="rounded-xl border border-ink/10 bg-surface p-3"><h2 className="mb-2 font-display text-lg">Jugadores</h2><div className="space-y-1.5">{room.members.filter((member) => member.role === 'PLAYER').map((member) => <div key={member.id} className="flex items-center gap-2 rounded-lg bg-ink/[.035] p-2"><Avatar name={member.displayName} avatar={member.avatar} presence={member.presence} size="xs" /><strong className="min-w-0 flex-1 truncate text-sm">{member.displayName}</strong><span className="text-xs font-bold text-ink/60">{game.scores[member.id] ?? 0}</span>{solved.has(member.id) && <CheckCircle2 className="text-leaf" size={16} />}</div>)}</div></aside>; }
function GuessArea({ pokemon, game, player, offset, onAction }: { pokemon: Pokemon[]; game: PokemonPaletteGuessPublicState; player: PokemonPaletteGuessPlayerState; offset: number; onAction(action: unknown): Promise<void> }) { const cooldown = useRemainingMs(player.cooldownUntil, offset); if (player.role === 'SPECTATOR') return <div className="py-6 text-center"><Eye className="mx-auto text-aqua" /><strong className="mt-2 block font-display text-xl">Estás observando</strong></div>; if (player.solved) return <div className="rounded-xl bg-leaf/[.09] p-5 text-center"><CheckCircle2 className="mx-auto text-leaf" size={38} /><strong className="block font-display text-2xl text-leaf">¡Paleta acertada!</strong><p className="font-bold text-ink/65">{player.solveOrder}.º · +{player.roundPoints} puntos</p></div>; return <div><div className="mb-2 flex items-center justify-between"><h2 className="font-display text-xl">¿De quién son estos colores?</h2><span className="text-xs font-bold text-ink/60">{player.attemptCount} intentos</span></div>{player.lastAttempt?.result === 'INCORRECT' && <p className="mb-2 flex items-center justify-between rounded-xl bg-berry/[.08] px-3 py-2 text-sm font-extrabold text-berry"><span><XCircle className="mr-1 inline" size={17} />Incorrecto</span><span>{cooldown > 0 ? `${(cooldown / 1_000).toFixed(1)}s` : 'Prueba otra vez'}</span></p>}<PokemonSelector key={game.roundNumber} pokemon={pokemon} locked={EMPTY_LOCKED} disabled={!player.canGuess} confirmationDisabled={cooldown > 0} variant="embedded" autoFocus={false} inputLabel={`Buscar respuesta para la paleta ${game.roundNumber}`} onSelect={(pokemonId) => onAction({ type: 'GUESS_POKEMON', pokemonId })} /></div>; }
function Reveal({ room, game, offset }: { room: RoomView; game: PokemonPaletteGuessPublicState; offset: number }) { const result = game.lastRound!; return <section className="mx-auto max-w-5xl px-3 py-5 sm:px-5"><header className="mb-4 flex items-start justify-between gap-3"><div><p className="font-extrabold text-leaf">Ronda {game.roundNumber} resuelta</p><h1 className="font-display text-3xl sm:text-4xl">¡Era {result.pokemon.name}!</h1></div><ServerTimer deadline={game.nextTransitionAt} serverOffset={offset} label="Siguiente ronda" /></header><div className="grid gap-5 rounded-2xl border border-leaf/25 bg-surface p-4 sm:p-6 md:grid-cols-[19rem_1fr]"><div className="text-center"><PaletteClue colors={result.palette} compact /><img src={result.pokemon.sprite} alt={result.pokemon.name} className="mx-auto mt-2 h-52 w-52 object-contain [image-rendering:pixelated]" /><strong className="font-display text-2xl">{result.pokemon.name}</strong><p className="text-sm font-bold text-ink/60">Generación {result.pokemon.generation}</p></div><div className="space-y-2">{room.members.filter((member) => member.role === 'PLAYER').sort((a, b) => (result.solves[a.id]?.solveOrder ?? Infinity) - (result.solves[b.id]?.solveOrder ?? Infinity)).map((member) => { const solve = result.solves[member.id]; return <article key={member.id} className={`flex items-center gap-3 rounded-xl border p-3 ${solve ? 'border-leaf/30 bg-leaf/[.07]' : 'border-ink/10'}`}><Avatar name={member.displayName} avatar={member.avatar} size="sm" /><div className="min-w-0 flex-1"><strong className="block truncate">{member.displayName}</strong><small className="font-bold text-ink/60">{solve ? `${solve.solveOrder}.º · ${(solve.elapsedMs / 1_000).toFixed(1)}s · ${solve.attempts} intentos` : 'No acertó'}</small></div><strong className={solve ? 'text-leaf' : 'text-ink/40'}>+{solve?.points ?? 0}</strong></article>; })}</div></div></section>; }

export function PokemonPaletteGuessGame({ room, onAction }: { room: RoomView; selfId: string; onAction(action: unknown): Promise<void> }) { const game = room.game as PokemonPaletteGuessPublicState; const player = room.gamePlayerState as PokemonPaletteGuessPlayerState; const config = room.selectedGameConfig as { generations: number[] }; const offset = useServerOffset(room.serverNow); const { pokemon, error } = usePokemonPool({ generations: config.generations }); if (game.phase === 'ROUND_RESULTS' && game.lastRound) return <Reveal room={room} game={game} offset={offset} />; return <section className="mx-auto max-w-7xl overflow-x-clip px-3 py-4 sm:px-5"><header className="mb-4 flex items-center justify-between gap-3"><div><p className="text-xs font-extrabold text-ink/60">Ronda {game.roundNumber} / {game.totalRounds}</p><h1 className="font-display text-2xl sm:text-3xl">Adivina por la Paleta</h1></div><ServerTimer deadline={game.roundEndsAt} serverOffset={offset} /></header><div className="grid items-start gap-4 lg:grid-cols-[minmax(0,1fr)_18rem]"><main className="overflow-hidden rounded-2xl border border-ink/10 bg-surface"><div className="p-3 sm:p-5"><div className="mb-3 flex items-center gap-2 text-ink/60"><Palette size={20} /><strong>Colores dominantes del sprite</strong></div><PaletteClue colors={game.colors} /></div><div className="border-t border-ink/10 p-4 sm:p-5">{error ? <p className="status-error" role="alert">{error}</p> : <GuessArea pokemon={pokemon} game={game} player={player} offset={offset} onAction={onAction} />}</div></main><PlayerStatus room={room} game={game} /></div></section>; }
