import type { PokemonPaletteGuessPublicState, RoomView } from '@pokemon-universe/shared';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it } from 'vitest';
import { PokemonPaletteGuessConfigPanel } from '../games/pokemon-palette-guess/ConfigPanel';
import { PokemonPaletteGuessGame } from './PokemonPaletteGuessGame';
import { PokemonPaletteGuessResults } from './PokemonPaletteGuessResults';

const colors = ['#183048', '#d86048', '#f0c030', '#4878c0', '#78a848'];
const active: PokemonPaletteGuessPublicState = { gameId: 'pokemon-palette-guess', phase: 'ROUND_ACTIVE', roundNumber: 1, totalRounds: 10, colors, colorWeights: colors.map(() => 1 / colors.length), hints: [], attempts: [], solvedPlayers: [], scores: { p1: 0 }, roundStartedAt: 1_000, roundEndsAt: 26_000, nextTransitionAt: null, lastRound: null, results: null };
function room(game: PokemonPaletteGuessPublicState, playerState: unknown): RoomView { return { code: 'ABC234', phase: game.phase, hostId: 'p1', maxPlayers: 8, availableGames: [], selectedGameId: 'pokemon-palette-guess', selectedGameConfig: { generations: [1], roundSeconds: 25, rounds: 10, paletteSize: 5, hintsEnabled: false, hintKinds: ['GENERATION', 'TYPE', 'EVOLUTION'] }, sessionMode: { type: 'INFINITE' }, gameSelectionMode: { type: 'FIXED' }, nextGameVote: null, gamesPlayed: 0, sessionStandings: [], sessionHistory: [], serverNow: 1_000, game, gamePlayerState: playerState, members: [{ id: 'p1', displayName: 'Eru', avatar: { type: 'PRESET', value: 'trainer-berry' }, connected: true, presence: 'CONNECTED', roomRole: 'HOST', role: 'PLAYER', isHost: true, ready: false, sessionPoints: 0 }] } as unknown as RoomView; }

describe('Adivina por la Paleta UI', () => {
  it('makes the palette the visual focus without rendering a target identity', () => { const weighted = { ...active, colorWeights: [0.4, 0.25, 0.15, 0.12, 0.08] }; const markup = renderToStaticMarkup(createElement(PokemonPaletteGuessGame, { room: room(weighted, { role: 'PLAYER', canGuess: true, solved: false, solveOrder: null, cooldownUntil: null, roundPoints: 0, attemptCount: 0, lastAttempt: null }), selfId: 'p1', onAction: async () => undefined })); expect(markup).toContain('Paleta de 5 colores'); expect(markup).toContain('background-color:#183048'); expect(markup).toContain('aproximadamente 40%'); expect(markup).not.toContain('Pikachu'); });
  it('renders public hints and incorrect attempts', () => { const game: PokemonPaletteGuessPublicState = { ...active, hints: [{ kind: 'GENERATION', value: 1 }, { kind: 'TYPE', values: ['electric'] }], attempts: [{ playerId: 'p1', guessedPokemon: { id: 'raichu', name: 'Raichu', sprite: '/raichu.png' }, attemptedAt: 2_000 }] }; const markup = renderToStaticMarkup(createElement(PokemonPaletteGuessGame, { room: room(game, { role: 'PLAYER', canGuess: true, solved: false, solveOrder: null, cooldownUntil: null, roundPoints: 0, attemptCount: 1, lastAttempt: { result: 'INCORRECT', attemptedAt: 2_000 } }), selfId: 'p1', onAction: async () => undefined })); expect(markup).toContain('Generación 1'); expect(markup).toContain('Eléctrico'); expect(markup).toContain('Intentos públicos'); expect(markup).toContain('Raichu'); });
  it('renders lobby controls for palette coverage, hints and rounds', () => { const markup = renderToStaticMarkup(createElement(PokemonPaletteGuessConfigPanel, { config: { generations: [1], roundSeconds: 25, rounds: 10, paletteSize: 5, hintsEnabled: true, hintKinds: ['GENERATION', 'TYPE', 'EVOLUTION'] }, disabled: false, onChange: async () => undefined })); expect(markup).toContain('Máximo de colores visibles'); expect(markup).toContain('todos los colores dominantes'); expect(markup).toContain('Pistas adicionales'); expect(markup).toContain('Número de rondas'); });
  it('renders the final ranking and host controls', () => { const finished: PokemonPaletteGuessPublicState = { ...active, phase: 'GAME_RESULTS', roundEndsAt: null, results: { winnerId: 'p1', standings: [{ playerId: 'p1', position: 1, points: 13, won: true, stats: { correct: 1, totalAttempts: 1, firstTry: 1 } }] } }; const markup = renderToStaticMarkup(createElement(PokemonPaletteGuessResults, { room: room(finished, null), selfId: 'p1', onLobby: () => undefined, onEnd: () => undefined })); expect(markup).toContain('Resultados · Adivina por la Paleta'); expect(markup).toContain('Continuar sesión'); });
});
