import type { RoomMemberView, RoomView, SecretRankingPlayerState, SecretRankingPokemon, SecretRankingPublicState, SecretRankingRoundResult } from '@pokemon-universe/shared';
import { ArrowDown, ArrowUp, Check, Eye, ListChecks, LockKeyhole, Sparkles, Users } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Avatar } from '../components/Avatar';
import { ServerTimer } from '../components/ServerTimer';
import { useServerOffset } from '../hooks/useServerTime';

function member(room: RoomView, playerId: string): RoomMemberView | undefined {
  return room.members.find((candidate) => candidate.id === playerId);
}

function RankingList({ pokemon, interactive = false, onMove }: { pokemon: SecretRankingPokemon[]; interactive?: boolean; onMove?(index: number, direction: -1 | 1): void }) {
  return <ol className="space-y-2" aria-label="Ranking de Pokémon">{pokemon.map((entry, index) => <li key={entry.id} className="flex min-h-24 items-center gap-3 rounded-xl border border-ink/10 bg-surface-raised p-2.5"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-aqua/10 font-display text-xl text-aqua" aria-label={`Posición ${index + 1}`}>{index + 1}</span><span className="grid h-20 w-20 shrink-0 place-items-center rounded-lg bg-ink/[.035]"><img src={entry.sprite} alt="" className="h-20 w-20 object-contain [image-rendering:pixelated]" /></span><strong className="min-w-0 flex-1 truncate text-lg">{entry.name}</strong>{interactive && <span className="flex shrink-0 gap-1"><button type="button" className="icon-button !min-h-10 !min-w-10" disabled={index === 0} aria-label={`Subir ${entry.name}`} onClick={() => onMove?.(index, -1)}><ArrowUp size={18} /></button><button type="button" className="icon-button !min-h-10 !min-w-10" disabled={index === pokemon.length - 1} aria-label={`Bajar ${entry.name}`} onClick={() => onMove?.(index, 1)}><ArrowDown size={18} /></button></span>}</li>)}</ol>;
}

function SubmissionStatus({ room, game }: { room: RoomView; game: SecretRankingPublicState }) {
  const submitted = new Set(game.submittedPlayerIds);
  return <aside className="rounded-2xl border border-ink/10 bg-surface p-4 shadow-card" aria-labelledby="secret-ranking-status"><div className="mb-3 flex items-center gap-2"><Users className="text-aqua" size={20} /><h2 id="secret-ranking-status" className="font-display text-xl">Rankings recibidos</h2></div><div className="space-y-2">{room.members.filter((person) => game.scores[person.id] !== undefined).map((person) => <div key={person.id} className="flex items-center gap-2 rounded-xl bg-surface-raised p-2.5"><Avatar name={person.displayName} avatar={person.avatar} presence={person.presence} size="sm" /><strong className="min-w-0 flex-1 truncate">{person.displayName}</strong>{submitted.has(person.id) ? <span className="inline-flex items-center gap-1 text-sm font-extrabold text-leaf"><Check size={16} /> Listo</span> : <span className="text-sm font-bold text-ink/55">Ordenando…</span>}</div>)}</div><p className="mt-3 flex items-start gap-2 text-sm font-bold text-ink/60"><LockKeyhole className="mt-0.5 shrink-0 text-electric" size={16} />Solo se muestra quién ha terminado; los órdenes permanecen secretos hasta el reveal.</p></aside>;
}

function ConsensusList({ result }: { result: SecretRankingRoundResult }) {
  return <ol className="space-y-2">{result.consensus.map((entry, index) => <li key={entry.pokemon.id} className="flex min-h-24 items-center gap-3 rounded-xl bg-surface-raised p-2.5"><strong className="grid h-10 w-10 place-items-center rounded-lg bg-electric/10 font-display text-xl text-electric">{index + 1}</strong><img src={entry.pokemon.sprite} alt="" className="h-20 w-20 object-contain [image-rendering:pixelated]" /><span className="min-w-0 flex-1"><strong className="block truncate text-lg">{entry.pokemon.name}</strong><small className="font-bold text-ink/55">Posición media {entry.averagePosition.toFixed(2)}</small></span></li>)}</ol>;
}

function RoundReveal({ room, game, serverOffset }: { room: RoomView; game: SecretRankingPublicState; serverOffset: number }) {
  const result = game.lastRound!;
  const standings = Object.entries(result.players).sort(([, left], [, right]) => (left.position ?? Infinity) - (right.position ?? Infinity));
  return <section className="page-shell"><header className="mb-4 flex flex-wrap items-start justify-between gap-3 rounded-2xl border border-ink/10 bg-surface p-4 shadow-card"><div><span className="label !mb-0">Ronda {game.roundNumber} de {game.totalRounds} · Reveal</span><h1 className="font-display text-2xl sm:text-3xl">{result.prompt}</h1></div><ServerTimer deadline={game.nextTransitionAt} serverOffset={serverOffset} label="Siguiente ronda" /></header><div className="grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_24rem]"><main className="space-y-4"><section className="rounded-2xl border border-electric/25 bg-surface p-4 shadow-card sm:p-5" aria-labelledby="group-consensus"><div className="mb-4 flex items-center gap-2"><Sparkles className="text-electric" /><div><h2 id="group-consensus" className="font-display text-2xl">Ranking promedio del grupo</h2><p className="text-sm font-bold text-ink/60">Este orden visual usa todos los rankings enviados.</p></div></div>{result.consensus.length ? <ConsensusList result={result} /> : <div className="empty-state">Nadie completó el ranking a tiempo.</div>}</section><details className="rounded-2xl border border-ink/10 bg-surface p-4 shadow-card"><summary className="cursor-pointer font-display text-xl">Ver todos los rankings revelados</summary><div className="mt-4 grid gap-4 md:grid-cols-2">{Object.entries(result.players).map(([playerId, player]) => { const person = member(room, playerId); return <section key={playerId} className="rounded-xl bg-surface-raised/70 p-3"><h3 className="mb-2 flex items-center gap-2 font-display"><Avatar name={person?.displayName ?? playerId} avatar={person?.avatar} size="sm" />{person?.displayName ?? playerId}</h3>{player.ranking ? <RankingList pokemon={player.ranking} /> : <p className="empty-state !p-4 text-sm">No envió ranking.</p>}</section>; })}</div></details></main><aside className="rounded-2xl border border-ink/10 bg-surface p-4 shadow-card xl:sticky xl:top-4"><h2 className="mb-3 font-display text-xl">Cercanía de la ronda</h2><div className="space-y-2">{standings.map(([playerId, player]) => { const person = member(room, playerId); return <article key={playerId} className={`flex items-center gap-2 rounded-xl p-3 ${player.position === 1 ? 'bg-electric/[.09]' : 'bg-surface-raised'}`}><strong className="w-8 text-center text-lg">{player.position === 1 ? '🏆' : player.position ?? '—'}</strong><Avatar name={person?.displayName ?? playerId} avatar={person?.avatar} size="sm" /><span className="min-w-0 flex-1"><strong className="block truncate">{person?.displayName ?? playerId}</strong><small className="font-bold text-ink/55">{player.distance === null ? 'Sin ranking' : `Distancia ${player.distance.toFixed(2)}`}</small></span><strong className="text-leaf">+{player.pointsAwarded}</strong></article>; })}</div></aside></div></section>;
}

export function SecretRankingGame({ room, onAction }: { room: RoomView; selfId: string; onAction(action: unknown): Promise<void> }) {
  const game = room.game as SecretRankingPublicState;
  const player = room.gamePlayerState as SecretRankingPlayerState;
  const serverOffset = useServerOffset(room.serverNow);
  const [order, setOrder] = useState<SecretRankingPokemon[]>(game.pokemon);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const boardKey = useMemo(() => game.pokemon.map((pokemon) => pokemon.id).join('|'), [game.pokemon]);
  useEffect(() => { setOrder(game.pokemon); setBusy(false); setError(''); }, [game.roundNumber, boardKey]);
  if (game.phase === 'ROUND_RESULTS' && game.lastRound) return <RoundReveal room={room} game={game} serverOffset={serverOffset} />;
  const visibleOrder = player.role === 'PLAYER' && player.ownRanking ? player.ownRanking : order;
  const move = (index: number, direction: -1 | 1) => setOrder((current) => { const next = [...current]; const target = index + direction; [next[index], next[target]] = [next[target]!, next[index]!]; return next; });
  const submit = async () => { if (busy || !player.canSubmit) return; setBusy(true); setError(''); try { await onAction({ type: 'SUBMIT_RANKING', pokemonIds: order.map((pokemon) => pokemon.id) }); } catch (caught) { setError(caught instanceof Error ? caught.message : 'No se pudo enviar tu ranking.'); setBusy(false); } };
  return <section className="page-shell"><header className="mb-4 flex flex-wrap items-start justify-between gap-3 rounded-2xl border border-ink/10 bg-surface p-4 shadow-card"><div><span className="label !mb-0">Ronda {game.roundNumber} de {game.totalRounds}</span><h1 className="font-display text-2xl sm:text-3xl">Secret Ranking</h1></div><ServerTimer deadline={game.roundEndsAt} serverOffset={serverOffset} label="Para ordenar" /></header><div className="grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_22rem]"><main className="rounded-2xl border border-aqua/20 bg-surface p-4 shadow-card sm:p-6"><div className="mx-auto max-w-2xl"><div className="mb-5 text-center"><ListChecks className="mx-auto text-aqua" size={34} /><p className="mt-2 text-sm font-extrabold text-aqua">Ordena según esta pregunta</p><h2 className="font-display text-2xl sm:text-3xl">{game.prompt}</h2><p className="mt-2 font-bold text-ink/60">Tu posición 1 debe ser la que mejor encaja con el primer extremo.</p></div><RankingList pokemon={visibleOrder} interactive={player.role === 'PLAYER' && player.canSubmit} onMove={move} />{player.role === 'PLAYER' && player.canSubmit ? <div className="mt-4"><button type="button" className="btn-primary w-full" disabled={busy || order.length !== 5} onClick={() => void submit()}><LockKeyhole size={18} />{busy ? 'Enviando…' : 'Bloquear ranking'}</button><p className="mt-2 text-center text-sm font-bold text-ink/55">Después de enviarlo no podrás cambiar el orden.</p>{error && <p className="status-error mt-3" role="alert">{error}</p>}</div> : player.role === 'PLAYER' && player.ownRanking ? <div className="mt-4 rounded-xl bg-leaf/[.08] p-4 text-center text-leaf"><Check className="mx-auto" /><strong className="mt-1 block">Ranking bloqueado</strong><p className="text-sm font-bold">Esperando a los demás jugadores.</p></div> : <div className="mt-4 rounded-xl bg-ink/[.04] p-4 text-center"><Eye className="mx-auto text-aqua" /><strong className="mt-1 block">Estás observando</strong><p className="text-sm font-bold text-ink/60">Los rankings se revelarán al cerrar la ronda.</p></div>}</div></main><SubmissionStatus room={room} game={game} /></div></section>;
}
