import type { RoomView, SketchmonPublicState } from '@pokemon-universe/shared';
import { Images, Palette, RotateCcw, StopCircle } from 'lucide-react';
import { Avatar } from '../components/Avatar';
import { SketchmonCanvasSurface } from './SketchmonCanvas';

export function SketchmonResults({ room, selfId, onLobby, onEnd }: { room: RoomView; selfId: string; onLobby(): void; onEnd(): void }) {
  const game = room.game as SketchmonPublicState; const host = room.hostId === selfId;
  return <section className="mx-auto max-w-6xl px-3 py-8 sm:px-5"><div className="rounded-2xl border border-ink/10 bg-surface p-4 shadow-card sm:p-7"><Palette className="mx-auto text-berry" size={50} /><span className="label mt-2 text-center">Sketchmon · Resultados</span><h1 className="mb-2 text-center font-display text-3xl sm:text-4xl">La galería de la partida</h1><p className="mx-auto mb-6 max-w-xl text-center font-bold text-ink/60">Puntos por reconocer rápido los dibujos y por conseguir que el grupo entienda los tuyos.</p>
    <div className="space-y-2.5">{game.results?.standings.map((entry) => { const member = room.members.find((candidate) => candidate.id === entry.playerId); return <article key={entry.playerId} className={`grid items-center gap-3 rounded-xl border p-3 sm:grid-cols-[auto_auto_1fr_auto] ${entry.position === 1 ? 'border-electric/45 bg-electric/[.07]' : 'border-ink/10 bg-surface-raised/70'}`}><strong className="w-9 text-center font-display text-2xl">{entry.position <= 3 ? ['🥇', '🥈', '🥉'][entry.position - 1] : entry.position}</strong><Avatar name={member?.displayName ?? entry.playerId} avatar={member?.avatar} size="md" /><div className="min-w-0"><strong className="block truncate font-display text-xl">{member?.displayName ?? entry.playerId}</strong><p className="text-sm font-bold text-ink/65">{entry.stats.guessedPokemon ?? 0} adivinados · {entry.stats.firstTry ?? 0} al primer intento · {entry.stats.drawingSuccesses ?? 0}/{entry.stats.drawingRounds ?? 0} dibujos descubiertos</p><div className="mt-1 flex flex-wrap gap-1.5 text-xs font-extrabold"><span className="rounded-full bg-leaf/10 px-2 py-0.5 text-leaf">+{entry.stats.pointsFromGuessing ?? 0} adivinando</span><span className="rounded-full bg-aqua/10 px-2 py-0.5 text-aqua">+{entry.stats.pointsFromDrawing ?? 0} dibujando</span></div></div><strong className="justify-self-end text-xl text-berry">{entry.points} pts</strong></article>; })}</div>
    <section className="mt-8 border-t border-ink/10 pt-6" aria-labelledby="sketchmon-gallery"><div className="mb-4 flex items-center gap-2"><Images className="text-aqua" /><div><span className="label !mb-0">Recuerdos de la sesión</span><h2 id="sketchmon-gallery" className="font-display text-2xl">Los dibujos de la partida</h2></div></div>{game.gallery.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{game.gallery.map((entry) => { const drawer = room.members.find((candidate) => candidate.id === entry.drawerId); return <article key={entry.roundNumber} className="overflow-hidden rounded-xl border border-ink/10 bg-surface-raised"><div className="bg-white"><SketchmonCanvasSurface strokes={entry.drawing} label={`Dibujo de ${entry.pokemon.name} por ${drawer?.displayName ?? entry.drawerId}`} /></div><div className="flex items-center gap-3 p-3"><img src={entry.pokemon.sprite} alt="" className="h-12 w-12 object-contain [image-rendering:pixelated]" /><div className="min-w-0 flex-1"><strong className="block truncate font-display text-lg">{entry.pokemon.name}</strong><p className="truncate text-sm font-bold text-ink/60">de {drawer?.displayName ?? entry.drawerId} · Vuelta {entry.lapNumber}</p></div>{entry.winnerId ? <span className="text-xs font-black text-leaf">ADIVINADO</span> : <span className="text-xs font-black text-berry">SIN ACIERTO</span>}</div></article>; })}</div> : <div className="empty-state">No se pudo completar ningún dibujo en esta partida.</div>}</section>
    {host ? <div className="mt-7 flex flex-wrap justify-center gap-3"><button className="btn-primary" onClick={onLobby}><RotateCcw /> Continuar sesión</button><button className="btn-ghost" onClick={onEnd}><StopCircle /> Terminar sesión</button></div> : <p className="mt-6 text-center font-bold text-ink/65">Esperando a que el host continúe la sesión…</p>}</div></section>;
}
