import { POKEMON_TYPES, type Pokemon, type PokemonType, type RoomView, type TypeDuelPlayerState, type TypeDuelPublicState } from '@pokemon-universe/shared';
import { Check, Clock3, Eye, Search, Swords, X } from 'lucide-react';
import { useDeferredValue, useEffect, useMemo, useState } from 'react';
import { api } from '../lib/api'; import { searchPokemonOptions } from './pokemon-search';
const typeLabels: Record<PokemonType, string> = { normal: 'Normal', fire: 'Fuego', water: 'Agua', electric: 'Eléctrico', grass: 'Planta', ice: 'Hielo', fighting: 'Lucha', poison: 'Veneno', ground: 'Tierra', flying: 'Volador', psychic: 'Psíquico', bug: 'Bicho', rock: 'Roca', ghost: 'Fantasma', dragon: 'Dragón', dark: 'Siniestro', steel: 'Acero', fairy: 'Hada' };
function useNow() { const [now, setNow] = useState(Date.now()); useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 100); return () => clearInterval(timer); }, []); return now; }
export function TypeDuelGame({ room, onAction }: { room: RoomView; selfId: string; onAction(action: unknown): Promise<void> }) {
  const game = room.game as TypeDuelPublicState; const player = room.gamePlayerState as TypeDuelPlayerState; const members = useMemo(() => new Map(room.members.map((m) => [m.id, m])), [room.members]); const now = useNow(); const offset = useMemo(() => room.serverNow - Date.now(), [room.serverNow]); const remaining = Math.max(0, Math.ceil(((game.roundEndsAt ?? game.nextTransitionAt ?? 0) - (now + offset)) / 1000));
  const generations = (room.selectedGameConfig as { generations: number[] }).generations; const [pokemon, setPokemon] = useState<Pokemon[]>([]); const [query, setQuery] = useState(''); const deferred = useDeferredValue(query); const results = useMemo(() => searchPokemonOptions(pokemon, deferred), [pokemon, deferred]); const [pending, setPending] = useState(false); const [error, setError] = useState('');
  useEffect(() => { void api<{ pokemon: Pokemon[] }>(`/pokemon?generations=${generations.join(',')}`).then((body) => setPokemon(body.pokemon)); }, [generations.join(',')]);
  useEffect(() => { setQuery(''); setError(''); }, [game.phase, game.roundNumber]);
  const names = game.participants.map((id) => members.get(id)?.displayName ?? id); const cooldownMs = Math.max(0, player.cooldownUntil - (now + offset));
  async function act(action: unknown) { setPending(true); setError(''); try { await onAction(action); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Acción rechazada'); } finally { setPending(false); } }
  return <section className="mx-auto max-w-7xl px-4 py-6"><header className="mb-5 flex flex-wrap items-end justify-between"><div><span className="label">Ronda {game.roundNumber} de {game.totalRounds}</span><h1 className="font-display text-3xl"><Swords className="mr-2 inline text-berry" />{names[0]} VS {names[1]}</h1></div><span className="chip text-lg"><Clock3 /> {remaining}s</span></header>
    {game.phase === 'SELECTING_TYPES' && <div className="card text-center"><h2 className="font-display text-2xl">Elegid un tipo en secreto</h2><div className="my-4 flex justify-center gap-4">{game.participants.map((id) => <span key={id} className="chip">{members.get(id)?.displayName} {game.typeSelectionCompletedIds.includes(id) ? '✓' : '…'}</span>)}</div>{player.canSelectType ? <div className="mx-auto grid max-w-4xl grid-cols-3 gap-2 sm:grid-cols-6">{POKEMON_TYPES.map((type) => <button key={type} disabled={pending} onClick={() => void act({ type: 'SELECT_TYPE', pokemonType: type })} className="rounded-xl border-2 border-ink/10 bg-surface-raised p-2 font-bold hover:border-aqua">{typeLabels[type]}</button>)}</div> : player.ownType ? <p className="font-extrabold text-leaf"><Check className="mr-2 inline" />Elegiste {typeLabels[player.ownType]}. El tipo rival sigue oculto.</p> : <p className="font-bold text-ink/45"><Eye className="mr-2 inline" />Estás observando la selección.</p>}</div>}
    {(game.phase === 'TYPE_REVEAL' || game.phase === 'INVALID_COMBINATION' || game.phase === 'POKEMON_SEARCH') && <div className={`mb-5 rounded-2xl border-2 p-4 text-center ${game.phase === 'INVALID_COMBINATION' ? 'border-berry bg-berry/10' : 'border-aqua bg-aqua/10'}`}><div className="flex flex-wrap justify-center gap-5 text-xl font-display">{game.participants.map((id) => <span key={id}>{members.get(id)?.displayName} → {typeLabels[game.revealedTypes[id]!]}</span>)}</div>{game.phase === 'INVALID_COMBINATION' ? <p className="mt-2 font-extrabold text-berry">No existe ningún Pokémon válido. Los mismos jugadores elegirán de nuevo.</p> : <p className="mt-2 font-bold">Objetivo exacto: {game.requiredTypes?.map((type) => typeLabels[type]).join(' + ')}</p>}</div>}
    {game.phase === 'POKEMON_SEARCH' && <div className="grid gap-5 lg:grid-cols-[1fr_340px]"><div>{player.participant ? <div className="card !p-4"><label className="relative block"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-ink/35" /><input className="field pl-12" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar Pokémon…" autoComplete="off" /></label>{cooldownMs > 0 && <p className="mt-2 font-bold text-electric">Espera {(cooldownMs / 1000).toFixed(1)}s antes de volver a intentar.</p>}<div className="mt-3 grid max-h-[390px] gap-2 overflow-y-auto sm:grid-cols-2">{results.map((entry) => <button key={entry.id} disabled={pending || cooldownMs > 0} onClick={() => void act({ type: 'ATTEMPT_POKEMON', pokemonId: entry.id })} className="flex items-center gap-3 rounded-xl border-2 border-ink/10 bg-surface-raised p-2 text-left hover:border-aqua"><img className="h-12 w-12 object-contain" src={entry.sprite} alt="" /><strong>{entry.name}</strong></button>)}</div></div> : <div className="card grid min-h-64 place-items-center text-center"><div><Eye className="mx-auto text-aqua" size={44} /><h2 className="font-display text-2xl">Observas este duelo</h2></div></div>}</div><AttemptHistory game={game} names={members} /></div>}
    {game.phase === 'ROUND_RESULTS' && <div className="grid gap-5 md:grid-cols-2"><div className="card text-center"><h2 className="font-display text-3xl">{game.lastRound?.reason === 'WINNER' ? `${members.get(game.lastRound.winnerId!)?.displayName} gana +5` : game.lastRound?.reason === 'TIMEOUT' ? 'Tiempo agotado' : 'Selección cancelada'}</h2>{game.lastRound?.solutions.length ? <div className="mt-4"><span className="label">Podíais haber dicho</span><div className="flex justify-center gap-3">{game.lastRound.solutions.map((solution) => <div key={solution.id}><img className="h-20 w-20 object-contain" src={solution.sprite} alt="" /><strong>{solution.name}</strong></div>)}</div></div> : null}</div><AttemptHistory game={game} names={members} /></div>}
    {error && <p className="mt-4 rounded-xl bg-berry/10 p-3 text-center font-bold text-berry">{error}</p>}
  </section>;
}
function AttemptHistory({ game, names }: { game: TypeDuelPublicState; names: Map<string, RoomView['members'][number]> }) { return <aside className="card !p-4"><h2 className="mb-3 font-display text-xl">Intentos públicos</h2><div className="space-y-2">{game.attempts.map((attempt, index) => <div key={`${attempt.playerId}-${attempt.attemptedAt}-${index}`} className={`flex items-center gap-2 rounded-xl p-2 ${attempt.correct ? 'bg-leaf/10' : 'bg-berry/10'}`}><img className="h-10 w-10 object-contain" src={attempt.sprite} alt="" /><div className="min-w-0 flex-1"><span className="block truncate text-xs font-bold text-ink/45">{names.get(attempt.playerId)?.displayName} probó</span><strong>{attempt.pokemonName}</strong></div>{attempt.correct ? <Check className="text-leaf" /> : <X className="text-berry" />}</div>)}{game.attempts.length === 0 && <p className="text-sm font-bold text-ink/40">Todavía no hay intentos.</p>}</div></aside>; }
