import { POKEMON_TYPES, type Pokemon, type PokemonType, type RoomView, type TypeDuelPlayerState, type TypeDuelPublicState } from '@pokemon-universe/shared';
import { ArrowRight, Check, Clock3, Eye, Hourglass, LockKeyhole, Search, Swords, Target, Trophy, X, Zap } from 'lucide-react';
import { useDeferredValue, useEffect, useMemo, useState } from 'react';
import { api } from '../lib/api'; import { searchPokemonOptions } from './pokemon-search';
const typeLabels: Record<PokemonType, string> = { normal: 'Normal', fire: 'Fuego', water: 'Agua', electric: 'Eléctrico', grass: 'Planta', ice: 'Hielo', fighting: 'Lucha', poison: 'Veneno', ground: 'Tierra', flying: 'Volador', psychic: 'Psíquico', bug: 'Bicho', rock: 'Roca', ghost: 'Fantasma', dragon: 'Dragón', dark: 'Siniestro', steel: 'Acero', fairy: 'Hada' };
const typeVisuals: Record<PokemonType, { icon: string; color: string }> = {
  normal: { icon: '◉', color: '#a8a77a' },
  fire: { icon: '🔥', color: '#ee8130' },
  water: { icon: '💧', color: '#6390f0' },
  electric: { icon: '⚡', color: '#f7d02c' },
  grass: { icon: '🍃', color: '#7ac74c' },
  ice: { icon: '❄️', color: '#96d9d6' },
  fighting: { icon: '✊', color: '#c22e28' },
  poison: { icon: '☠️', color: '#a33ea1' },
  ground: { icon: '⛰️', color: '#e2bf65' },
  flying: { icon: '🪽', color: '#a98ff3' },
  psychic: { icon: '🔮', color: '#f95587' },
  bug: { icon: '🐛', color: '#a6b91a' },
  rock: { icon: '🪨', color: '#b6a136' },
  ghost: { icon: '👻', color: '#735797' },
  dragon: { icon: '🐉', color: '#6f35fc' },
  dark: { icon: '🌙', color: '#705746' },
  steel: { icon: '⚙️', color: '#b7b7ce' },
  fairy: { icon: '✨', color: '#d685ad' },
};

function TypeBadge({ type }: { type: PokemonType }) {
  const visual = typeVisuals[type];
  return <span className="inline-flex items-center gap-2 rounded-xl border px-3 py-1.5 font-extrabold" style={{ borderColor: `${visual.color}80`, backgroundColor: `${visual.color}1f` }}><span aria-hidden="true">{visual.icon}</span>{typeLabels[type]}</span>;
}
function useNow() { const [now, setNow] = useState(Date.now()); useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 100); return () => clearInterval(timer); }, []); return now; }
export function TypeDuelGame({ room, selfId, onAction }: { room: RoomView; selfId: string; onAction(action: unknown): Promise<void> }) {
  const game = room.game as TypeDuelPublicState; const player = room.gamePlayerState as TypeDuelPlayerState; const members = useMemo(() => new Map(room.members.map((m) => [m.id, m])), [room.members]); const now = useNow(); const offset = useMemo(() => room.serverNow - Date.now(), [room.serverNow]); const remaining = Math.max(0, Math.ceil(((game.roundEndsAt ?? game.nextTransitionAt ?? 0) - (now + offset)) / 1000));
  const generations = (room.selectedGameConfig as { generations: number[] }).generations; const [pokemon, setPokemon] = useState<Pokemon[]>([]); const [query, setQuery] = useState(''); const deferred = useDeferredValue(query); const results = useMemo(() => searchPokemonOptions(pokemon, deferred), [pokemon, deferred]); const [pending, setPending] = useState(false); const [error, setError] = useState('');
  useEffect(() => { void api<{ pokemon: Pokemon[] }>(`/pokemon?generations=${generations.join(',')}&includeForms=true`).then((body) => setPokemon(body.pokemon)); }, [generations.join(',')]);
  useEffect(() => { setQuery(''); setError(''); }, [game.phase, game.roundNumber]);
  const names = game.participants.map((id) => members.get(id)?.displayName ?? id); const cooldownMs = Math.max(0, player.cooldownUntil - (now + offset));
  const roundWinnerName = game.lastRound?.winnerId ? members.get(game.lastRound.winnerId)?.displayName ?? game.lastRound.winnerId : null;
  const winningAttempt = game.lastRound?.attempts.find((attempt) => attempt.correct) ?? null;
  async function act(action: unknown) { setPending(true); setError(''); try { await onAction(action); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Acción rechazada'); } finally { setPending(false); } }
  return <section className="mx-auto max-w-7xl px-4 py-6"><header className="mb-3 flex flex-wrap items-end justify-between gap-3"><div><span className="label">Ronda {game.roundNumber} de {game.totalRounds}</span><h1 className="font-display text-3xl"><Swords className="mr-2 inline text-berry" />{names[0]} VS {names[1]}</h1></div><span className="chip text-lg"><Clock3 /> {remaining}s</span></header>
    <div className="mb-5 h-2 overflow-hidden rounded-full bg-ink/10"><div className="h-full rounded-full bg-gradient-to-r from-berry to-electric transition-[width]" style={{ width: `${Math.min(100, Math.max(4, game.completedRounds / game.totalRounds * 100))}%` }} /></div>
    {game.phase === 'SELECTING_TYPES' && <div className="card text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-berry/15 text-berry"><LockKeyhole size={32} /></div><h2 className="mt-3 font-display text-3xl">Elegid un tipo en secreto</h2><p className="mt-1 font-bold text-ink/45">Las elecciones se revelarán simultáneamente.</p><div className="mx-auto my-5 grid max-w-xl grid-cols-2 gap-3">{game.participants.map((id) => { const complete = game.typeSelectionCompletedIds.includes(id); return <div key={id} className={`flex items-center gap-3 rounded-2xl border-2 p-3 text-left ${complete ? 'border-leaf/35 bg-leaf/10' : 'border-ink/10 bg-surface-raised'}`}><span className="grid h-10 w-10 place-items-center rounded-xl bg-ink/5 font-display font-bold">{members.get(id)?.displayName.slice(0, 1).toUpperCase()}</span><span className="min-w-0 flex-1"><strong className="block truncate">{members.get(id)?.displayName}</strong><small className={`font-extrabold ${complete ? 'text-leaf' : 'text-ink/35'}`}>{complete ? 'Tipo bloqueado ✓' : 'Eligiendo…'}</small></span></div>; })}</div>{player.canSelectType ? <div className="mx-auto grid max-w-5xl grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-6">{POKEMON_TYPES.map((type) => { const visual = typeVisuals[type]; return <button key={type} disabled={pending} aria-label={`Elegir tipo ${typeLabels[type]}`} onClick={() => void act({ type: 'SELECT_TYPE', pokemonType: type })} className="group flex min-h-14 items-center gap-2.5 rounded-xl border-2 px-3 py-2 text-left font-extrabold transition hover:-translate-y-0.5 hover:brightness-125 disabled:cursor-wait disabled:opacity-55" style={{ borderColor: `${visual.color}66`, backgroundColor: `${visual.color}16` }}><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg text-lg" style={{ backgroundColor: `${visual.color}35` }} aria-hidden="true">{visual.icon}</span><span className="truncate">{typeLabels[type]}</span></button>; })}</div> : player.ownType ? <p className="flex flex-wrap items-center justify-center gap-2 font-extrabold text-leaf"><Check /> Elegiste <TypeBadge type={player.ownType} /> El tipo rival sigue oculto.</p> : <p className="font-bold text-ink/45"><Eye className="mr-2 inline" />Estás observando la selección.</p>}</div>}
    {(game.phase === 'TYPE_REVEAL' || game.phase === 'INVALID_COMBINATION' || game.phase === 'POKEMON_SEARCH') && <div className={`mb-5 rounded-2xl border-2 p-4 text-center ${game.phase === 'INVALID_COMBINATION' ? 'border-berry bg-berry/10' : 'border-aqua bg-aqua/10'}`}><div className="flex flex-wrap justify-center gap-5">{game.participants.map((id) => <span key={id} className="flex items-center gap-2 font-display text-xl">{members.get(id)?.displayName} → <TypeBadge type={game.revealedTypes[id]!} /></span>)}</div>{game.phase === 'INVALID_COMBINATION' ? <p className="mt-3 font-extrabold text-berry">No existe ningún Pokémon válido. Los mismos jugadores elegirán de nuevo.</p> : <div className="mt-3 flex flex-wrap items-center justify-center gap-2 font-bold"><span>Objetivo exacto:</span>{game.requiredTypes?.map((type) => <TypeBadge key={type} type={type} />)}</div>}</div>}
    {game.phase === 'POKEMON_SEARCH' && <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px]"><div>{player.participant ? <div className="card !p-4 md:!p-5"><div className="mb-4 flex items-center gap-3 text-left"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-aqua/15 text-aqua"><Target /></span><div><span className="label !mb-0">Carrera activa</span><h2 className="font-display text-2xl">Encuentra la combinación exacta</h2></div></div><label className="relative block"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-aqua" /><input className="field min-h-14 pl-12 text-lg" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Escribe el nombre del Pokémon…" autoComplete="off" autoFocus /></label>{cooldownMs > 0 && <p className="mt-3 flex items-center gap-2 rounded-xl bg-electric/10 p-3 font-bold text-electric"><Hourglass className="animate-pulse" size={18} /> Espera {(cooldownMs / 1000).toFixed(1)}s antes de volver a intentar.</p>} {!deferred.trim() && <div className="grid min-h-40 place-items-center text-center text-ink/35"><div><Zap className="mx-auto mb-2 text-electric" size={34} /><p className="font-extrabold">Busca por nombre y envía tantos intentos como necesites.</p></div></div>}<div className="mt-3 grid max-h-[390px] gap-2 overflow-y-auto sm:grid-cols-2">{results.map((entry) => <button key={entry.id} disabled={pending || cooldownMs > 0} onClick={() => void act({ type: 'ATTEMPT_POKEMON', pokemonId: entry.id })} className="flex min-h-16 items-center gap-3 rounded-xl border-2 border-ink/10 bg-surface-raised p-2 text-left transition hover:border-aqua hover:bg-aqua/5"><img className="h-14 w-14 object-contain" src={entry.sprite} alt="" /><strong>{entry.name}</strong><ArrowRight className="ml-auto text-ink/25" /></button>)}</div></div> : <div className="card grid min-h-64 place-items-center text-center"><div><Eye className="mx-auto text-aqua" size={52} /><h2 className="mt-3 font-display text-2xl">Observas este duelo</h2><p className="mt-1 font-bold text-ink/45">Los intentos aparecerán en directo.</p></div></div>}</div><AttemptHistory game={game} names={members} /></div>}
    {game.phase === 'ROUND_RESULTS' && <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_390px]"><div className="card text-center"><div className={`mx-auto grid h-20 w-20 place-items-center rounded-full ${roundWinnerName ? 'bg-electric/20 text-electric' : 'bg-ink/5 text-ink/45'}`}>{roundWinnerName ? <Trophy size={42} /> : <Hourglass size={38} />}</div><span className="label mt-3">Resultado del duelo</span><h2 className="font-display text-4xl">{roundWinnerName ? `${roundWinnerName} gana` : game.lastRound?.reason === 'TIMEOUT' ? 'Tiempo agotado' : 'Selección cancelada'}</h2>{roundWinnerName && <span className="mt-2 inline-flex rounded-full bg-leaf/15 px-4 py-1.5 font-display text-xl font-bold text-leaf">+5 puntos</span>}{winningAttempt && <div className="mx-auto mt-5 flex max-w-md items-center justify-center gap-5 rounded-3xl border-2 border-leaf/30 bg-leaf/10 p-4 text-left"><img className="h-32 w-32 object-contain drop-shadow-lg" src={winningAttempt.sprite} alt={winningAttempt.pokemonName} /><div><span className="label !mb-0">Respuesta ganadora</span><strong className="block font-display text-2xl">{winningAttempt.pokemonName}</strong><span className="text-sm font-extrabold text-leaf">✓ Combinación válida</span></div></div>}{game.lastRound?.reason === 'TYPE_FORFEIT' && <p className="mt-3 font-bold text-electric">El rival no eligió un tipo antes de que terminara el tiempo.</p>}{game.lastRound?.solutions.length ? <div className="mt-6"><span className="label">{game.lastRound.reason === 'WINNER' ? 'También podíais haber elegido' : 'Podíais haber elegido'}</span><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{game.lastRound.solutions.map((solution) => <div key={solution.id} className="rounded-2xl border border-ink/10 bg-surface-raised p-2 transition hover:border-aqua/40"><img className="mx-auto h-24 w-24 object-contain" src={solution.sprite} alt="" /><strong className="block truncate text-sm">{solution.name}</strong></div>)}</div></div> : null}<div className="mt-6 flex flex-col items-center gap-2 border-t border-ink/10 pt-5"><p className="font-bold text-ink/45">Siguiente ronda en {remaining}s</p>{selfId === room.hostId && <button className="btn-primary" disabled={pending} onClick={() => void act({ type: 'CONTINUE' })}>{game.completedRounds >= game.totalRounds ? 'Ver clasificación' : 'Siguiente ronda'} <ArrowRight size={18} /></button>}</div></div><AttemptHistory game={game} names={members} large /></div>}
    {error && <p className="mt-4 rounded-xl bg-berry/10 p-3 text-center font-bold text-berry">{error}</p>}
  </section>;
}
function AttemptHistory({ game, names, large = false }: { game: TypeDuelPublicState; names: Map<string, RoomView['members'][number]>; large?: boolean }) { return <aside className="card !p-4"><div className="mb-3 flex items-center justify-between"><h2 className="font-display text-xl">Intentos públicos</h2><span className="chip">{game.attempts.length}</span></div><div className="space-y-2">{game.attempts.map((attempt, index) => <div key={`${attempt.playerId}-${attempt.attemptedAt}-${index}`} className={`flex items-center gap-3 rounded-2xl border p-3 ${attempt.correct ? 'border-leaf/25 bg-leaf/10' : 'border-berry/20 bg-berry/10'}`}><img className={`${large ? 'h-20 w-20' : 'h-14 w-14'} shrink-0 object-contain`} src={attempt.sprite} alt="" /><div className="min-w-0 flex-1"><span className="block truncate text-xs font-bold text-ink/45">{names.get(attempt.playerId)?.displayName} probó</span><strong className={`${large ? 'text-lg' : ''} block truncate`}>{attempt.pokemonName}</strong><span className={`text-xs font-extrabold ${attempt.correct ? 'text-leaf' : 'text-berry'}`}>{attempt.correct ? 'Combinación válida' : 'No coincide con los tipos'}</span></div>{attempt.correct ? <Check className="shrink-0 text-leaf" size={large ? 26 : 20} /> : <X className="shrink-0 text-berry" size={large ? 26 : 20} />}</div>)}{game.attempts.length === 0 && <div className="grid min-h-28 place-items-center rounded-2xl border border-dashed border-ink/10 text-center"><div><Search className="mx-auto mb-2 text-ink/25" /><p className="text-sm font-bold text-ink/40">Todavía no hay intentos.</p></div></div>}</div></aside>; }
