import type { WhoIsWhoPlayerState, WhoIsWhoPublicState, WhoIsWhoTeam, RoomView } from '@pokemon-universe/shared';
import { Eye, Flag, MousePointer2, Target } from 'lucide-react';
import type { PointerEvent } from 'react';
import { useEffect, useState } from 'react';
import { Avatar } from '../components/Avatar';
import { ServerTimer } from '../components/ServerTimer';
import { useServerOffset } from '../hooks/useServerTime';

const teamName: Record<WhoIsWhoTeam, string> = { BLUE: 'Equipo Azul', RED: 'Equipo Rojo' };
const teamClass: Record<WhoIsWhoTeam, string> = { BLUE: 'text-aqua', RED: 'text-berry' };
export function WhoIsWhoPokemonGame({ room, selfId, onAction }: { room: RoomView; selfId: string; onAction(action: unknown): Promise<void> }) {
  const game = room.game as WhoIsWhoPublicState; const player = room.gamePlayerState as WhoIsWhoPlayerState; const offset = useServerOffset(room.serverNow); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [guessing, setGuessing] = useState(false);
  const send = async (action: unknown) => { if (busy) return; setBusy(true); setError(''); try { await onAction(action); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Acción rechazada.'); } finally { setBusy(false); } };
  useEffect(() => () => { void onAction({ type: 'CLEAR_CURSOR' }).catch(() => undefined); }, [onAction]);
  const moveCursor = (event: PointerEvent<HTMLDivElement>) => { const rect = event.currentTarget.getBoundingClientRect(); void onAction({ type: 'UPDATE_CURSOR', x: Math.max(0, Math.min(1, (event.clientX - rect.left) / rect.width)), y: Math.max(0, Math.min(1, (event.clientY - rect.top) / rect.height)) }).catch(() => undefined); };
  const members = (team: WhoIsWhoTeam) => game.teams[team].playerIds.map((id) => room.members.find((member) => member.id === id)).filter(Boolean);
  const discarded = new Set(player.discardedPokemonIds); const active = game.phase === 'TURN_ACTIVE';
  return <section className="page-shell max-w-[96rem]"><header className="panel mb-4 flex flex-wrap items-center justify-between gap-3 px-4 py-3 sm:px-5"><div><span className="label !mb-0">Ronda {game.roundNumber} / {game.totalRounds} · Turno {game.turnNumber}</span><h1 className="font-display text-2xl sm:text-3xl">Quién es Quién — Pokémon</h1></div><ServerTimer deadline={game.roundEndsAt} serverOffset={offset} label="Turno" /></header>
    <div className="mb-4 grid gap-3 md:grid-cols-2">{(['BLUE', 'RED'] as WhoIsWhoTeam[]).map((team) => <section key={team} className={`rounded-xl border border-ink/10 bg-surface p-3 ${player.team === team ? 'ring-2 ring-aqua/30' : ''}`}><div className="flex items-center gap-2"><Flag className={teamClass[team]} size={18} /><strong className={`font-display text-lg ${teamClass[team]}`}>{teamName[team]}</strong><span className="chip ml-auto">{members(team).length} jugadores</span></div><div className="mt-2 flex flex-wrap gap-2">{members(team).map((member) => <span key={member!.id} className="inline-flex items-center gap-1 text-sm font-bold"><Avatar name={member!.displayName} avatar={member!.avatar} size="xs" />{member!.displayName}</span>)}</div>{player.team === team && player.ownSecret && <p className="mt-2 flex items-center gap-2 rounded-lg bg-electric/10 p-2 text-sm font-extrabold text-electric">Tu secreto: <strong>{player.ownSecret.name}</strong></p>}</section>)}</div>
    <div className="grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_20rem]"><main className="panel p-3 sm:p-5"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><strong className={`font-display text-xl ${teamClass[game.currentTeam]}`}>{active ? `Turno del ${teamName[game.currentTeam]}` : 'Partida finalizada'}</strong><p className="text-sm font-bold text-ink/60">Haz las preguntas por voz y pulsa las cartas para descartarlas o restaurarlas.</p></div>{player.team && <span className="chip"><MousePointer2 size={15} /> Cursores del equipo</span>}</div>
      <div onPointerMove={moveCursor} onPointerLeave={() => void onAction({ type: 'CLEAR_CURSOR' }).catch(() => undefined)} className="relative grid gap-2" style={{ gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 7rem), 1fr))' }}>{game.board.map((pokemon) => { const isDiscarded = discarded.has(pokemon.id); return <button type="button" key={pokemon.id} disabled={!player.canAct} onClick={() => guessing ? void send({ type: 'GUESS_POKEMON', pokemonId: pokemon.id }).then(() => setGuessing(false)) : void send({ type: 'TOGGLE_DISCARD', pokemonId: pokemon.id })} className={`relative min-h-28 rounded-xl border p-2 text-center transition ${isDiscarded ? 'border-ink/10 bg-ink/[.035] opacity-35 grayscale' : 'border-ink/10 bg-surface-raised hover:border-aqua/60'} ${guessing ? 'ring-2 ring-electric/40' : ''} disabled:cursor-default`}><img src={pokemon.sprite} alt="" className="mx-auto h-16 w-16 object-contain [image-rendering:pixelated]" /><strong className="block truncate text-sm">{pokemon.name}</strong>{isDiscarded && <span className="absolute inset-0 grid place-items-center text-3xl font-black text-berry/80">×</span>}{guessing && <span className="absolute bottom-1 left-1/2 -translate-x-1/2 rounded bg-night px-1 text-[9px] font-black text-white">Elegir</span>}</button>; })}{Object.entries(player.cursors).filter(([id]) => id !== selfId).map(([id, cursor]) => <span key={id} className="pointer-events-none absolute z-10" style={{ left: `${cursor.x * 100}%`, top: `${cursor.y * 100}%` }}><MousePointer2 className="fill-electric text-night drop-shadow" size={19} /><small className="ml-1 rounded bg-night px-1 text-[10px] font-black text-white">{room.members.find((member) => member.id === id)?.displayName ?? 'Compañero'}</small></span>)}</div>
      <div className="mt-4 flex flex-wrap gap-2">{player.canGuess && <button type="button" className="btn-primary" disabled={busy} onClick={() => setGuessing((value) => !value)}><Target size={18} /> {guessing ? 'Cancelar adivinanza' : 'Adivinar Pokémon'}</button>}{player.canAct && <button type="button" className="btn-secondary" disabled={busy || guessing} onClick={() => void send({ type: 'END_TURN' })}>Terminar turno</button>}{guessing && <span className="chip !bg-electric/10 !text-electric">Pulsa cualquier Pokémon del tablero para confirmar</span>}{player.lastGuess?.correct === false && <span className="chip !bg-berry/10 !text-berry">Respuesta incorrecta · turno terminado</span>}{error && <span className="status-error" role="alert">{error}</span>}</div>
    </main><aside className="grid gap-4 xl:sticky xl:top-4"><section className="panel p-4"><h2 className="mb-2 flex items-center gap-2 font-display text-xl"><Eye className="text-aqua" size={19} /> Cómo jugar</h2><p className="text-sm font-bold text-ink/65">El equipo activo pregunta por voz, descarta cartas y puede intentar adivinar una vez. Un fallo termina el turno.</p></section><section className="panel p-4"><h2 className="mb-2 font-display text-xl">Estado</h2><p className={`font-extrabold ${teamClass[game.currentTeam]}`}>{active ? teamName[game.currentTeam] : game.winnerTeam ? `Ganó ${teamName[game.winnerTeam]}` : 'Empate'}</p><p className="mt-1 text-sm font-bold text-ink/60">{player.team ? `Tu equipo conserva ${player.discardedPokemonIds.length} descartes.` : 'Estás observando.'}</p></section></aside></div></section>;
}
