import type { RoomMemberView, RoomView, WouldYouRatherOption, WouldYouRatherPlayerState, WouldYouRatherPublicState, WouldYouRatherRoundResult } from '@pokemon-universe/shared';
import { Check, Eye, LockKeyhole, Send, Sparkles, Users } from 'lucide-react';
import { useState } from 'react';
import { Avatar } from '../components/Avatar';
import { ServerTimer } from '../components/ServerTimer';
import { useServerOffset } from '../hooks/useServerTime';

function member(room: RoomView, playerId: string): RoomMemberView | undefined {
  return room.members.find((candidate) => candidate.id === playerId);
}

function OptionPanel({ letter, text, selected, disabled, onClick }: { letter: WouldYouRatherOption; text: string; selected: boolean; disabled: boolean; onClick(): void }) {
  const selectedStyle = letter === 'A' ? 'border-aqua bg-aqua/10' : 'border-electric bg-electric/10';
  return <button type="button" aria-pressed={selected} disabled={disabled} onClick={onClick} className={`min-h-36 rounded-2xl border p-4 text-left transition-colors sm:min-h-44 sm:p-5 ${selected ? selectedStyle : 'border-ink/10 bg-surface-raised hover:border-aqua/50'}`}><span className={`mb-3 grid h-10 w-10 place-items-center rounded-xl font-display text-xl ${letter === 'A' ? 'bg-aqua text-night' : 'bg-electric text-night'}`}>{letter}</span><strong className="block font-display text-xl leading-tight sm:text-2xl">{text}</strong></button>;
}

function Ballot({ game, player, onSubmit }: { game: WouldYouRatherPublicState; player: WouldYouRatherPlayerState; onSubmit(preference: WouldYouRatherOption, prediction: WouldYouRatherOption): Promise<void> }) {
  const [preference, setPreference] = useState<WouldYouRatherOption | null>(null); const [prediction, setPrediction] = useState<WouldYouRatherOption | null>(null);
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  if (player.role === 'SPECTATOR') return <div className="empty-state"><Eye className="mx-auto mb-2 text-aqua" />Estás observando esta ronda.</div>;
  if (player.ownBallot) return <div className="rounded-2xl border border-leaf/30 bg-leaf/[.07] p-5 text-center"><Check className="mx-auto text-leaf" size={36} /><h2 className="mt-2 font-display text-2xl">Papeleta bloqueada</h2><p className="mt-2 font-bold text-ink/65">Elegiste <strong>{player.ownBallot.preference}</strong> y predijiste <strong>{player.ownBallot.prediction}</strong>. Solo tú puedes verlo hasta el reveal.</p></div>;
  const send = async () => { if (!preference || !prediction || busy) return; setBusy(true); setError(''); try { await onSubmit(preference, prediction); } catch (caught) { setError(caught instanceof Error ? caught.message : 'No se pudo enviar la papeleta.'); setBusy(false); } };
  return <div className="space-y-6"><section aria-labelledby="wyr-preference"><div className="mb-3"><span className="label !mb-0">Paso 1 · Tu decisión</span><h2 id="wyr-preference" className="font-display text-2xl">¿Qué preferirías tú?</h2></div><div className="grid gap-3 md:grid-cols-2"><OptionPanel letter="A" text={game.prompt.optionA} selected={preference === 'A'} disabled={!player.canSubmit || busy} onClick={() => setPreference('A')} /><OptionPanel letter="B" text={game.prompt.optionB} selected={preference === 'B'} disabled={!player.canSubmit || busy} onClick={() => setPreference('B')} /></div></section><section aria-labelledby="wyr-prediction"><div className="mb-3"><span className="label !mb-0">Paso 2 · Lee la sala</span><h2 id="wyr-prediction" className="font-display text-2xl">¿Cuál será la mayoría?</h2><p className="font-bold text-ink/60">Puedes predecir la misma opción que elegiste o la contraria.</p></div><div className="grid grid-cols-2 gap-3"><button type="button" aria-pressed={prediction === 'A'} disabled={!player.canSubmit || busy} onClick={() => setPrediction('A')} className={`min-h-14 rounded-xl border font-display text-lg ${prediction === 'A' ? 'border-aqua bg-aqua/10 text-aqua' : 'border-ink/10 bg-surface-raised'}`}>Mayoría A</button><button type="button" aria-pressed={prediction === 'B'} disabled={!player.canSubmit || busy} onClick={() => setPrediction('B')} className={`min-h-14 rounded-xl border font-display text-lg ${prediction === 'B' ? 'border-electric bg-electric/10 text-electric' : 'border-ink/10 bg-surface-raised'}`}>Mayoría B</button></div></section><button type="button" className="btn-primary w-full justify-center" disabled={!preference || !prediction || busy || !player.canSubmit} onClick={() => void send()}><Send size={18} /> {busy ? 'Enviando…' : 'Bloquear papeleta'}</button>{error && <p className="status-error" role="alert">{error}</p>}</div>;
}

function PlayerProgress({ room, game }: { room: RoomView; game: WouldYouRatherPublicState }) {
  const submitted = new Set(game.submittedPlayerIds);
  return <aside className="rounded-2xl border border-ink/10 bg-surface p-4 shadow-card" aria-labelledby="wyr-progress"><div className="mb-3 flex items-center gap-2"><Users className="text-aqua" /><h2 id="wyr-progress" className="font-display text-xl">Papeletas</h2></div><div className="space-y-2">{game.playerIds.map((playerId) => { const person = member(room, playerId); return <div key={playerId} className="flex min-h-12 items-center gap-2 rounded-xl bg-surface-raised p-2.5"><Avatar name={person?.displayName ?? playerId} avatar={person?.avatar} presence={person?.presence} size="sm" /><strong className="min-w-0 flex-1 truncate">{person?.displayName ?? playerId}</strong>{submitted.has(playerId) ? <span className="inline-flex items-center gap-1 text-sm font-extrabold text-leaf"><Check size={16} /> Lista</span> : <span className="text-sm font-bold text-ink/55">Pensando…</span>}</div>; })}</div><p className="mt-3 flex gap-2 text-sm font-bold text-ink/60"><LockKeyhole className="mt-0.5 shrink-0 text-electric" size={16} />Elección y predicción permanecen secretas hasta el reveal.</p></aside>;
}

function RoundReveal({ room, game, result, serverOffset }: { room: RoomView; game: WouldYouRatherPublicState; result: WouldYouRatherRoundResult; serverOffset: number }) {
  const total = result.totals.A + result.totals.B; const aPercent = total === 0 ? 50 : Math.round(result.totals.A / total * 100);
  return <section className="page-shell"><div className="overflow-hidden rounded-2xl border border-electric/30 bg-surface shadow-card reveal-pop"><header className="flex flex-wrap items-start justify-between gap-3 border-b border-ink/10 p-4 sm:p-6"><div><span className="label !mb-0">Ronda {game.roundNumber} · Reveal</span><h1 className="font-display text-3xl text-electric sm:text-4xl">{result.majority ? `La mayoría eligió ${result.majority}` : 'La sala quedó dividida'}</h1><p className="mt-2 font-bold text-ink/60">{result.majority ? '1 punto por estar en la mayoría y 2 por haberla predicho.' : 'En empate no se reparten puntos de elección ni de predicción.'}</p></div><ServerTimer deadline={game.nextTransitionAt} serverOffset={serverOffset} label="Siguiente ronda" /></header><div className="p-4 sm:p-6"><div className="grid gap-3 md:grid-cols-2"><article className={`rounded-2xl border p-4 ${result.majority === 'A' ? 'border-aqua/50 bg-aqua/[.08]' : 'border-ink/10 bg-surface-raised'}`}><span className="label !mb-1 text-aqua">Opción A · {result.totals.A} votos</span><strong className="block font-display text-xl leading-tight sm:text-2xl">{result.prompt.optionA}</strong></article><article className={`rounded-2xl border p-4 ${result.majority === 'B' ? 'border-electric/50 bg-electric/[.08]' : 'border-ink/10 bg-surface-raised'}`}><span className="label !mb-1 text-electric">Opción B · {result.totals.B} votos</span><strong className="block font-display text-xl leading-tight sm:text-2xl">{result.prompt.optionB}</strong></article></div><div className="mt-4 flex h-3 overflow-hidden rounded-full bg-electric" aria-label={`${aPercent}% eligió A`}><span className="bg-aqua" style={{ width: `${aPercent}%` }} /></div><div className="mt-6 space-y-2">{result.players.map((entry) => { const person = member(room, entry.playerId); return <article key={entry.playerId} className="grid items-center gap-3 rounded-xl border border-ink/10 bg-surface-raised/70 p-3 sm:grid-cols-[auto_1fr_auto]"><Avatar name={person?.displayName ?? entry.playerId} avatar={person?.avatar} size="sm" /><div><strong className="font-display text-lg">{person?.displayName ?? entry.playerId}</strong><p className="text-sm font-bold text-ink/60">Eligió <span className={entry.preference === 'A' ? 'text-aqua' : 'text-electric'}>{entry.preference}</span> · Predijo <span className={entry.prediction === 'A' ? 'text-aqua' : 'text-electric'}>{entry.prediction}</span></p></div><strong className={entry.totalPoints > 0 ? 'text-leaf' : 'text-ink/45'}>+{entry.totalPoints} pts</strong></article>; })}</div>{result.missingPlayerIds.length > 0 && <p className="mt-4 rounded-xl bg-ink/[.04] p-3 text-sm font-bold text-ink/60">Sin papeleta: {result.missingPlayerIds.map((id) => member(room, id)?.displayName ?? id).join(', ')}.</p>}</div></div></section>;
}

export function WouldYouRatherGame({ room, onAction }: { room: RoomView; selfId: string; onAction(action: unknown): Promise<void> }) {
  const game = room.game as WouldYouRatherPublicState; const player = room.gamePlayerState as WouldYouRatherPlayerState; const serverOffset = useServerOffset(room.serverNow);
  if (game.phase === 'ROUND_RESULTS' && game.lastRound) return <RoundReveal room={room} game={game} result={game.lastRound} serverOffset={serverOffset} />;
  return <section className="page-shell"><header className="rounded-2xl border border-ink/10 bg-surface p-4 shadow-card"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="label !mb-0">Ronda {game.roundNumber} de {game.totalRounds}</span><h1 className="font-display text-2xl sm:text-3xl">Would You Rather Pokémon</h1></div><ServerTimer deadline={game.roundEndsAt} serverOffset={serverOffset} label="Para decidir" /></div></header><section className="my-4 rounded-2xl border border-berry/20 bg-berry/[.045] px-4 py-5 text-center shadow-card"><Sparkles className="mx-auto text-berry" /><span className="label mt-2 !mb-0">El dilema</span><h2 className="font-display text-2xl">Elige con sinceridad. Predice con malicia.</h2></section><div className="grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_22rem]"><main className="rounded-2xl border border-ink/10 bg-surface p-4 shadow-card sm:p-5"><Ballot key={game.roundNumber} game={game} player={player} onSubmit={(preference, prediction) => onAction({ type: 'SUBMIT_BALLOT', preference, prediction })} /></main><PlayerProgress room={room} game={game} /></div></section>;
}
