import type { Pokemon, PokemonLegendaryStatus, PokemonType, RoomView, ZoomedPokemonHint, ZoomedPokemonPlayerState, ZoomedPokemonPublicState } from '@pokemon-universe/shared';
import { CheckCircle2, Eye, History, Lightbulb, Search, XCircle, ZoomOut } from 'lucide-react';
import { Avatar } from '../components/Avatar';
import { ServerTimer } from '../components/ServerTimer';
import { usePokemonPool } from '../hooks/usePokemonPool';
import { useRemainingMs, useServerOffset } from '../hooks/useServerTime';
import { PokemonSelector } from './PokemonSelector';

const EMPTY_LOCKED = new Set<string>();
const typeLabels: Record<PokemonType, string> = { normal: 'Normal', fire: 'Fuego', water: 'Agua', electric: 'Eléctrico', grass: 'Planta', ice: 'Hielo', fighting: 'Lucha', poison: 'Veneno', ground: 'Tierra', flying: 'Volador', psychic: 'Psíquico', bug: 'Bicho', rock: 'Roca', ghost: 'Fantasma', dragon: 'Dragón', dark: 'Siniestro', steel: 'Acero', fairy: 'Hada' };
const categoryLabels: Record<PokemonLegendaryStatus, string> = { NORMAL: 'No legendario', LEGENDARY: 'Legendario', MYTHICAL: 'Mítico' };

function hintLabel(hint: ZoomedPokemonHint): string {
  if (hint.kind === 'GENERATION') return `Generación ${hint.value}`;
  if (hint.kind === 'TYPE') return hint.values.map((type) => typeLabels[type]).join(' / ');
  if (hint.kind === 'TYPE_COUNT') return hint.value === 1 ? 'Monotipo' : `${hint.value} tipos`;
  if (hint.kind === 'CATEGORY') return categoryLabels[hint.value];
  if (hint.stages <= 1) return 'No evoluciona'; if (hint.stage === 1) return 'Pokémon base'; if (hint.stage >= hint.stages) return 'Evolución final'; return 'Evolución intermedia';
}

export function ZoomViewport({ source, sourceType, zoom, alt }: { source: string; sourceType: 'SPRITE' | 'ARTWORK'; zoom: number; alt: string }) {
  return <div className="zoomed-viewport relative aspect-square w-full overflow-hidden rounded-2xl border border-aqua/25 bg-night" aria-label={alt} data-source-type={sourceType}><div className="absolute inset-0 bg-[radial-gradient(circle,rgba(82,199,232,.16),transparent_70%)]" /><img src={source} alt="" className="zoomed-image absolute inset-0 h-full w-full object-contain [image-rendering:auto]" style={{ transform: `scale(${zoom})`, transformOrigin: '50% 50%' }} /></div>;
}

function GuessPanel({ pokemon, player, game, serverOffset, participating, loadError, onAction }: { pokemon: Pokemon[]; player: ZoomedPokemonPlayerState; game: ZoomedPokemonPublicState; serverOffset: number; participating: boolean; loadError: string; onAction(action: unknown): Promise<void> }) {
  const cooldownMs = useRemainingMs(player.cooldownUntil, serverOffset);
  if (!participating) return <div className="grid min-h-28 place-items-center rounded-2xl bg-ink/[.04] text-center"><div><Eye className="mx-auto text-aqua" /><strong className="block font-display text-xl">Estás observando</strong><span className="text-sm font-bold text-ink/65">Los espectadores no pueden responder.</span></div></div>;
  if (player.solved) return <div className="reveal-pop grid min-h-32 place-items-center rounded-2xl border border-leaf/30 bg-leaf/[.08] text-center"><div><CheckCircle2 className="mx-auto text-leaf" size={40} /><strong className="block font-display text-2xl text-leaf">¡Has acertado!</strong><span className="font-bold text-ink/70">Eres el {player.solveOrder}º · +{player.roundPoints} pts<br />Esperando al resto…</span></div></div>;
  return <section><div className="mb-2 flex items-end justify-between"><div><span className="label !mb-0">Tu respuesta</span><h2 className="flex items-center gap-2 font-display text-xl"><Search size={19} /> Buscar Pokémon</h2></div><small className="font-bold text-ink/60">{player.attemptCount} intentos</small></div>{player.lastAttempt?.result === 'INCORRECT' && <p className="mb-2 flex justify-between gap-2 rounded-xl bg-berry/[.08] px-3 py-2 text-sm font-extrabold text-berry" role="status"><span>❌ No es ese Pokémon.</span><span>{cooldownMs > 0 ? `Nuevo intento en ${(cooldownMs / 1000).toFixed(1)}s` : 'Ya puedes intentarlo'}</span></p>}{loadError ? <p className="text-berry">{loadError}</p> : <PokemonSelector key={game.roundNumber} pokemon={pokemon} locked={EMPTY_LOCKED} disabled={!player.canGuess} confirmationDisabled={cooldownMs > 0} variant="embedded" autoFocus={false} onSelect={(pokemonId) => onAction({ type: 'GUESS_POKEMON', pokemonId })} />}</section>;
}

function SocialPanels({ room, game }: { room: RoomView; game: ZoomedPokemonPublicState }) {
  return <aside className="grid gap-4 md:grid-cols-2 xl:sticky xl:top-4 xl:grid-cols-1"><section className="rounded-2xl border border-ink/10 bg-surface/85 p-4"><h2 className="mb-3 font-display text-xl">Jugadores</h2><div className="space-y-2">{room.members.map((member) => { const solve = game.solves[member.id]; return <div key={member.id} className="flex items-center gap-2 rounded-xl bg-ink/[.035] p-2"><Avatar name={member.displayName} avatar={member.avatar} presence={member.presence} size="sm" /><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{member.displayName}</strong><small className="font-bold text-ink/55">{game.scores[member.id] ?? 0} pts</small></span>{member.role === 'SPECTATOR' ? <span className="text-xs font-bold text-ink/55">Espectador</span> : solve ? <span className="text-xs font-black text-leaf">✓ Ha acertado</span> : <span className="text-xs font-bold text-ink/60">buscando…</span>}</div>; })}</div></section><section className="rounded-2xl border border-ink/10 bg-surface/85 p-4"><h2 className="mb-3 flex items-center gap-2 font-display text-xl"><History size={20} className="text-berry" /> Intentos recientes</h2>{game.attempts.length ? <div className="max-h-64 space-y-1.5 overflow-y-auto">{game.attempts.slice(-30).reverse().map((attempt, index) => { const member = room.members.find((item) => item.id === attempt.playerId); return <div key={`${attempt.attemptedAt}-${index}`} className="flex items-center gap-2 rounded-xl bg-berry/[.06] p-2 text-sm"><Avatar name={member?.displayName ?? attempt.playerId} avatar={member?.avatar} size="xs" /><strong className="truncate">{member?.displayName}</strong><span className="text-ink/55">→</span><img src={attempt.guessedPokemon.sprite} alt="" className="h-7 w-7 object-contain [image-rendering:auto]" /><span className="min-w-0 flex-1 truncate font-bold">{attempt.guessedPokemon.name}</span><XCircle size={15} className="text-berry" /></div>; })}</div> : <p className="text-center text-sm font-bold text-ink/60">Sin intentos fallidos todavía.</p>}</section></aside>;
}

function RoundReveal({ room, game, serverOffset }: { room: RoomView; game: ZoomedPokemonPublicState; serverOffset: number }) {
  const result = game.lastRound!; const ordered = room.members.filter((member) => member.role === 'PLAYER').sort((a, b) => (result.solves[a.id]?.solveOrder ?? Infinity) - (result.solves[b.id]?.solveOrder ?? Infinity));
  return <section className="mx-auto max-w-6xl px-3 py-5"><div className="rounded-2xl border border-leaf/25 bg-surface/95 p-4 shadow-card sm:p-6"><header className="mb-5 flex items-start justify-between"><div><span className="label">Reveal · Ronda {game.roundNumber}</span><h1 className="font-display text-3xl text-leaf sm:text-5xl">¡Era {result.pokemon.name}!</h1></div><ServerTimer deadline={game.nextTransitionAt} serverOffset={serverOffset} label="Siguiente ronda" /></header><div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_18rem_minmax(18rem,1fr)] lg:items-center"><div><ZoomViewport source={result.initialCropUrl} sourceType={result.imageSourceType} zoom={game.zoomStages[0]!} alt="Recorte inicial" /><strong className="mt-2 block text-center font-display text-xl">Así empezó · Zoom ×{game.zoomStages[0]}</strong></div><div className="text-center"><ZoomOut className="mx-auto text-aqua" size={42} /><span className="font-display text-2xl">zoom out</span></div><div><ZoomViewport source={result.imageUrl} sourceType={result.imageSourceType} zoom={1} alt={`Imagen completa de ${result.pokemon.name}`} /><strong className="mt-2 block text-center font-display text-2xl">{result.pokemon.name}</strong></div></div><div className="mt-6 grid gap-2 sm:grid-cols-2">{ordered.map((member) => { const solve = result.solves[member.id]; return <article key={member.id} className="flex items-center gap-3 rounded-2xl border border-ink/10 bg-ink/[.03] p-3"><strong className="w-8 text-center text-xl">{solve?.solveOrder && solve.solveOrder <= 3 ? ['🥇', '🥈', '🥉'][solve.solveOrder - 1] : solve?.solveOrder ?? '—'}</strong><Avatar name={member.displayName} avatar={member.avatar} size="sm" /><span className="min-w-0 flex-1"><strong className="block truncate">{member.displayName}</strong><small className={solve ? 'font-bold text-leaf' : 'font-bold text-berry'}>{solve ? `Zoom ×${solve.zoom} · bonificación +${solve.zoomBonus}` : 'No acertó'}</small></span><strong>+{solve?.points ?? 0}</strong></article>; })}</div></div></section>;
}

export function ZoomedPokemonGame({ room, selfId, onAction }: { room: RoomView; selfId: string; onAction(action: unknown): Promise<void> }) {
  const game = room.game as ZoomedPokemonPublicState; const player = room.gamePlayerState as ZoomedPokemonPlayerState; const config = room.selectedGameConfig as { generations: number[]; includeForms: boolean; hintsEnabled: boolean };
  const serverOffset = useServerOffset(room.serverNow); const { pokemon, error: loadError } = usePokemonPool({ generations: config.generations, includeForms: config.includeForms });
  if (game.phase === 'ROUND_RESULTS' && game.lastRound) return <RoundReveal room={room} game={game} serverOffset={serverOffset} />;
  const sourceType = game.imageSourceType ?? 'SPRITE'; const zoom = game.zoomStages[game.currentZoomStage] ?? game.zoomStages[0]!; const participating = room.members.find((member) => member.id === selfId)?.role === 'PLAYER';
  return <section className="mx-auto max-w-[90rem] overflow-x-clip px-3 py-4 sm:px-5"><header className="mb-4 flex items-center justify-between gap-3 rounded-2xl border border-ink/10 bg-surface/85 px-4 py-3 shadow-card"><div><span className="label !mb-0">Ronda {game.roundNumber} / {game.totalRounds}</span><h1 className="font-display text-2xl sm:text-3xl">Zoomed Pokémon</h1></div><ServerTimer deadline={game.roundEndsAt} serverOffset={serverOffset} /></header><div className="grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_22rem]"><main className="rounded-2xl border border-ink/10 bg-surface/90 p-4 shadow-card sm:p-6"><h2 className="mb-3 text-center font-display text-2xl">¿Qué Pokémon es?</h2><div className="mx-auto max-w-[36rem]"><ZoomViewport source={game.imageUrl ?? ''} sourceType={sourceType} zoom={zoom} alt="Detalle ampliado del Pokémon misterioso" /><div className="mt-2 flex items-center justify-between gap-3"><strong className="font-display text-xl text-aqua">Zoom ×{zoom}</strong><span className="rounded-full bg-electric/10 px-3 py-1 text-xs font-black uppercase tracking-wider text-electric">Nivel {game.currentZoomStage + 1} · Bonificación +{game.currentZoomBonus} pts</span></div></div>{game.visibleHints.length > 0 && <section className="mx-auto mt-4 max-w-[42rem] rounded-2xl border border-electric/20 bg-electric/[.06] p-3"><strong className="flex items-center gap-2 font-display"><Lightbulb size={18} className="text-electric" /> Pistas</strong><div className="mt-2 flex flex-wrap gap-2">{game.visibleHints.map((hint, index) => <span key={`${hint.kind}-${index}`} className="rounded-full bg-electric/10 px-3 py-1 text-sm font-extrabold text-electric">{hintLabel(hint)}</span>)}</div></section>}<div className="zoomed-answer mx-auto mt-5 max-w-[52rem] border-t border-ink/10 pt-4"><GuessPanel pokemon={pokemon} player={player} game={game} serverOffset={serverOffset} participating={Boolean(participating)} loadError={loadError} onAction={onAction} /></div></main><SocialPanels room={room} game={game} /></div></section>;
}
