import type { WouldYouRatherPromptPair } from '../contracts.js';

const pairs = [
  ['Que Gengar cuente tu historial de búsqueda en una cena familiar', 'Que Mr. Mime lo represente entero con mímica'],
  ['Compartir piso con Snorlax y pagar tú todo el alquiler', 'Compartir piso con Rotom y que controle todos tus electrodomésticos'],
  ['Que Hypno sea tu terapeuta', 'Que Slowpoke sea tu asesor financiero'],
  ['Que Meowth haga tu declaración de la renta', 'Que Psyduck gestione tu hipoteca'],
  ['Tener a Absol avisándote de cada desgracia', 'Tener a Xatu sabiendo exactamente cómo vas a morir'],
  ['Que Banette ordene tu armario cada noche', 'Que Cofagrigus elija el diseño de tu ataúd'],
  ['Trabajar para el Team Rocket con contrato indefinido', 'Ser autónomo y cobrar siempre en Pokédolares'],
  ['Ir a una cita mientras Gardevoir lee tus pensamientos', 'Ir a una entrevista mientras Zoroark suplanta a tu ex'],
  ['Que Haunter te haga cosquillas cada vez que mientes', 'Que Hatterene aparezca cada vez que pierdes la paciencia'],
  ['Dormir abrazado a un Slugma', 'Ducharte siempre con un Cryogonal'],
  ['Tener un Magikarp que habla sin parar', 'Tener un Gengar viviendo dentro de tu armario'],
  ['Que Ditto sustituya a tu jefe durante un mes', 'Que Zoroark sustituya a todos tus compañeros de trabajo'],
  ['Saber el día exacto en que te despedirán gracias a Xatu', 'No volver a entender ninguna indirecta por culpa de Slowpoke'],
  ['Que Mimikyu diseñe tu perfil de citas', 'Que Sableye elija todos tus regalos de aniversario'],
  ['Una cena romántica cocinada por Muk', 'Un desayuno de empresa servido por Garbodor'],
  ['Que Alakazam recuerde cada cosa vergonzosa que has dicho', 'Que Chatot la repita cuando conoce a alguien nuevo'],
  ['Tener a Jigglypuff como vecino con karaoke nocturno', 'Tener a Exploud como despertador sin botón de apagar'],
  ['Que Drowzee revise tus sueños en una pantalla pública', 'Que Rotom publique tus notas del móvil una vez al año'],
  ['Venderle tu alma a Giratina por vacaciones ilimitadas', 'Trabajar los domingos para Arceus por una nómina mediocre'],
  ['Que Greedent controle tu despensa', 'Que Trubbish decida cuándo toca limpiar la casa'],
  ['Llegar a todas partes montado en un Rapidash enfadado', 'Llegar siempre tarde sobre un Slowpoke encantador'],
  ['Tener la suerte de Togepi pero estornudar fuego', 'Tener la fuerza de Machamp pero cuatro veces más agujetas'],
  ['Que Porygon organice tu vida digital', 'Que Klefki guarde todas tus contraseñas'],
  ['Perder una discusión contra un Psyduck', 'Recibir consejos amorosos de un Luvdisc'],
  ['Que Cubone escriba tu discurso de boda', 'Que Spiritomb prepare el brindis'],
  ['Vivir un año en una casa encantada con Litwick', 'Pasar un mes de camping con Parasect'],
  ['Tener un Eevee que cambie de evolución cada lunes', 'Tener un Castform que controle el tiempo según su humor'],
  ['Que Machoke sea tu entrenador personal', 'Que Slaking sea tu coach de productividad'],
  ['Cruzar el océano sobre Lapras', 'Atravesar el cielo agarrado a Drifblim'],
  ['Participar en un concurso de cocina con Scovillain', 'Participar en un karaoke con Meloetta'],
  ['Explorar una cueva con Umbreon', 'Explorar un bosque con Decidueye'],
  ['Tener a Dragonite como repartidor personal', 'Tener a Corviknight como taxi diario'],
  ['Aprender teletransporte con Abra', 'Aprender a respirar bajo el agua con Vaporeon'],
  ['Cuidar una guardería llena de Toxel', 'Organizar una excursión escolar con Impidimp'],
  ['Que Smeargle pinte todas las paredes de tu casa', 'Que Sudowoodo decore todo tu jardín'],
  ['Compartir tus snacks con Munchlax', 'Compartir tu conexión wifi con Porygon-Z'],
] as const;

export const officialWouldYouRatherPrompts: readonly WouldYouRatherPromptPair[] = pairs.map(([optionA, optionB], index) => ({
  id: `would-you-rather-official-${String(index + 1).padStart(2, '0')}`,
  optionA,
  optionB,
}));
