import { describe, expect, it } from 'vitest'; import type { GameContext, GamePlayer, Pokemon, PokemonCatalog, PokemonType, TypeDuelPlayerState, TypeDuelState } from '../../index.js'; import { chooseBalancedPair, isValidPokemonForTypes, typeDuelGame, TYPE_DUEL_ATTEMPT_COOLDOWN_MS, TYPE_DUEL_MAX_SOLUTIONS, TYPE_DUEL_RESULT_MS } from '../../index.js';
const pokemon: Pokemon[] = [
  { id: 'volcanion', name: 'Volcanion', nationalDexNumber: 721, generation: 6, sprite: '/v.png', hp: 80, attack: 110, defense: 120, specialAttack: 130, specialDefense: 90, speed: 70, baseStatTotal: 600, types: ['fire', 'water'] },
  { id: 'arcanine', name: 'Arcanine', nationalDexNumber: 59, generation: 1, sprite: '/a.png', hp: 90, attack: 110, defense: 80, specialAttack: 100, specialDefense: 80, speed: 95, baseStatTotal: 555, types: ['fire'] },
  { id: 'charizard', name: 'Charizard', nationalDexNumber: 6, generation: 1, sprite: '/c.png', hp: 78, attack: 84, defense: 78, specialAttack: 109, specialDefense: 85, speed: 100, baseStatTotal: 534, types: ['fire', 'flying'] },
  { id: 'squirtle', name: 'Squirtle', nationalDexNumber: 7, generation: 1, sprite: '/s.png', hp: 44, attack: 48, defense: 65, specialAttack: 50, specialDefense: 64, speed: 43, baseStatTotal: 314, types: ['water'] },
  { id: 'dugtrio-alola', name: 'Dugtrio de Alola', nationalDexNumber: 51, generation: 1, isDefault: false, sprite: '/dugtrio-alola.png', hp: 35, attack: 100, defense: 60, specialAttack: 50, specialDefense: 70, speed: 110, baseStatTotal: 425, types: ['ground', 'steel'] },
  ...Array.from({ length: 9 }, (_, index): Pokemon => ({ id: `fire-${index}`, name: `Fire ${index}`, nationalDexNumber: 800 + index, generation: 1, sprite: `/fire-${index}.png`, hp: 50, attack: 50, defense: 50, specialAttack: 50, specialDefense: 50, speed: 50, baseStatTotal: 300, types: ['fire'] })),
];
const catalog: PokemonCatalog = { all: () => pokemon, byId: (id) => pokemon.find((p) => p.id === id), byDexNumber: (n) => pokemon.find((p) => p.nationalDexNumber === n && p.isDefault !== false), forGenerations: (g, options) => pokemon.filter((p) => g.includes(p.generation) && (options?.includeForms || p.isDefault !== false)) };
const players: GamePlayer[] = ['p1', 'p2', 'p3', 'p4'].map((id) => ({ id, displayName: id }));
function setup(rounds = 2) { let now = 1_000; const context: GameContext = { players: players.map((player) => ({ ...player })), pokemon: catalog, get now() { return now; }, random: () => 0, hostId: 'p1' }; let state = typeDuelGame.createInitialState({ generations: [1, 6], typeSelectSeconds: 15, searchSeconds: 20, rounds }, context); state = typeDuelGame.start(state, context); return { state, context, setNow: (n: number) => { now = n; } }; }
function selectTypes(state: TypeDuelState, context: GameContext, a: PokemonType, b: PokemonType) { const [p1, p2] = state.participants; let next = typeDuelGame.handleAction(state, p1, { type: 'SELECT_TYPE', pokemonType: a }, context).state; next = typeDuelGame.handleAction(next, p2, { type: 'SELECT_TYPE', pokemonType: b }, context).state; return next; }
function advance(f: ReturnType<typeof setup>, state: TypeDuelState) { f.setNow((state.roundEndsAt ?? state.nextTransitionAt)!); return typeDuelGame.handleTimeout(state, f.context); }
describe('Type Duel', () => {
  it('selects balanced pairs and avoids an immediate repeat', () => { expect(chooseBalancedPair(['a', 'b', 'c', 'd'], { a: 1, b: 1, c: 0, d: 0 }, ['a', 'b'], () => 0)).toEqual(['c', 'd']); const f = setup(); expect(f.state.participants).toEqual(['p1', 'p2']); });
  it('keeps rival type secret until both have selected', () => { const f = setup(); const [a, b] = f.state.participants; const state = typeDuelGame.handleAction(f.state, a, { type: 'SELECT_TYPE', pokemonType: 'fire' }, f.context).state; expect(typeDuelGame.getPublicState(state, f.context).revealedTypes).toEqual({}); expect((typeDuelGame.getPlayerState(state, b, f.context) as TypeDuelPlayerState).ownType).toBeNull(); expect((typeDuelGame.getPlayerState(state, a, f.context) as TypeDuelPlayerState).ownType).toBe('fire'); });
  it('validates exact dual and exact monotype combinations', () => { expect(isValidPokemonForTypes(pokemon[0]!, 'fire', 'water')).toBe(true); expect(isValidPokemonForTypes(pokemon[1]!, 'fire', 'fire')).toBe(true); expect(isValidPokemonForTypes(pokemon[2]!, 'fire', 'fire')).toBe(false); });
  it('includes regional forms when validating a duel combination', () => { const f = setup(); const state = selectTypes(f.state, f.context, 'ground', 'steel'); expect(state.phase).toBe('TYPE_REVEAL'); expect(state.validPokemonIds).toContain('dugtrio-alola'); });
  it('does not consume a round for an impossible combination', () => { const f = setup(); let state = selectTypes(f.state, f.context, 'dragon', 'fairy'); expect(state.phase).toBe('INVALID_COMBINATION'); expect(state.completedRounds).toBe(0); const pair = state.participants; state = advance(f, state); expect(state.phase).toBe('SELECTING_TYPES'); expect(state.participants).toEqual(pair); expect(state.roundNumber).toBe(1); });
  it('awards the duel to the only player who selected a type before timeout', () => { const f = setup(); const first = typeDuelGame.handleAction(f.state, 'p1', { type: 'SELECT_TYPE', pokemonType: 'fire' }, f.context).state; const state = advance(f, first); expect(state.lastRound).toMatchObject({ reason: 'TYPE_FORFEIT', winnerId: 'p1' }); expect(state.completedRounds).toBe(1); expect(state.scores).toEqual({ p1: 5, p2: 0, p3: 0, p4: 0 }); expect(state.playerStats.p1).toMatchObject({ duelsPlayed: 1, duelsWon: 1 }); expect(typeDuelGame.getPublicState(state, f.context).revealedTypes).toEqual({}); });
  it('cancels without points when neither player selects a type', () => { const f = setup(); const state = advance(f, f.state); expect(state.lastRound?.reason).toBe('TYPE_TIMEOUT'); expect(state.completedRounds).toBe(0); expect(state.scores).toEqual({ p1: 0, p2: 0, p3: 0, p4: 0 }); });
  it('rejects spectators and allows multiple participant attempts with cooldown', () => { const f = setup(); let state = selectTypes(f.state, f.context, 'fire', 'fire'); state = advance(f, state); expect(typeDuelGame.handleAction(state, 'p3', { type: 'ATTEMPT_POKEMON', pokemonId: 'arcanine' }, f.context).accepted).toBe(false); const wrong = typeDuelGame.handleAction(state, 'p1', { type: 'ATTEMPT_POKEMON', pokemonId: 'charizard' }, f.context); expect(wrong.accepted).toBe(true); expect(wrong.state.phase).toBe('POKEMON_SEARCH'); expect(wrong.state.attempts[0]).toMatchObject({ pokemonId: 'charizard', correct: false }); const blocked = typeDuelGame.handleAction(wrong.state, 'p1', { type: 'ATTEMPT_POKEMON', pokemonId: 'arcanine' }, f.context); expect(blocked.error).toMatch(/Espera/); f.setNow(f.context.now + TYPE_DUEL_ATTEMPT_COOLDOWN_MS); const correct = typeDuelGame.handleAction(wrong.state, 'p1', { type: 'ATTEMPT_POKEMON', pokemonId: 'arcanine' }, f.context); expect(correct.state).toMatchObject({ phase: 'ROUND_RESULTS', scores: { p1: 5, p2: 0 } }); expect(correct.state.lastRound?.solutions).toHaveLength(TYPE_DUEL_MAX_SOLUTIONS); expect(correct.state.lastRound?.solutions.map((solution) => solution.id)).not.toContain('arcanine'); });
  it('accepts only the first simultaneous correct answer', () => { const f = setup(); let state = advance(f, selectTypes(f.state, f.context, 'fire', 'water')); state = typeDuelGame.handleAction(state, 'p1', { type: 'ATTEMPT_POKEMON', pokemonId: 'volcanion' }, f.context).state; const second = typeDuelGame.handleAction(state, 'p2', { type: 'ATTEMPT_POKEMON', pokemonId: 'volcanion' }, f.context); expect(state.lastRound?.winnerId).toBe('p1'); expect(second.accepted).toBe(false); expect(state.scores).toEqual({ p1: 5, p2: 0, p3: 0, p4: 0 }); });
  it('shows results for ten seconds and only lets the Host continue early', () => { const f = setup(); let state = advance(f, selectTypes(f.state, f.context, 'fire', 'water')); state = typeDuelGame.handleAction(state, 'p1', { type: 'ATTEMPT_POKEMON', pokemonId: 'volcanion' }, f.context).state; expect(state.nextTransitionAt).toBe(f.context.now + TYPE_DUEL_RESULT_MS); const denied = typeDuelGame.handleAction(state, 'p2', { type: 'CONTINUE' }, f.context); expect(denied).toMatchObject({ accepted: false, error: expect.stringMatching(/Host/) }); const continued = typeDuelGame.handleAction(state, 'p1', { type: 'CONTINUE' }, f.context); expect(continued.accepted).toBe(true); expect(continued.state.phase).toBe('SELECTING_TYPES'); });
  it('times out with at most eight valid solutions', () => { const f = setup(); let state = advance(f, selectTypes(f.state, f.context, 'fire', 'fire')); state = advance(f, state); expect(state.lastRound?.reason).toBe('TIMEOUT'); expect(state.lastRound?.solutions).toHaveLength(TYPE_DUEL_MAX_SOLUTIONS); expect(state.lastRound?.solutions.length).toBeLessThanOrEqual(8); expect(state.scores.p1).toBe(0); });
  it('prioritizes less-used players next round', () => { const f = setup(); let state = advance(f, selectTypes(f.state, f.context, 'fire', 'fire')); state = typeDuelGame.handleAction(state, 'p1', { type: 'ATTEMPT_POKEMON', pokemonId: 'arcanine' }, f.context).state; state = advance(f, state); expect(state.participants).toEqual(['p3', 'p4']); });
  it('finishes after N valid rounds and restores private state', () => { const f = setup(1); let state = selectTypes(f.state, f.context, 'fire', 'fire'); const privateView = typeDuelGame.getPlayerState(state, 'p1', f.context) as TypeDuelPlayerState; expect(privateView.ownType).toBe('fire'); state = advance(f, state); state = typeDuelGame.handleAction(state, 'p1', { type: 'ATTEMPT_POKEMON', pokemonId: 'arcanine' }, f.context).state; state = advance(f, state); expect(state.phase).toBe('GAME_RESULTS'); expect(typeDuelGame.getResults(state).standings).toHaveLength(4); });
  it('cancels without a free win when a duelist disconnects and excludes them from the next pair', () => { const f = setup(); const disconnectedId = f.state.participants[1]; f.context.players.find((player) => player.id === disconnectedId)!.connected = false; let state = typeDuelGame.handlePresenceChange!(f.state, f.context); expect(state).toMatchObject({ phase: 'ROUND_RESULTS', completedRounds: 0, lastRound: { reason: 'DISCONNECTED', winnerId: null } }); expect(state.scores).toEqual({ p1: 0, p2: 0, p3: 0, p4: 0 }); state = advance(f, state); expect(state.participants).not.toContain(disconnectedId); });
});
