import { guessFromStatsConfigSchema, type GuessFromStatsConfig } from '@pokemon-universe/shared';
import { BarChart3, Lightbulb } from 'lucide-react';
import { GenerationSelector } from '../../components/GenerationSelector';

const roundTimes = [15, 20, 30, 45, 60]; const roundCounts = [5, 10, 15, 20];
const statOptions: Array<{ key: keyof GuessFromStatsConfig['stats']; label: string }> = [
  { key: 'hp', label: 'PS' }, { key: 'attack', label: 'Ataque' }, { key: 'defense', label: 'Defensa' }, { key: 'specialAttack', label: 'At. Especial' }, { key: 'specialDefense', label: 'Def. Especial' }, { key: 'speed', label: 'Velocidad' }, { key: 'bst', label: 'Total de Stats (BST)' },
];
const hintOptions: Array<{ key: keyof GuessFromStatsConfig['hints']; label: string }> = [
  { key: 'generation', label: 'Generación' }, { key: 'types', label: 'Tipos' }, { key: 'typeCount', label: 'Nº de tipos' }, { key: 'evolution', label: 'Etapa evolutiva' }, { key: 'height', label: 'Altura' }, { key: 'weight', label: 'Peso' }, { key: 'category', label: 'Legendario / Mítico' },
];

export function validateGuessFromStatsConfig(config: unknown): string | null {
  const result = guessFromStatsConfigSchema.safeParse(config); if (result.success) return null;
  return result.error.issues[0]?.message ?? 'Configuración inválida.';
}

export function GuessFromStatsConfigPanel({ config, disabled, onChange }: { config: unknown; disabled: boolean; onChange(config: unknown): Promise<void> }) {
  const value = config as GuessFromStatsConfig; const statCount = Object.values(value.stats).filter(Boolean).length;
  function toggleStat(key: keyof GuessFromStatsConfig['stats']) { void onChange({ ...value, stats: { ...value.stats, [key]: !value.stats[key] } }); }
  function toggleHint(key: keyof GuessFromStatsConfig['hints']) { void onChange({ ...value, hints: { ...value.hints, [key]: !value.hints[key] } }); }
  return <fieldset disabled={disabled} className="space-y-6">
    <GenerationSelector selected={value.generations} label="Generaciones del pool" onChange={(generations) => void onChange({ ...value, generations })} />
    <div className="grid gap-5 lg:grid-cols-2"><section><span className="label">Tiempo por ronda</span><div className="grid grid-cols-5 gap-2">{roundTimes.map((seconds) => <button type="button" key={seconds} aria-pressed={value.roundSeconds === seconds} onClick={() => void onChange({ ...value, roundSeconds: seconds })} className={`min-h-11 rounded-xl border font-extrabold ${value.roundSeconds === seconds ? 'border-electric bg-electric text-night' : 'border-ink/10 bg-surface-raised text-ink/65'}`}>{seconds}s</button>)}</div></section><section><span className="label">Número de rondas</span><div className="grid grid-cols-4 gap-2">{roundCounts.map((rounds) => <button type="button" key={rounds} aria-pressed={value.rounds === rounds} onClick={() => void onChange({ ...value, rounds })} className={`min-h-11 rounded-xl border font-extrabold ${value.rounds === rounds ? 'border-electric bg-electric text-night' : 'border-ink/10 bg-surface-raised text-ink/65'}`}>{rounds}</button>)}</div></section></div>
    <section><div className="mb-3 flex items-center justify-between gap-2"><div><span className="label !mb-0">Stats mostradas</span><p className="text-sm font-bold text-ink/65">Los valores visibles definen todas las respuestas correctas.</p></div><span className={`chip ${statCount < 2 ? 'text-berry' : 'text-leaf'}`}>{statCount} activas</span></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{statOptions.map((option) => <button type="button" key={option.key} aria-pressed={value.stats[option.key]} onClick={() => toggleStat(option.key)} className={`flex min-h-12 items-center gap-2 rounded-xl border px-3 text-left font-extrabold ${value.stats[option.key] ? 'border-aqua/40 bg-aqua/10 text-aqua' : 'border-ink/10 bg-surface-raised text-ink/60'}`}><BarChart3 size={17} />{value.stats[option.key] ? '✓ ' : ''}{option.label}</button>)}</div>{statCount < 2 && <p className="mt-2 rounded-xl bg-berry/10 p-3 text-sm font-extrabold text-berry" role="alert">Selecciona al menos 2 estadísticas.</p>}</section>
    <section><button type="button" aria-pressed={value.hintsEnabled} onClick={() => void onChange({ ...value, hintsEnabled: !value.hintsEnabled })} className={`flex min-h-20 w-full items-center gap-3 rounded-2xl border p-3 text-left ${value.hintsEnabled ? 'border-electric bg-electric/10' : 'border-ink/10 bg-surface-raised'}`}><span className={`grid h-11 w-11 place-items-center rounded-xl ${value.hintsEnabled ? 'bg-electric text-night' : 'bg-ink/[0.07] text-ink/60'}`}><Lightbulb /></span><span className="flex-1"><strong className="block font-display text-xl">Pistas adicionales</strong><small className="font-bold text-ink/65">{value.hintsEnabled ? 'También forman parte de la equivalencia.' : 'Solo se mostrarán las stats seleccionadas.'}</small></span><span className={`grid h-6 w-6 place-items-center rounded-full font-black ${value.hintsEnabled ? 'bg-leaf text-night' : 'bg-ink/10'}`}>{value.hintsEnabled ? '✓' : ''}</span></button>{value.hintsEnabled && <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{hintOptions.map((option) => <button type="button" key={option.key} aria-pressed={value.hints[option.key]} onClick={() => toggleHint(option.key)} className={`min-h-11 rounded-xl border px-3 text-left font-extrabold ${value.hints[option.key] ? 'border-leaf/40 bg-leaf/10 text-leaf' : 'border-ink/10 bg-surface-raised text-ink/60'}`}>{value.hints[option.key] ? '✓ ' : ''}{option.label}</button>)}</div>}</section>
    <p className="rounded-xl bg-ink/[0.04] p-3 text-sm font-bold text-ink/65">Las formas con ID y Base Stats propios participan. Si dos formas son indistinguibles por la información pública, ambas se aceptan.</p>
  </fieldset>;
}
