import { describe, expect, it } from 'vitest';
import { CachedTcgCardCatalog, getComparableCardPrice } from './comparable-price.js';
import type { TcgCatalogCardRow } from './repository.js';

const date = new Date('2026-01-01T00:00:00Z');
function card(id: string, market: string | null = '4.2500', overrides: Partial<TcgCatalogCardRow> = {}): TcgCatalogCardRow { return { id, localId: id, name: `Card ${id}`, rarity: 'Rare', imageUrl: `https://img.test/${id}.webp`, set: { id: 'set', name: 'Set' }, prices: [{ provider: 'cardmarket', currency: 'EUR', variant: 'standard', market, observedAt: date }], ...overrides }; }
function repository(rows: TcgCatalogCardRow[]) { return { findById: async () => null, count: async () => rows.length, loadComparableCards: async () => rows }; }

describe('PostgreSQL TCG comparable price catalog', () => {
  it('uses market from the coherent EUR Cardmarket standard lane and keeps zero valid', async () => { const catalog = new CachedTcgCardCatalog(repository([card('a', '0'), card('b', '4.2500')])); await catalog.refresh(); expect(catalog.cardsFor({ setIds: [], rarities: [], minPrice: null, maxPrice: null }).map(({ price }) => price)).toEqual(['0', '4.25']); });
  it('ignores null, negative, NaN, missing images and non-HTTPS assets', async () => { const catalog = new CachedTcgCardCatalog(repository([card('ok-a'), card('ok-b'), card('null', null), card('negative', '-2'), card('nan', 'NaN'), card('missing', '2', { imageUrl: null }), card('http', '2', { imageUrl: 'http://img.test/x' })])); await catalog.refresh(); expect(catalog.options().cardCount).toBe(2); });
  it('filters sets, rarities, and exact price bounds', async () => { const catalog = new CachedTcgCardCatalog(repository([card('a', '1.001'), card('b', '1.002'), card('c', '3', { set: { id: 'other', name: 'Other' }, rarity: 'Promo' })])); await catalog.refresh(); expect(catalog.cardsFor({ setIds: ['set'], rarities: ['Rare'], minPrice: '1.001', maxPrice: '1.002' })).toHaveLength(2); expect(catalog.cardsFor({ setIds: ['other'], rarities: [], minPrice: null, maxPrice: null })).toHaveLength(0); });
  it('does not mix providers, variants, or currencies inside one pool', async () => { const a = card('a'); const b = card('b'); const usd = { provider: 'tcgplayer', currency: 'USD', variant: 'normal', market: '8', observedAt: date }; a.prices.push(usd); b.prices.push(usd); const catalog = new CachedTcgCardCatalog(repository([a, b])); await catalog.refresh(); const pool = catalog.cardsFor({ setIds: [], rarities: [], minPrice: null, maxPrice: null }); expect(new Set(pool.map(({ currency, provider, variant }) => `${currency}:${provider}:${variant}`))).toEqual(new Set(['EUR:cardmarket:standard'])); });
  it('selects the newest row deterministically for a lane', () => { const row = card('a'); row.prices.unshift({ ...row.prices[0]!, market: '1', observedAt: new Date('2025-01-01') }); expect(getComparableCardPrice(row, { currency: 'EUR', provider: 'cardmarket', variant: 'standard' })?.amount).toBe('4.25'); });
});
