import { type TcgFilterOptions, type TcgHigherLowerConfig } from '@pokemon-universe/shared';
import { AlertCircle, Check, ChevronDown, Search } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { api } from '../../lib/api';
import { ConfigRange } from '../../room/ConfigRange';

function MultiFilter({ label, allLabel, options, selected, disabled, onChange }: { label: string; allLabel: string; options: Array<{ value: string; label: string; count: number }>; selected: string[]; disabled: boolean; onChange(value: string[]): void }) {
  const [query, setQuery] = useState(''); const visible = options.filter((option) => option.label.toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es')));
  return <details className="rounded-2xl border border-ink/10 bg-surface-raised"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 p-4"><span><span className="label !mb-0">{label}</span><strong>{selected.length === 0 ? allLabel : `${selected.length} seleccionados`}</strong></span><ChevronDown size={18} /></summary><div className="border-t border-ink/10 p-3">
    <label className="relative mb-2 block"><span className="sr-only">Buscar {label}</span><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-ink/45" size={16} /><input className="field !min-h-10 !pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar" /></label>
    <button type="button" disabled={disabled} onClick={() => onChange([])} className={`mb-2 w-full rounded-xl border p-2 text-left font-bold ${selected.length === 0 ? 'border-aqua bg-aqua/10' : 'border-ink/10'}`}><Check className={`mr-2 inline ${selected.length ? 'opacity-0' : ''}`} size={15} />{allLabel}</button>
    <div className="max-h-56 space-y-1 overflow-y-auto pr-1">{visible.map((option) => { const active = selected.includes(option.value); return <button type="button" key={option.value} disabled={disabled} onClick={() => onChange(active ? selected.filter((item) => item !== option.value) : [...selected, option.value])} className={`flex w-full items-center gap-2 rounded-xl border p-2 text-left ${active ? 'border-aqua bg-aqua/10' : 'border-transparent hover:bg-ink/[.04]'}`}><Check className={active ? 'text-aqua' : 'opacity-0'} size={15} /><span className="min-w-0 flex-1 truncate font-bold">{option.label}</span><span className="text-xs font-bold text-ink/45">{option.count}</span></button>; })}</div>
  </div></details>;
}

export function TcgHigherLowerConfigPanel({ config, disabled, onChange }: { config: unknown; disabled: boolean; onChange(config: unknown): Promise<void> }) {
  const value = config as TcgHigherLowerConfig; const [options, setOptions] = useState<TcgFilterOptions | null>(null); const [loadError, setLoadError] = useState(''); const [eligible, setEligible] = useState<number | null>(null);
  useEffect(() => { let alive = true; const load = () => void api<TcgFilterOptions>('/tcg/options').then((data) => { if (alive) { setOptions(data); setLoadError(''); } }).catch((error: unknown) => { if (alive) setLoadError(error instanceof Error ? error.message : 'No se pudo cargar el catálogo TCG.'); }); load(); const timer = window.setInterval(load, 10_000); return () => { alive = false; window.clearInterval(timer); }; }, []);
  const filterKey = JSON.stringify(value);
  useEffect(() => { let alive = true; const timer = window.setTimeout(() => { void api<{ cardCount: number }>('/tcg/eligibility', { method: 'POST', body: JSON.stringify(value) }).then((data) => { if (alive) setEligible(data.cardCount); }).catch(() => { if (alive) setEligible(null); }); }, 250); return () => { alive = false; window.clearTimeout(timer); }; }, [filterKey, options?.cardCount]);
  const sets = useMemo(() => options?.sets.map((set) => ({ value: set.id, label: set.name, count: set.cardCount })) ?? [], [options]); const rarities = useMemo(() => options?.rarities.map((rarity) => ({ value: rarity.value, label: rarity.value, count: rarity.cardCount })) ?? [], [options]);
  const updatePrice = (key: 'minPrice' | 'maxPrice', raw: string) => void onChange({ ...value, [key]: raw.trim() === '' ? null : raw });
  return <fieldset disabled={disabled} className="space-y-5">
    {loadError && <p className="status-error"><AlertCircle className="inline" size={16} /> {loadError}</p>}
    <div className="grid gap-3 md:grid-cols-2"><MultiFilter label="Sets" allLabel="Todos los sets" options={sets} selected={value.setIds} disabled={disabled} onChange={(setIds) => void onChange({ ...value, setIds })} /><MultiFilter label="Rareza" allLabel="Todas las rarezas" options={rarities} selected={value.rarities} disabled={disabled} onChange={(raritiesValue) => void onChange({ ...value, rarities: raritiesValue })} /></div>
    <div><span className="label">Rango de precio</span><div className="grid gap-3 sm:grid-cols-2"><label><span className="mb-1 block text-sm font-bold text-ink/65">Mínimo</span><input className="field" type="number" min="0" step="0.01" value={value.minPrice ?? ''} placeholder="Sin límite" onChange={(event) => updatePrice('minPrice', event.target.value)} /></label><label><span className="mb-1 block text-sm font-bold text-ink/65">Máximo</span><input className="field" type="number" min="0" step="0.01" value={value.maxPrice ?? ''} placeholder="Sin límite" onChange={(event) => updatePrice('maxPrice', event.target.value)} /></label></div></div>
    <div className="grid gap-4 md:grid-cols-2"><ConfigRange label="Tiempo por comparación" value={value.roundSeconds} min={5} max={60} step={5} disabled={disabled} formatValue={(seconds) => `${seconds} segundos`} onCommit={(roundSeconds) => onChange({ ...value, roundSeconds })} /><ConfigRange label="Número de rondas" value={value.rounds} min={5} max={50} disabled={disabled} accent="aqua" formatValue={(rounds) => `${rounds} rondas`} onCommit={(rounds) => onChange({ ...value, rounds })} /></div>
    <p className={`rounded-xl p-3 text-sm font-bold ${eligible !== null && eligible >= 2 ? 'bg-leaf/10 text-leaf' : 'bg-berry/10 text-berry'}`}>{eligible === null ? 'Comprobando cartas disponibles…' : eligible >= 2 ? `${eligible.toLocaleString('es-ES')} cartas elegibles.` : 'No hay suficientes cartas con una misma fuente, variante y moneda. Amplía los filtros antes de iniciar.'}</p>
  </fieldset>;
}
