ALTER TABLE "Pokemon"
  ADD COLUMN "heightDecimeters" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "weightHectograms" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "legendaryStatus" TEXT NOT NULL DEFAULT 'NORMAL',
  ADD COLUMN "color" TEXT NOT NULL DEFAULT 'unknown',
  ADD COLUMN "abilities" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
