import { GENERATIONS, HIGHER_LOWER_CATEGORIES, type HigherLowerCategory, type HigherLowerConfig } from '@pokemon-universe/shared';
const labels: Record<HigherLowerCategory, string> = { DEX_NUMBER: 'N.º Pokédex', HP: 'HP', ATTACK: 'Ataque', DEFENSE: 'Defensa', SPECIAL_ATTACK: 'Ataque Esp.', SPECIAL_DEFENSE: 'Defensa Esp.', SPEED: 'Velocidad', BASE_STAT_TOTAL: 'Total stats' };
export function HigherLowerConfigPanel({ config, disabled, onChange }: { config: unknown; disabled: boolean; onChange(config: unknown): Promise<void> }) {
  const value = config as HigherLowerConfig;
  const toggleGeneration = (generation: number) => { const generations = value.generations.includes(generation) ? value.generations.filter((item) => item !== generation) : [...value.generations, generation]; if (generations.length) void onChange({ ...value, generations }); };
  const toggleCategory = (category: HigherLowerCategory) => { const categories = value.categories.includes(category) ? value.categories.filter((item) => item !== category) : [...value.categories, category]; if (categories.length) void onChange({ ...value, categories }); };
  return <fieldset disabled={disabled} className="space-y-6"><div><span className="label">Categorías</span><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{HIGHER_LOWER_CATEGORIES.map((category) => <button type="button" key={category} onClick={() => toggleCategory(category)} className={`rounded-xl border-2 px-3 py-2 text-left font-extrabold ${value.categories.includes(category) ? 'border-electric bg-electric text-night' : 'border-ink/10 bg-surface-raised text-ink/50'}`}>{labels[category]}</button>)}</div></div>
    <div><span className="label">Generaciones</span><div className="grid grid-cols-3 gap-2 sm:grid-cols-5">{GENERATIONS.map((generation) => <button type="button" key={generation} onClick={() => toggleGeneration(generation)} className={`rounded-xl border-2 py-2 font-bold ${value.generations.includes(generation) ? 'border-aqua bg-aqua text-night' : 'border-ink/10 bg-surface-raised text-ink/45'}`}>Gen {generation}</button>)}</div></div>
    <div className="grid gap-4 sm:grid-cols-2"><div><span className="label">Mostrar valor anterior</span><div className="grid grid-cols-2 gap-2">{[[true, 'Sí'], [false, 'No']].map(([choice, label]) => <button type="button" key={String(choice)} onClick={() => void onChange({ ...value, showPreviousValue: choice })} className={`rounded-xl border-2 py-2 font-bold ${value.showPreviousValue === choice ? 'border-berry bg-berry text-white' : 'border-ink/10 bg-surface-raised'}`}>{label}</button>)}</div></div><div><span className="label">Mostrar respuestas</span><div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => void onChange({ ...value, answerVisibility: 'REALTIME' })} className={`rounded-xl border-2 py-2 font-bold ${value.answerVisibility === 'REALTIME' ? 'border-leaf bg-leaf text-night' : 'border-ink/10 bg-surface-raised'}`}>En directo</button><button type="button" onClick={() => void onChange({ ...value, answerVisibility: 'REVEAL' })} className={`rounded-xl border-2 py-2 font-bold ${value.answerVisibility === 'REVEAL' ? 'border-leaf bg-leaf text-night' : 'border-ink/10 bg-surface-raised'}`}>En reveal</button></div></div></div>
    <div className="grid gap-5 sm:grid-cols-2"><label><span className="label">Tiempo · {value.roundSeconds}s</span><input className="w-full accent-berry" type="range" min={10} max={60} step={5} value={value.roundSeconds} onChange={(event) => void onChange({ ...value, roundSeconds: Number(event.target.value) })} /></label><label><span className="label">Rondas · {value.rounds}</span><input className="w-full accent-aqua" type="range" min={1} max={30} value={value.rounds} onChange={(event) => void onChange({ ...value, rounds: Number(event.target.value) })} /></label></div>
  </fieldset>;
}
