import { describe, expect, it } from 'vitest';
import type { GameContext, Pokemon, PokemonCatalog } from '../../index.js';
import { defaultWhoIsWhoPokemonConfig } from './config.js';
import { whoIsWhoPokemonGame } from './server.js';
import type { WhoIsWhoPlayerState, WhoIsWhoState } from './types.js';

const pokemon: Pokemon[] = Array.from({ length: 8 }, (_, index) => ({ id: `p${index + 1}`, nationalDexNumber: index + 1, name: `P${index + 1}`, generation: 1, isDefault: true, sprite: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${index + 1}.png`, hp: 50, attack: 50, defense: 50, specialAttack: 50, specialDefense: 50, speed: 50, baseStatTotal: 300, types: ['normal'], legendaryStatus: 'NORMAL' }));
const catalog: PokemonCatalog = { all: () => pokemon, byId: (id) => pokemon.find((entry) => entry.id === id), byDexNumber: (number) => pokemon.find((entry) => entry.nationalDexNumber === number), forGenerations: () => pokemon };
function setup(rounds = 2) { const context: GameContext = { players: ['a', 'b', 'c', 'd'].map((id) => ({ id, displayName: id, connected: true, active: true })), pokemon: catalog, now: 1_000, random: () => 0, roomCode: 'TEST' }; const state = whoIsWhoPokemonGame.start(whoIsWhoPokemonGame.createInitialState({ ...defaultWhoIsWhoPokemonConfig, generations: [1], boardSize: 6, rounds }, context), context); return { context, state }; }
function action(state: WhoIsWhoState, context: GameContext, playerId: string, value: Parameters<typeof whoIsWhoPokemonGame.handleAction>[2]) { return whoIsWhoPokemonGame.handleAction(state, playerId, value, context); }

describe('Quién es Quién — Pokémon', () => {
  it('creates balanced teams with different secrets and keeps them private', () => { const { context, state } = setup(); expect(Math.abs(state.teams.BLUE.playerIds.length - state.teams.RED.playerIds.length)).toBeLessThanOrEqual(1); expect(state.teams.BLUE.secretPokemonId).not.toBe(state.teams.RED.secretPokemonId); const publicState = whoIsWhoPokemonGame.getPublicState(state, context); expect(publicState.revealedSecrets.BLUE).toBeNull(); expect(publicState.revealedSecrets.RED).toBeNull(); const blue = whoIsWhoPokemonGame.getPlayerState(state, state.teams.BLUE.playerIds[0]!, context) as WhoIsWhoPlayerState; const red = whoIsWhoPokemonGame.getPlayerState(state, state.teams.RED.playerIds[0]!, context) as WhoIsWhoPlayerState; const spectator = whoIsWhoPokemonGame.getPlayerState(state, 'spectator', context) as WhoIsWhoPlayerState; expect(blue.ownSecret?.id).toBe(state.teams.BLUE.secretPokemonId); expect(red.ownSecret?.id).toBe(state.teams.RED.secretPokemonId); expect(spectator.ownSecret).toBeNull(); expect(JSON.stringify(blue)).not.toContain(state.teams.RED.secretPokemonId); expect(JSON.stringify(red)).not.toContain(state.teams.BLUE.secretPokemonId); expect(JSON.stringify(spectator)).not.toContain(state.teams.BLUE.secretPokemonId); expect(JSON.stringify(spectator)).not.toContain(state.teams.RED.secretPokemonId); });
  it('synchronizes reversible discards within the team', () => { const { context, state } = setup(); const player = state.teams.BLUE.playerIds[0]!; const card = state.board[0]!.id; const discarded = action(state, context, player, { type: 'TOGGLE_DISCARD', pokemonId: card }); expect(discarded.accepted).toBe(true); expect(discarded.state.teams.BLUE.discardedPokemonIds).toContain(card); const restored = action(discarded.state, context, player, { type: 'TOGGLE_DISCARD', pokemonId: card }); expect(restored.state.teams.BLUE.discardedPokemonIds).not.toContain(card); });
  it('allows either team to manage its board outside its turn without affecting the rival', () => { const { context, state } = setup(); const red = state.teams.RED.playerIds[0]!; const card = state.board[0]!.id; const result = action(state, context, red, { type: 'TOGGLE_DISCARD', pokemonId: card }); expect(result.accepted).toBe(true); expect(result.state.teams.RED.discardedPokemonIds).toEqual([card]); expect(result.state.teams.BLUE.discardedPokemonIds).toEqual([]); });
  it('supports unlimited discards, all-but-one, every card, and restoring every card', () => { const { context, state } = setup(); const blue = state.teams.BLUE.playerIds[0]!; let current = state; for (const card of state.board.slice(0, -1)) current = action(current, context, blue, { type: 'TOGGLE_DISCARD', pokemonId: card.id }).state; expect(current.teams.BLUE.discardedPokemonIds).toHaveLength(state.board.length - 1); current = action(current, context, blue, { type: 'TOGGLE_DISCARD', pokemonId: state.board.at(-1)!.id }).state; expect(current.teams.BLUE.discardedPokemonIds).toHaveLength(state.board.length); for (const card of state.board) current = action(current, context, blue, { type: 'TOGGLE_DISCARD', pokemonId: card.id }).state; expect(current.teams.BLUE.discardedPokemonIds).toEqual([]); });
  it('shares discards with teammates but not rivals, including reconnect projections', () => { const { context, state } = setup(); const [blue, teammate] = state.teams.BLUE.playerIds; const red = state.teams.RED.playerIds[0]!; const card = state.board[2]!.id; const next = action(state, context, blue!, { type: 'TOGGLE_DISCARD', pokemonId: card }).state; const first = whoIsWhoPokemonGame.getPlayerState(next, blue!, context) as WhoIsWhoPlayerState; const peer = whoIsWhoPokemonGame.getPlayerState(next, teammate!, context) as WhoIsWhoPlayerState; const rival = whoIsWhoPokemonGame.getPlayerState(next, red, context) as WhoIsWhoPlayerState; expect(first.discardedPokemonIds).toEqual([card]); expect(peer.discardedPokemonIds).toEqual([card]); expect(rival.discardedPokemonIds).toEqual([]); expect(JSON.parse(JSON.stringify(peer)).discardedPokemonIds).toEqual([card]); });
  it('keeps discards, board and secrets across every turn and round', () => { const { context, state } = setup(); const blue = state.teams.BLUE.playerIds[0]!; const red = state.teams.RED.playerIds[0]!; const card = state.board[0]!.id; const discarded = action(state, context, blue, { type: 'TOGGLE_DISCARD', pokemonId: card }).state; const oldSecrets = [discarded.teams.BLUE.secretPokemonId, discarded.teams.RED.secretPokemonId]; const oldBoard = discarded.board; const redTurn = action(discarded, context, blue, { type: 'END_TURN' }).state; expect(redTurn.teams.BLUE.discardedPokemonIds).toEqual([card]); const nextRound = action(redTurn, context, red, { type: 'END_TURN' }).state; expect(nextRound.roundNumber).toBe(2); expect(nextRound.currentTeam).toBe('BLUE'); expect(nextRound.board).toEqual(oldBoard); expect(nextRound.teams.BLUE.discardedPokemonIds).toEqual([card]); expect([nextRound.teams.BLUE.secretPokemonId, nextRound.teams.RED.secretPokemonId]).toEqual(oldSecrets); });
  it('lets each team privately choose one secret from the board before the timer starts', () => { const context: GameContext = { players: ['a', 'b'].map((id) => ({ id, displayName: id, connected: true, active: true })), pokemon: catalog, now: 1_000, random: () => 0, roomCode: 'TEST' }; let state = whoIsWhoPokemonGame.start(whoIsWhoPokemonGame.createInitialState({ ...defaultWhoIsWhoPokemonConfig, generations: [1], boardSize: 6, rounds: 2, secretSelection: 'PLAYER_CHOICE' }, context), context); expect(state.roundEndsAt).toBeNull(); const blue = state.teams.BLUE.playerIds[0]!; const red = state.teams.RED.playerIds[0]!; state = action(state, context, blue, { type: 'SELECT_SECRET', pokemonId: state.board[0]!.id }).state; expect(state.roundEndsAt).toBeNull(); expect((whoIsWhoPokemonGame.getPlayerState(state, red, context) as WhoIsWhoPlayerState).ownSecret).toBeNull(); state = action(state, context, red, { type: 'SELECT_SECRET', pokemonId: state.board[1]!.id }).state; expect(state.roundEndsAt).toBe(41_000); expect(whoIsWhoPokemonGame.getPublicState(state, context).revealedSecrets).toEqual({ BLUE: null, RED: null }); });
  it('rejects spectators, unknown cards, and keeps double toggles consistent', () => { const { context, state } = setup(); const blue = state.teams.BLUE.playerIds[0]!; const card = state.board[0]!.id; expect(action(state, context, 'spectator', { type: 'TOGGLE_DISCARD', pokemonId: card }).accepted).toBe(false); expect(action(state, context, blue, { type: 'TOGGLE_DISCARD', pokemonId: 'missing' }).accepted).toBe(false); const once = action(state, context, blue, { type: 'TOGGLE_DISCARD', pokemonId: card }).state; const twice = action(once, context, blue, { type: 'TOGGLE_DISCARD', pokemonId: card }).state; expect(twice.teams.BLUE.discardedPokemonIds).toEqual([]); });
  it('alternates turns, ends a wrong guess and awards a correct guess', () => { const { context, state } = setup(); const blue = state.teams.BLUE.playerIds[0]!; const red = state.teams.RED.playerIds[0]!; const wrong = state.board.find((card) => card.id !== state.teams.RED.secretPokemonId)!; const failed = action(state, context, blue, { type: 'GUESS_POKEMON', pokemonId: wrong.id }); expect(failed.accepted).toBe(true); expect(failed.state.currentTeam).toBe('RED'); expect(failed.state.guesses.at(-1)?.correct).toBe(false); const correct = action(failed.state, context, red, { type: 'GUESS_POKEMON', pokemonId: state.teams.BLUE.secretPokemonId }); expect(correct.accepted).toBe(true); expect(correct.state.phase).toBe('GAME_RESULTS'); expect(correct.state.winnerTeam).toBe('RED'); });
  it('finishes in a draw after the configured full rounds', () => { const { context, state } = setup(1); const blue = state.teams.BLUE.playerIds[0]!; const red = state.teams.RED.playerIds[0]!; const wrongBlue = state.board.find((card) => card.id !== state.teams.RED.secretPokemonId)!; const wrongRed = state.board.find((card) => card.id !== state.teams.BLUE.secretPokemonId)!; const afterBlue = action(state, context, blue, { type: 'GUESS_POKEMON', pokemonId: wrongBlue.id }).state; const afterRed = action(afterBlue, context, red, { type: 'GUESS_POKEMON', pokemonId: wrongRed.id }).state; expect(afterRed.phase).toBe('GAME_RESULTS'); expect(afterRed.winnerTeam).toBeNull(); });
  it('awards the other team when a complete team leaves permanently', () => { const { context, state } = setup(); (context as { players: GameContext['players'] }).players = context.players.map((player) => state.teams.BLUE.playerIds.includes(player.id) ? { ...player, active: false } : player); const next = whoIsWhoPokemonGame.handlePresenceChange!(state, context); expect(next.phase).toBe('GAME_RESULTS'); expect(next.winnerTeam).toBe('RED'); });
});
