import { describe, expect, it } from 'vitest';
import type { GameContext, Pokemon, PokemonCatalog } from '../../index.js';
import { defaultWhoIsWhoPokemonConfig } from './config.js';
import { whoIsWhoPokemonGame } from './server.js';
import type { WhoIsWhoPlayerState, WhoIsWhoState } from './types.js';

const pokemon: Pokemon[] = Array.from({ length: 8 }, (_, index) => ({ id: `p${index + 1}`, nationalDexNumber: index + 1, name: `P${index + 1}`, generation: 1, isDefault: true, sprite: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${index + 1}.png`, hp: 50, attack: 50, defense: 50, specialAttack: 50, specialDefense: 50, speed: 50, baseStatTotal: 300, types: ['normal'], legendaryStatus: 'NORMAL' }));
const catalog: PokemonCatalog = { all: () => pokemon, byId: (id) => pokemon.find((entry) => entry.id === id), byDexNumber: (number) => pokemon.find((entry) => entry.nationalDexNumber === number), forGenerations: () => pokemon };
function setup(rounds = 2) { const context: GameContext = { players: ['a', 'b', 'c', 'd'].map((id) => ({ id, displayName: id, connected: true, active: true })), pokemon: catalog, now: 1_000, random: () => 0, roomCode: 'TEST' }; const state = whoIsWhoPokemonGame.start(whoIsWhoPokemonGame.createInitialState({ ...defaultWhoIsWhoPokemonConfig, generations: [1], boardSize: 6, rounds }, context), context); return { context, state }; }
function action(state: WhoIsWhoState, context: GameContext, playerId: string, value: Parameters<typeof whoIsWhoPokemonGame.handleAction>[2]) { return whoIsWhoPokemonGame.handleAction(state, playerId, value, context); }

describe('Quién es Quién — Pokémon', () => {
  it('creates balanced teams with different secrets and keeps them private', () => { const { context, state } = setup(); expect(Math.abs(state.teams.BLUE.playerIds.length - state.teams.RED.playerIds.length)).toBeLessThanOrEqual(1); expect(state.teams.BLUE.secretPokemonId).not.toBe(state.teams.RED.secretPokemonId); const publicState = whoIsWhoPokemonGame.getPublicState(state, context); expect(publicState.revealedSecrets.BLUE).toBeNull(); expect(publicState.revealedSecrets.RED).toBeNull(); const privateState = whoIsWhoPokemonGame.getPlayerState(state, state.teams.BLUE.playerIds[0]!, context) as WhoIsWhoPlayerState; expect(privateState.ownSecret?.id).toBe(state.teams.BLUE.secretPokemonId); });
  it('synchronizes reversible discards and cursors only within the team', () => { const { context, state } = setup(); const player = state.teams.BLUE.playerIds[0]!; const card = state.board[0]!.id; const discarded = action(state, context, player, { type: 'TOGGLE_DISCARD', pokemonId: card }); expect(discarded.accepted).toBe(true); expect(discarded.state.teams.BLUE.discardedPokemonIds).toContain(card); const restored = action(discarded.state, context, player, { type: 'TOGGLE_DISCARD', pokemonId: card }); expect(restored.state.teams.BLUE.discardedPokemonIds).not.toContain(card); const cursor = action(restored.state, context, player, { type: 'UPDATE_CURSOR', x: 0.4, y: 0.6 }); expect((whoIsWhoPokemonGame.getPlayerState(cursor.state, player, context) as WhoIsWhoPlayerState).cursors[player]).toMatchObject({ x: 0.4, y: 0.6 }); });
  it('alternates turns, ends a wrong guess and awards a correct guess', () => { const { context, state } = setup(); const blue = state.teams.BLUE.playerIds[0]!; const red = state.teams.RED.playerIds[0]!; const wrong = state.board.find((card) => card.id !== state.teams.RED.secretPokemonId)!; const failed = action(state, context, blue, { type: 'GUESS_POKEMON', pokemonId: wrong.id }); expect(failed.accepted).toBe(true); expect(failed.state.currentTeam).toBe('RED'); expect(failed.state.guesses.at(-1)?.correct).toBe(false); const correct = action(failed.state, context, red, { type: 'GUESS_POKEMON', pokemonId: state.teams.BLUE.secretPokemonId }); expect(correct.accepted).toBe(true); expect(correct.state.phase).toBe('GAME_RESULTS'); expect(correct.state.winnerTeam).toBe('RED'); });
  it('finishes in a draw after the configured full rounds', () => { const { context, state } = setup(1); const blue = state.teams.BLUE.playerIds[0]!; const red = state.teams.RED.playerIds[0]!; const wrongBlue = state.board.find((card) => card.id !== state.teams.RED.secretPokemonId)!; const wrongRed = state.board.find((card) => card.id !== state.teams.BLUE.secretPokemonId)!; const afterBlue = action(state, context, blue, { type: 'GUESS_POKEMON', pokemonId: wrongBlue.id }).state; const afterRed = action(afterBlue, context, red, { type: 'GUESS_POKEMON', pokemonId: wrongRed.id }).state; expect(afterRed.phase).toBe('GAME_RESULTS'); expect(afterRed.winnerTeam).toBeNull(); });
  it('awards the other team when a complete team leaves permanently', () => { const { context, state } = setup(); (context as { players: GameContext['players'] }).players = context.players.map((player) => state.teams.BLUE.playerIds.includes(player.id) ? { ...player, active: false } : player); const next = whoIsWhoPokemonGame.handlePresenceChange!(state, context); expect(next.phase).toBe('GAME_RESULTS'); expect(next.winnerTeam).toBe('RED'); });
});
