import type { PokemonTeamAuctionConfig } from '@pokemon-universe/shared';
import { Coins, Sparkles } from 'lucide-react';
import { GenerationSelector } from '../../components/GenerationSelector';

const budgets = [10, 20, 30, 50] as const;

export function PokemonTeamAuctionConfigPanel({ config, disabled, onChange }: { config: unknown; disabled: boolean; onChange(config: unknown): Promise<void> }) {
  const value = config as PokemonTeamAuctionConfig;
  return <fieldset disabled={disabled} className="space-y-7">
    <GenerationSelector selected={value.generations} label="Generaciones disponibles" description="La pool contiene exactamente seis lotes por jugador. Las formas alternativas cuentan como Pokémon independientes." onChange={(generations) => void onChange({ ...value, generations })} />
    <section aria-labelledby="team-auction-budget"><div className="mb-2 flex items-center gap-2"><Coins className="text-electric" size={19} /><span id="team-auction-budget" className="font-extrabold">Presupuesto inicial por jugador</span></div><div className="grid gap-2 sm:grid-cols-[repeat(4,minmax(0,1fr))_minmax(8rem,1fr)]">{budgets.map((initialBudget) => <button type="button" key={initialBudget} aria-pressed={value.initialBudget === initialBudget} onClick={() => void onChange({ ...value, initialBudget })} className={`min-h-11 rounded-xl border font-extrabold ${value.initialBudget === initialBudget ? 'border-electric bg-electric text-night' : 'border-ink/10 bg-surface-raised text-ink/65 hover:border-aqua'}`}>{initialBudget}</button>)}<label><span className="sr-only">Presupuesto personalizado</span><input className="field min-h-11 text-center font-extrabold" type="number" min={1} max={100} value={value.initialBudget} onChange={(event) => { const initialBudget = Number(event.target.value); if (Number.isInteger(initialBudget) && initialBudget >= 1 && initialBudget <= 100) void onChange({ ...value, initialBudget }); }} /></label></div><p className="mt-2 text-sm font-bold text-ink/60">Las pujas empiezan en 1 y pueden saltar directamente a cualquier cantidad que puedas pagar.</p></section>
    <button type="button" aria-pressed={value.includeForms} onClick={() => void onChange({ ...value, includeForms: !value.includeForms })} className={`flex min-h-20 w-full items-center gap-3 rounded-xl border p-3 text-left transition-colors ${value.includeForms ? 'border-aqua bg-aqua/10' : 'border-ink/10 bg-surface-raised hover:border-aqua/45'}`}><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${value.includeForms ? 'bg-aqua text-night' : 'bg-ink/[.07]'}`}><Sparkles size={20} /></span><span className="min-w-0 flex-1"><strong className="block font-display text-lg">Incluir formas alternativas</strong><small className="block font-bold text-ink/65">Las formas regionales ocupan su propio lote y se valoran con su BST.</small></span><span className="font-black text-leaf">{value.includeForms ? '✓' : ''}</span></button>
  </fieldset>;
}
