import type { SubjectiveCategory } from '../contracts.js';

const texts = [
  'De más adorable a menos adorable',
  'De mejor compañero de aventuras a peor compañero',
  'De más probable a menos probable que llegue tarde a una cita',
  'De mejor cocinero a peor cocinero',
  'De más fiable a menos fiable para guardar un secreto',
  'De mejor compañero de piso a peor compañero',
  'De más probable a menos probable que sobreviva en una isla desierta',
  'De mejor profesor a peor profesor',
  'De más elegante a menos elegante',
  'De más divertido a menos divertido en una fiesta',
  'De mejor guardaespaldas a peor guardaespaldas',
  'De más probable a menos probable que se haga influencer',
  'De mejor mascota a peor mascota',
  'De más aterrador a menos aterrador al encontrarlo de noche',
  'De más inteligente a menos inteligente',
  'De mejor líder de equipo a peor líder',
  'De más probable a menos probable que rompa algo en casa',
  'De mejor protagonista de película a peor protagonista',
  'De más probable a menos probable que gane un concurso de talentos',
  'De mejor detective a peor detective',
  'De más paciente a menos paciente',
  'De mejor compañero de viaje a peor compañero',
  'De más probable a menos probable que se convierta en villano',
  'De mejor niñero a peor niñero',
  'De más carismático a menos carismático',
  'De mejor médico a peor médico',
  'De más probable a menos probable que duerma todo el día',
  'De mejor alcalde a peor alcalde',
  'De más deportista a menos deportista',
  'De mejor músico a peor músico',
  'De más probable a menos probable que empiece una discusión absurda',
  'De mejor policía a peor policía',
  'De más generoso a menos generoso',
  'De mejor cita romántica a peor cita',
  'De más probable a menos probable que domine el mundo',
  'De mejor chef de restaurante a peor chef',
  'De más tranquilo a menos tranquilo',
  'De mejor héroe a peor héroe',
  'De más probable a menos probable que olvide tu cumpleaños',
  'De mejor jefe final a peor jefe final',
] as const;

export const officialSecretRankingPrompts: readonly SubjectiveCategory[] = texts.map((text, index) => ({
  id: `secret-ranking-official-${String(index + 1).padStart(2, '0')}`,
  text,
}));
