import type { SubjectiveCategory } from '../contracts.js';

const texts = [
  'De más adorable a menos adorable',
  'De mejor compañero de aventuras a peor compañero',
  'De más probable a menos probable que llegue tarde a una cita',
  'De mejor cocinero a peor cocinero',
  'De más fiable a menos fiable para guardar un secreto',
  'De mejor compañero de piso a peor compañero',
  'De más probable a menos probable que sobreviva en una isla desierta',
  'De mejor profesor a peor profesor',
  'De más elegante a menos elegante',
  'De más divertido a menos divertido en una fiesta',
  'De mejor guardaespaldas a peor guardaespaldas',
  'De más probable a menos probable que se haga influencer',
  'De mejor mascota a peor mascota',
  'De más aterrador a menos aterrador al encontrarlo de noche',
  'De más inteligente a menos inteligente',
  'De mejor líder de equipo a peor líder',
  'De más probable a menos probable que rompa algo en casa',
  'De mejor protagonista de película a peor protagonista',
  'De más probable a menos probable que gane un concurso de talentos',
  'De mejor detective a peor detective',
  'De más paciente a menos paciente',
  'De mejor compañero de viaje a peor compañero',
  'De más probable a menos probable que se convierta en villano',
  'De mejor niñero a peor niñero',
  'De más carismático a menos carismático',
  'De mejor médico a peor médico',
  'De más probable a menos probable que duerma todo el día',
  'De mejor alcalde a peor alcalde',
  'De más deportista a menos deportista',
  'De mejor músico a peor músico',
  'De más probable a menos probable que empiece una discusión absurda',
  'De mejor policía a peor policía',
  'De más generoso a menos generoso',
  'De mejor cita romántica a peor cita',
  'De más probable a menos probable que domine el mundo',
  'De mejor chef de restaurante a peor chef',
  'De más tranquilo a menos tranquilo',
  'De mejor héroe a peor héroe',
  'De más probable a menos probable que olvide tu cumpleaños',
  'De mejor jefe final a peor jefe final',
  'De más probable a menos probable que sobreviva a una cena familiar incómoda',
  'De mejor a peor coartada para llegar tres horas tarde',
  'De más probable a menos probable que tenga una segunda vida secreta',
  'De más probable a menos probable que venda humo en una charla motivacional',
  'De mejor a peor acompañante para colarse en una boda',
  'De más probable a menos probable que responda «estoy bien» cuando claramente no lo está',
  'De mejor a peor persona para compartir una cuenta de streaming',
  'De más probable a menos probable que tenga un podcast que nadie pidió',
  'De más probable a menos probable que desaparezca del grupo sin despedirse',
  'De mejor a peor compañero para cometer un crimen ficticio perfecto',
  'De más probable a menos probable que sea expulsado de un karaoke',
  'De más probable a menos probable que lea tus mensajes por encima del hombro',
  'De mejor a peor candidato para fingir ser tu pareja en una reunión',
  'De más probable a menos probable que lleve un Excel de sus enemigos',
  'De más probable a menos probable que convierta una barbacoa en una emergencia nacional',
  'De mejor a peor persona para llamar a las cuatro de la mañana',
  'De más probable a menos probable que tenga un altar dedicado a sí mismo',
  'De más probable a menos probable que gane una discusión usando datos inventados',
  'De mejor a peor compañero durante un apocalipsis absurdo',
  'De más probable a menos probable que venda el sofá para comprar criptomonedas',
  'De más probable a menos probable que mande audios de doce minutos',
  'De mejor a peor suegro o suegra Pokémon',
  'De más probable a menos probable que finja su propia muerte para evitar una reunión',
  'De más probable a menos probable que convierta un funeral ficticio en su espectáculo personal',
  'De mejor a peor persona para custodiar el botón rojo',
  'De más probable a menos probable que sea cancelado por un tuit de hace diez años',
  'De más probable a menos probable que empiece una secta por accidente',
  'De mejor a peor compañero para esconder un cadáver de película',
  'De más probable a menos probable que cobre entrada por su cumpleaños',
  'De más probable a menos probable que tenga una lista negra en Notas',
  'De mejor a peor villano de una comedia romántica',
  'De más probable a menos probable que ligue usando una presentación de diapositivas',
  'De más probable a menos probable que diga «sin dramas» y sea todo drama',
  'De mejor a peor invitado para una despedida de soltero o soltera',
  'De más probable a menos probable que se case por el buffet',
  'De más probable a menos probable que sobreviva fingiendo que sabe lo que hace',
  'De mejor a peor persona para revelar un secreto familiar en Navidad',
  'De más probable a menos probable que tenga una contraseña llamada contraseña',
  'De más probable a menos probable que convierta una cita en una entrevista de trabajo',
  'De mejor a peor portavoz durante una invasión alienígena',
] as const;

export const officialSecretRankingPrompts: readonly SubjectiveCategory[] = texts.map((text, index) => ({
  id: `secret-ranking-official-${String(index + 1).padStart(2, '0')}`,
  text,
}));
